redhat-best-practices-for-k8s/certsuite

pkg/provider/provider.go

Otherwise duplicated objects are stores in env.pods, etc.

resetting env object before refreshing it

---

Makefile
README.md

https://github.com/golangci/golangci-lint/releases/tag/v1.44.1
No code changes found/needed.

Bump GolangCI-lint to v1.44.1

---

cnf-certification-test/accesscontrol/namespace/namespace.go
internal/ocpclient/ocpclient.go
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_crds.go
pkg/provider/provider.go

Upgrading api to v1. Only change is that multiple versions are supported for CRDs. We now loop through each version to list CR objects for that version.

Bumping the CRD API to v1

---

cnf-certification-test/platform/nodetainted/nodetainted.go

Change the variable name to better represent the ClientsHolder changes from #36

Switch tainted node test to ClientHolder

---

.github/workflows/pre-main.yaml
Makefile
cnf-certification-test/lifecycle/ownerreference/ownerreference_test.go
cnf-certification-test/platform/nodetainted/nodetainted_test.go
cnf-certification-test/suite_test.go

This fix allows for running all units tests:
- The main entry point for the suite is a unit test, so needs to be excluded. 
- quality gate adjusted to 50%
- commented out 2 testcases that need to be updated

Fix for unit testing and test coverage

---

.github/workflows/pre-main.yaml
CATALOG.md
Dockerfile
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/lifecycle/ownerreference/ownerreference.go
cnf-certification-test/lifecycle/ownerreference/ownerreference_test.go
cnf-certification-test/lifecycle/suite.go
cnf-certification-test/networking/icmp/icmp.go
cnf-certification-test/networking/icmp/icmp_test.go
cnf-certification-test/networking/netcommons/netcommons.go
cnf-certification-test/networking/netcommons/netcommons_test.go
cnf-certification-test/networking/suite.go
cnf-certification-test/platform/cnffsdiff/fsdiff.go
cnf-certification-test/platform/cnffsdiff/fsdiff_test.go
cnf-certification-test/platform/suite.go
go.mod
go.sum
internal/crclient/crclient.go
pkg/loghelper/loghelper.go
pkg/provider/provider.go
pkg/provider/provider_test.go
pkg/testhelper/testhelper.go
pkg/tnf/status.go

This is to port the ipv4/ipv6 icmp testcases to the new project. 
Also includes:
- a fix for the ExecCommandContainer function due to issues running tests in github (took long time to debug).
- a new pattern (loghelper.CuratedLogLines) to store the lines of logs to store in the claims file without involving ginkgo
- a fix for building images corresponding to the current repo instead of the upstream

Porting ICMP IPv4/IPv6 networking testcases

---

cnf-certification-test/lifecycle/suite.go
pkg/provider/provider.go

Adding lifecycle node scheduling test case:
- added failed pods identity to claim file
ContainersPreStop test case:
- added additional nil check

Adding lifecycle node scheduling test case

---

Makefile

Similar to: https://github.com/test-network-function/test-network-function/pull/552
Adds a `make coverage-html` path to the Makefile.

Add make coverage-html path

---

cnf-certification-test/accesscontrol/rbac/clusterrolebinding.go
cnf-certification-test/accesscontrol/rbac/clusterrolebinding_test.go
cnf-certification-test/lifecycle/graceperiod/graceperiod.go
cnf-certification-test/lifecycle/graceperiod/graceperiod_test.go
cnf-certification-test/lifecycle/suite.go
pkg/provider/provider.go

In this test case, we look at the yaml applied configuration (found in annotation ) for the  terminationGracePeriodSeconds parameter. If it is not defined then fail the test. The test is done for deployments, statefulsets and unmanaged pods.

Porting lifecycle grace period test cases

---

cmd/tnf/generate/catalog/catalog_test.go
cmd/tnf/generate/catalog/testdata/testFile1.txt

The `catalog` packages just prints a lot of stuff, not much to actually test.  However this brought the file to:
`coverage: 38.8% of statements`

Add catalog package tests

---

cmd/tnf/addclaim/addclaim.go
cmd/tnf/addclaim/addclaim_test.go

This brings the coverage of this file to: `coverage: 25.5% of statements`
The largest function, `claimUpdate`, needs a set claim file to test so I left it uncovered for now.

Add tests for claim package

---

.github/workflows/pre-main.yaml

This is the second part of the partner PR to improve testing stateful sets. Deployment and statefulset are now created (and exist) at the same time
Before, we were testing only deployments during the smoke test run not using image and
we were only using the statefulset (no deployment) during the smoke test run with the image
This PR remove the code deleting the deployment and creating the statefulset to test the image since both statefulset and deployment are always created at the same time.
Will remove reference to pod-recreation repo before mergingno deployments

Porting:  Removing extra statefulset test #651

---

README.md
run-cnf-suites.sh

Use ./run-cnf-suites.sh -L|--list [-f SUITE...] to see all the specs
filtering optionally by suite.

run-cnf-suites.sh: add option to list the specs

---

cnf-certification-test/operator/phasecheck/phasecheck.go
cnf-certification-test/operator/phasecheck/phasecheck_test.go
cnf-certification-test/operator/suite.go
pkg/provider/provider.go

Pod recreation test case might destroy and re-create the operator pod. This PR is adding a wait so that the operator has time to go back to a succeeded phase before starting the test

Waiting for operator to be ready before testing sucessful phase

---

script/create-missing-test-files.sh

`moq.go` files don't need corresponding _test.go files.

Exclude _moq.go files from test file creation

---

cnf-certification-test/operator/suite.go
pkg/provider/provider.go

I brought back the old Operator struct from the old repo so all this
CSV-related information can be grouped under it.

Added custom struct Operator as placeholder for CSV related fields

---

.golangci.yml
Makefile
README.md

https://github.com/golangci/golangci-lint/releases/tag/v1.45.2
Similar to:
https://github.com/test-network-function/test-network-function/pull/660
https://github.com/test-network-function/cnfcert-tests-verification/pull/55
https://github.com/test-network-function/test-network-function-claim/pull/41

Update GolangCI to 1.45.2

---

go.mod

`goexpect` is no longer used in our repo.  It's a leftover from the old repo that isn't needed anymore.

Remove 'goexpect' from go.mod

---

cnf-certification-test/certification/certtool/certtool.go
cnf-certification-test/certification/certtool/certtool_test.go
cnf-certification-test/certification/suite.go

This section of the `suite.go` for the certification test suite was a bit too complex and needed some test cases.

Address complexity in certification test suite

---

pkg/provider/provider.go
pkg/provider/provider_test.go

1. Filter csv subscriptiosn based on namespace.
2. I've separated the retrieval of the subscription info from the installPlans.
They should be related, as installPlans are automatically created by OLM
once a subscription is created, but it's technically (but not
recommended) possible to install CSV by hand without using
subscriptions.
Also, added all unit tests for the csv related functions of the provider
package.

Minor changes in the createOperators() function plus UTs.

---

pkg/provider/provider.go

The configuration field does not need to have the k8s/ocp versions as
this information is already dumped in the "versions" field at the end of
the claim file.

Claim file: avoid dumping k8s/ocp versions in the configuration field.

---

cnf-certification-test/accesscontrol/rbac/automount.go
cnf-certification-test/accesscontrol/rbac/automount_test.go
cnf-certification-test/accesscontrol/rbac/clusterrolebinding.go
cnf-certification-test/accesscontrol/rbac/clusterrolebinding_test.go
cnf-certification-test/accesscontrol/rbac/rolebinding.go
cnf-certification-test/accesscontrol/rbac/rolebinding_test.go
cnf-certification-test/accesscontrol/suite.go

Similar to: #81 
Removed all of the remaining structs for access-control's tests that were still building their own structs/copies of the clientsHolder and switched them to using the clientsHolder singleton per suggestion from @greyerof.

Switch back to using singleton clientsHolder

---

cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/networking/suite.go
cnf-certification-test/platform/suite.go
cnf-certification-test/suite_test.go
internal/clientsholder/command.go
pkg/autodiscover/autodiscover.go
pkg/configuration/utils.go
pkg/provider/provider.go

When no ginkgo focus was provided, the diagnostic information retrieval
could start before the debug pods were ready, resulting in errors when
executing the commands inside the debug pods, so I've added the wait
right before the autodiscovery.
Calling WaitDebugPodsReady in the BeforeEach is no longer needed.
Other minor refactors:
- The k8s clients holder is initialized as part of the initial sequence
of the program.
- Ginkgo/Git info traces improvements.
- Added command to trace in ExecCommandContainer().
- WaitDebugPodsReady refactored to return error.
- Removed explicit function to load/process the environment variables.
Instead, the package's init() function is used, as they never need to
be reloaed/reparsed.

Wait for all the debug pods to be ready before autodiscovery starts.

---

cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/certification/suite.go
cnf-certification-test/lifecycle/suite.go
cnf-certification-test/networking/suite.go
cnf-certification-test/observability/suite.go
cnf-certification-test/operator/suite.go
cnf-certification-test/platform/suite.go
pkg/testhelper/testhelper.go

Verified each test to make sure that they would skip if not finding a required resources (pods, containers, operators, etc)
Added 2 generic function:
- SkipIfEmptyAny: takes a list of resources to check for and skip the test if any of them are empty
- SkipIfEmptyAll: takes a list of resources to check for and skip the test if all of them are empty

Skipping test cases if resources they rely on are not detected

---

pkg/tnf/utils/utils_test.go

The [old repo](https://github.com/test-network-function/test-network-function/blob/c1fe06ccf63eb75efe9a544503ad4c5b6cb9376b/pkg/utils/utils_test.go#L185) had this func tested.  Copying the tests over.  Brings this file to 100% coverage.

Add StringInSlice tests from old repo

---

pkg/diagnostics/diagnostics.go
pkg/diagnostics/diagnostics_test.go
pkg/provider/provider_test.go

Added some more unit test coverage for the `diagnostics` package.  I skipped all of the functions that require a `GetTestEnvironment()` object because at this time I'm not sure how to spoof the singleton.
- Removed `getLscpu`, `getIPConfig`, and `getLsblk` functions in favor of `getHWJsonOutput`.  These functions were essentially the same thing and needed a single parameter passed into them.
- Utilized changes from #109`clientsHolder.Command` interface for mocking out the `execCommandContainer` function.
- BONUS: Added a test in the `provider` package for `ConvertArrayPods` function.

Add unit test for diagnostics package

---

internal/crclient/crclient.go

The CI seems to be failing on an unsupported runtime.  This will help us debug that problem.

Add logging for type of runtime not supported

---

.github/workflows/merge.yaml
.github/workflows/pre-main.yaml
Dockerfile
README.md
cnf-certification-test/networking/icmp/icmp_test.go
cnf-certification-test/networking/suite.go
go.mod
internal/api/api.go
internal/api/api_test.go

Jira: https://issues.redhat.com/browse/CNFCERT-262
Our repo seems to be healthy enough running locally on Go 1.18.1.  I'll see if the CI likes it.
The GolangCI linter seems to be tracking some individual tests that don't quite work with 1.18 here: https://github.com/golangci/golangci-lint/issues/2649

Upgrade to Go 1.18.1

---

.github/workflows/pre-main.yaml

Looks like this line was missed in the old repo as well.
Fix applied in the old repo here: https://github.com/test-network-function/test-network-function/pull/670

Set pre-main to install correct ginkgo v2 version

---

cnf-certification-test/lifecycle/podrecreation/podrecreation_test.go
internal/clientsholder/clientsholder.go

Brings the `podrecreation` package from 0% to 71.8% of statements.
Had to add `ClearTestClientsHolder` to help clean up the singleton's existing k8sclient (and corresponding generated test objects).

Add tests for podrecreation package

---

cnf-certification-test/certification/certtool/certtool.go
cnf-certification-test/certification/certtool/certtool_test.go
cnf-certification-test/certification/suite.go

Broke out some more of the looping complexity to be able to better test it.  Created `GetContainersToQuery` which will look through the env for containers to query.
The `certtool` package is now at: `coverage: 93.0% of statements`.

More breakdown and testing of certification status

---

cnf-certification-test/platform/cnffsdiff/fsdiff.go
cnf-certification-test/platform/cnffsdiff/fsdiff_test.go
cnf-certification-test/platform/suite.go

The TC was failing in real OCP clusters.
The fsDiff function was not using the target container UID, so the
command was just showing this error when executed:
ERROR  [Apr 25 13:11:31.770][command.go: 76] command: chroot /host
podman diff --format json
ERROR  [Apr 25 13:11:31.770][command.go: 77] stderr: Error: "podman
diff" requires a name, id, or the "--latest" flag
ERROR  [Apr 25 13:11:31.770][command.go: 78] stdout:

Fix platform-alteration-base-image TC

---

cnf-certification-test/results/results.go

for instance:
platform-alteration-platform-alteration-isredhat-release -> platform-alteration-isredhat-release

Removing duplicate test suite name at the beginning of the test in claims file

---

cnf-certification-test/platform/hugepages/hugepages.go
cnf-certification-test/platform/hugepages/hugepages_test.go
cnf-certification-test/platform/suite.go
internal/clientsholder/clientsholder.go

Refactored the original TC to use the MachineConfig already parsed
in the autodiscovery step. Also, I moved old the helper functions into
a separate "hugepages" package.

TC migration: platform-alteration-hugepages-config TC.

---

cnf-certification-test/operator/suite.go
pkg/autodiscover/autodiscover_crds.go
pkg/autodiscover/autodiscover_operators.go
pkg/autodiscover/autodiscover_podset.go

Found a bug in the `findSubscriptions` function where it was creating the `options` var but then not using it.
This should make everything more uniform.
Might have merge conflicts with #145.

In-line the ListOptions

---

cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/lifecycle/suite.go

In 3.3.0, to pass the high availability check, the CNF should define pod anti affinity to avoid deploying Pods in the same node.
The number of replica should be higher than 1 as well.
In the current code, we check for replicas number only, this PT fixes that.

Fix High Availability Test

---

cnf-certification-test/lifecycle/suite.go

Tested locally using kind, the TC was never failing when there were not
enought nodes for the pods to be redeployed.

Fix: lifecycle-pod-recreation TC was not failing.

---

cnf-certification-test/lifecycle/suite.go
pkg/autodiscover/autodiscover_podset.go

This commit makes both deployments and statefulsets being discovered in
the same way: checking inner pod's labels to match the configured
targetPodLabels.
+ Traces improved. Show warning when no resources have been found in the
configured namespaces.

Statefulsets autodiscovery changed to check inner pod's template labels.

---

pkg/loghelper/loghelper_test.go

New coverage is `coverage: 88.2% of statements`.

Add tests for loghelper

---

CATALOG.md
cnf-certification-test/lifecycle/podrecreation/podrecreation.go
cnf-certification-test/lifecycle/podrecreation/podrecreation_test.go
cnf-certification-test/lifecycle/podsets/podsets.go
cnf-certification-test/lifecycle/suite.go

Added code to wait for the pods to be completely deleted during the pod recreation node drain. Otherwise the deployment/statefulset api will not pickup the that the pods have been deleted.
Used mutithreaded approach to speed up deletion

wait for pod to be deleted to complete the drain

---

cnf-certification-test/accesscontrol/namespace/namespace.go
cnf-certification-test/accesscontrol/namespace/namespace_test.go
cnf-certification-test/accesscontrol/suite.go

#80 accidentally broke the way the CI was checking if this test failed.  Using the `loghelper.CuratedLogLines` this will restore this functionality.

Fix claim file log

---

cnf-certification-test/accesscontrol/namespace/namespace.go
cnf-certification-test/accesscontrol/rbac/automount.go
cnf-certification-test/accesscontrol/rbac/automount_test.go
cnf-certification-test/accesscontrol/rbac/clusterrolebinding.go
cnf-certification-test/accesscontrol/rbac/common_test.go
cnf-certification-test/accesscontrol/rbac/rolebinding.go
cnf-certification-test/lifecycle/ownerreference/ownerreference.go
cnf-certification-test/lifecycle/podrecreation/podrecreation.go
cnf-certification-test/lifecycle/podsets/podsets_test.go
cnf-certification-test/lifecycle/suite.go
cnf-certification-test/networking/icmp/icmp_test.go
cnf-certification-test/networking/netcommons/netcommons.go
cnf-certification-test/observability/suite.go
cnf-certification-test/operator/phasecheck/phasecheck_test.go
cnf-certification-test/platform/hugepages/hugepages.go
internal/clientsholder/clientsholder.go
internal/clientsholder/command.go
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_crds_test.go
pkg/autodiscover/autodiscover_pods.go
pkg/autodiscover/autodiscover_pods_test.go
pkg/autodiscover/autodiscover_podset.go
pkg/diagnostics/diagnostics.go
pkg/diagnostics/diagnostics_test.go
pkg/provider/provider.go
pkg/provider/provider_test.go

We import a lot of libraries, and it getting difficult to figure out which one we were referencing and in places where we did use unique import names, they weren't consistent. 
Changes:
- `v1` ambiguity in naming convention replaced by the module+v1
- Module naming changed (if applicable) from example `v1rbac` to `rbacv1` to match repo-wide.

Be consistent in import naming convention

---

pkg/testhelper/testhelper_test.go

New coverage level: `coverage: 90.9% of statements`.
To be honest these two functions seem very similar and there might be room to merge the two in a subsequent PR.

Add tests for SkipIfEmpty funcs

---

cnf-certification-test/certification/suite.go
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_operators.go
pkg/provider/provider.go

The subscriptions discovery was wrong as it was using labels to find
them. I've changed that and also removed the subscriptions slice as it's
never used.
+ Includes PR #186 changes plus some naming refactors.

Do not use labels to discover subscriptions.

---

.github/workflows/update-certification.yml

This commit tries to fix this error that appears in the job logs:
Error: When the repository is checked out on a commit instead of a
branch, the 'base' input must be supplied.

Fixed job to download the certified targets DB.

---

.github/workflows/update-certification.yml

The jobs seems to work, but it's not triggering the PR check actions as
a repo token is needed for this. See:
https://github.com/peter-evans/create-pull-request/blob/main/docs/concepts-guidelines.md#triggering-further-workflow-runs

Add repo access token to the update certified db job.

---

README.md
cnf-certification-test/tnf_config.yml

Both operator and affiliated-certification test suites use operators
autodiscovered by the "test-network-function.com/operator" label 
applied to the target CSVs since PR #570 (old repo).
Also, README updated, fixing some references to the old repo.

Remove certifiedoperatorinfo section in the yaml config file.

---

cnf-certification-test/certification/suite.go
internal/registry/operator.go
internal/registry/operator_test.go
pkg/provider/provider.go

The previous code was not considering the channel stream for the
operator certification check, which could produce false positives.

Added channel stream to operator certification check.

---

cnf-certification-test/lifecycle/podsets/podsets.go
cnf-certification-test/lifecycle/scaling/deployment_scaling.go
cnf-certification-test/lifecycle/scaling/deployment_scaling_test.go
internal/clientsholder/clientsholder.go

`coverage: 14.1% of statements` 
I will add more tests for the HPA Scaler (very similar) in another PR.
- Changed `WaitForDeploymentSetReady` to be a func var to be able to override the check for AvailableReplicas.
- Removed `v1.DeploymentInterface` from the call to `scaleDeploymentHelper` as it was not necessary.

Add scaling unit tests

---

pkg/autodiscover/autodiscover_test.go

`coverage: 20.8% of statements`
I didn't include tests for `getOpenshiftVersion` or `DoAutoDiscover` in this.

Add autodiscover unit tests

---

.github/workflows/merge.yaml
.github/workflows/pre-main.yaml
.github/workflows/update-certification.yml

https://github.com/actions/setup-go/releases/tag/v3.0.0
v3 is the latest available release of `setup-go`.
Semi-related to #204

Upgrade to v3 setup-go action

---

Makefile

The build-cnf-tests-debug target was using wrong keys for the linker
flags, so the "TNF Version" wasn't printed:
[suite_test.go: 136] TNF Version         : Unreleased build post  (  )
They were set as github.com/**cnf-certification-test**/... instead of
github.com/**test-network-function**/...
Also, added those linker vars as env var to shorten the ginkgo build
command.

Fix linker release variables for the debug version.

---

cnf-certification-test/platform/suite.go

If there are "other" tainted kernel failures than the `module was loaded` failures, report them as part of the claim file printout.

Surface more information about tainted kernel failures

---

.github/workflows/pre-main.yaml

#185 added this shellcheck linter but #196 missed the version bump.

Missed shellcheck ubuntu version

---

version.json

In preparation for the v4.0.0 release we are setting the partner repo version to tag 4.0.0 which can be found here: https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.0.0

Update partner release tag to v4.0.0

---

.github/workflows/pre-main.yaml
.github/workflows/tnf-image.yaml
.github/workflows/update-certification.yml

This issue [here](https://github.com/actions/virtual-environments/issues/5490) is preventing docker from running properly inside the 22.04 image.  Once it is fixed we will revisit.

Revert change to 22.04 ubuntu version

---

.github/workflows/tnf-image.yaml

This was causing the v4.0.0 image publish run to fail.

Add working directory in tnf_image.yaml

---

.github/workflows/pre-main.yaml
.github/workflows/tnf-image.yaml
Dockerfile

- Remove the Dockerfile references to the oc client.  Not needed anymore.
- Removed `RELEASE_LEVEL` vars. Not needed.
- Change `yum` to `dnf`.  Add `dnf update`.

Remove references to oc client

---

cnf-certification-test/observability/suite.go

When getting the log buffer from k8s containers, both the 'oc' client
and the go-client won't return the last line in case it doesn't have the
new line char at the end, so this TC will fail in rare cases when the
container has printed newline-ended lines before but the last one
doesn't have the newline char yet.
This fix just reads the last 2 log lines, so in case there's previous
valid lines, this TC will pass.

Fix for observability-container-logging TC.

---

cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/platform/suite.go

We perform the same nil check in the following spots:
- https://github.com/test-network-function/cnf-certification-test/blob/main/cnf-certification-test/accesscontrol/suite.go#L412-L416
- https://github.com/test-network-function/cnf-certification-test/blob/main/cnf-certification-test/platform/bootparams/bootparams.go#L36-L40
I think the underlying issue we were seeing in a [recent failure](https://www.distributed-ci.io/jobs/9048dacf-b2cc-440d-b0af-5a10170434bd/files) was that the debug pods either weren't spawned correctly or unresponsive but this nil check should have been in place to catch it in the first place.

Avoid nil panic when debug pod missing

---

cmd/tnf/fetch/fetch.go
go.mod
go.sum
internal/api/api.go
internal/registry/helm.go
pkg/configuration/utils.go

Upstream repo: https://github.com/go-yaml/yaml
Switches all references to the upstream YAML package we use from `"gopkg.in/yaml.v2"` to `"gopkg.in/yaml.v3"`.  Then I ran `go mod tidy` to finish it up.
Also see: https://github.com/test-network-function/cnf-certification-test/security/dependabot/7

Upgrade YAML package to v3

---

cnf-certification-test/networking/netcommons/netcommons.go
cnf-certification-test/platform/hugepages/hugepages.go
cnf-certification-test/platform/nodetainted/nodetainted.go

`strings.Builder` is a more efficient way of building strings.
More information about efficiency: 
https://medium.com/@ramseyjiang_22278/join-string-using-strings-builder-6-simple-ways-to-optimise-golang-4-59f3fdf630f
Examples: https://zetcode.com/golang/builder/

Optimize around strings.Builder

---

Makefile
cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/lifecycle/suite.go
cnf-certification-test/platform/suite.go
cnf-certification-test/suite_test.go
go.mod
go.sum

Instead of seeing a failure like:
```
tnf.ClaimFilePrintf("bad containers: %v", badContainers)
gomega.Expect(badContainers).To(gomega.BeNil())
```
I wanted to add more context to the failures instead of just seeing a list of "bad containers" in DCI output.

Remove gomega; add more context to failures

---

pkg/testhelper/testhelper_test.go

Adding a unit test case in the TestHelper unit tests for nil objects.  No functional change.  Utilizes the `assert.Panics` func.

Add nil check in testhelper

---

cnf-certification-test/common/constant.go

Related to: https://github.com/test-network-function/test-network-function/pull/591
This must have fell through the cracks when we were copying things over from the old repo.

Remove unused diagnostic and common key

---

cnf-certification-test/lifecycle/suite.go
pkg/provider/provider.go
pkg/provider/provider_test.go

Adding a safeguard against running the pod-recreation test case against a cluster with less than two workers.
Bonus, I also added the same check around the `testDeploymentScaling` and `testStatefulSetScaling` tests because even if we are attempting to scale these up/down, if they are properly using anti-affinity rules they'll never scale correctly anyways.

Add safeguard for SNO clusters

---

internal/api/api.go
internal/api/offlinecheck/operator.go
internal/api/offlinecheck/operator_test.go
internal/api/onlinecheck/onlinecheck.go

The URL to get the operator info was using the "package" field to filter, but there's also a "csv_name" on each entry that can be used as a filter, as that's exactly the field we're using in our TC. Also, the offline checker uses the csv name by default (see `buildOperatorKey()` so now both checkers online/offline are aligned.

Use CSV name to search in online catalog.

---

pkg/provider/provider.go

On slow connections or overloaded clusters, downloading the container
image and starting it may take a bit more than one minute.

Increased timeout for waiting for the debug pods to be up.

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/platform/suite.go
pkg/autodiscover/autodiscover.go
pkg/compatibility/compatibility.go
pkg/compatibility/compatibility_test.go
pkg/provider/provider.go

Adds what is essentially a hardcoded set of dates tied to specific OCP version based on the table found [here](https://access.redhat.com/support/policy/updates/openshift).
We already pulled in the OCP version from the cluster version operator so it was just a matter of comparing that version to the table and logging the results.
As far as I could find, there wasn't an API that served this information out so I figured the next best way would be to keep some sort of local table since this date-based information doesn't seem to change very often anyways.
The second part of the issue 205 is that we wanted to compare the RHEL worker version to the OCP version to see if any workers were incompatible but I haven't been able to find a table comparing those numbers.

Add compatibility matrix for testing OCP versions

---

cnf-certification-test/platform/nodetainted/nodetainted.go
cnf-certification-test/platform/nodetainted/nodetainted_test.go
pkg/stringhelper/stringhelper.go
pkg/stringhelper/stringhelper_test.go

Does not belong in the `nodetainted` package specifically if we have a `stringhelper` package.

Move RemoveEmptyStrings to stringhelper

---

.github/workflows/pre-main.yaml
Dockerfile
cnf-certification-test/chaostesting/suite.go
pkg/provider/provider.go
run-cnf-suites.sh

Okay I set the folder where to copy the files as `/usr/tnf/chaostesting/chaos-test-files/`.
I believe the binary lives in `/usr/tnf` as well:
```
ENV TNF_DIR=/usr/tnf
ENV TNF_SRC_DIR=${TNF_DIR}/tnf-src
ENV TNF_BIN_DIR=${TNF_DIR}/cnf-certification-test
```
This should be the correct path but I'll need some additional reviews.

Copy chaostesting files in via Dockerfile

---

cnf-certification-test/platform/suite.go

`cut.String()` prints out all of the details about the container instead of just the pod name.

Print more details about containers that fail the fsdiff test

---

cnf-certification-test/platform/suite.go

- Wrap `testNodeOperatingSystemStatus` with the check for OCP cluster.
- Fix the error message printing to print the combination of all of the errors in the failure message.

Fix the CI; OCP test fails because it runs Ubuntu

---

.github/workflows/update-rhcos-mapping.yml

- Checkout the actual code before running.  😄 
- Add spacing.
The [latest run](https://github.com/test-network-function/cnf-certification-test/runs/7225806609?check_suite_focus=true#step:2:8) failed because the Github Action was not checking out the code properly prior to running.

Fix RHCOS automation

---

internal/api/offlinecheck/container_test.go

These two references images were removed in one of the recent automated runs that update the offline database.  I replaced them with an image that is currently available.

Fix offline certification unit tests

---

CATALOG.md
cnf-certification-test/chaostesting/suite.go
cnf-certification-test/identifiers/identifiers.go

The TC code is still there so it can also be manually run (after
removing the skip), for internal tests, but the catalog entry has been
removed so we can decide whether to keep chaos testing as part of TNF or
just agree on the final list of chaos test cases to be implemented
here.

Chaos testing pod-delete test case disabled and removed from catalog.

---

Dockerfile

Instead of using `-a` we should just specify the file.
The QE was failing because the path to the file was: `/usr/tnf/cnf-certification-test/platform/operatingsystem/files/files/rhcos_version_map`

Fix rhcos_version_map copy

---

internal/projectpath/projectpath.go

The `projectpath` package was causing the QE failures such as: 
`Error: open /usr/tnf/tnf-src/cnf-certification-test/platform/operatingsystem/files/rhcos_version_map: no such file or directory`
This was because we were asking for the root directory instead of just using the working directory.  Using `os.Getwd()` this allows us to get the working directory correctly which should point us correctly at `cnf-certification-test/platform/operatingsystem/files/rhcos_version_map`.

Fix projectpath to handle proper workingdir

---

pkg/provider/provider.go

#350 once again had the wrong path.
```
/usr/tnf/cnf-certification-test/platform/operatingsystem/files
versus
/usr/tnf/cnf-certification-test/cnf-certification-test/platform/operatingsystem/files
```

Remove 'cnf-certification-test/' from path to RHCOS map file

---

cnf-certification-test/platform/suite.go

- Added a debug line showing how many nodes there are to test.
- Fix the failure logic to only `ginkgo.Fail` if there are any failed workers/masters.

Fix node OCP version test failure logic

---

CATALOG.md
cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/identifiers/identifiers.go
pkg/provider/provider.go
pkg/provider/provider_test.go

Adds a new test to the `access-control` test suite.
Compares the containers labeled for test and whichever node's kernel type they are running on to see if they have `SYS_NICE` security context capability enabled. 
Some helpful links:
- https://www.redhat.com/sysadmin/real-time-kernel

Add SYS_NICE realtime kernel check

---

Makefile
cnf-certification-test/lifecycle/podrecreation/podrecreation.go
cnf-certification-test/networking/suite.go

- `waitPodDeleted` doesn't return anything other than `nil`.
- `testNetworkConnectivity` was only ever using `defaultNumPings`.
Note I had to bump the timeout to 6 minutes because the CI was too slow (by a few seconds) running the linter.

GolangCI-lint v1.47.1; fix lint problems

---

Makefile
cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/platform/suite.go

`staticcheck` seems to hate that `debugPod == nil` doesn't return immediately after instead of calling ginkgo.Fail.
Semi related to #369.  Not sure why it didn't flag these originally. The PR [passed the CI](https://github.com/test-network-function/cnf-certification-test/actions/runs/2733634001).
Also, I had to bump the timeout again because of https://github.com/golangci/golangci-lint/issues/2997

Address more lint problems

---

version.json

https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.0.2
Preparing for v4.0.2 by pointing it at the correct tag of the -partner repo.

Update partner tag to v4.0.2

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/identifiers/remediation.go
cnf-certification-test/lifecycle/suite.go

Simple test to check for the existence of `requests` and `limits` on a container spec which corresponds to 4.6.11 in the new v1.4 requirements document.  Note, I don't know if we have a public link yet for the v1.4 document so I marked it as TODO.

Add test for requests and limits for containers

---

run-tnf-container.sh

Currently '-f access-control platform-alteration' from
dci-openshift-app-agent are passed as
'-f platform-alteration access-control ', see trailing space. The
fix keeps original order and remove the space.

Fix reverse order of suites with trailing space

---

Makefile
cmd/tnf/fetch/fetch.go
cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/platform/suite.go

https://github.com/golangci/golangci-lint/releases/tag/v1.47.3
Some upstream fixes.  Following up to #369 where I had to add some wrappers for ginkgo.Fail getting flagged in the linter.

Update golangci-lint to v1.47.3; remove staticcheck workaround

---

cnf-certification-test/accesscontrol/suite.go

Print the message to the claim file instead of to `logrus`.

Send output to the claim file for sys_nice

---

cnf-certification-test/platform/hugepages/hugepages.go
cnf-certification-test/platform/hugepages/hugepages_test.go
cnf-certification-test/platform/suite.go

- TC updated to check whether some hugepages sizes found in the node
exist in the MC Systemd/MC KernelArguments configuration. If those
sizes were not explicitly configured in the machine config, the count of
hugepages for all those sizes in the node must be zero.
- Refactored to use maps instead of slices in order to make it a bit
easier to compare.
- Every mismatch between node and MC returns an error now.
- Added UTs for both hugepages configs in machine config: kernelArgs
and systemd units.

Fix for platform-alteration-hugepages-config test case.

---

pkg/compatibility/compatibility.go

The lifecycle dates were updated for 4.9 here: https://access.redhat.com/support/policy/updates/openshift

Update the 4.9 OCP compatibility dates

---

CATALOG.md
cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/accesscontrol/tolerations/tolerations.go
cnf-certification-test/accesscontrol/tolerations/tolerations_test.go
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/identifiers/remediation.go

A new test that will check the existence of the default k8s tolerations on pods and if they are modified or added to this will flag a failure.
This is referenced in section 10.6 of the [v1.3 requirements doc](https://connect.redhat.com/sites/default/files/2022-05/Cloud%20Native%20Network%20Function%20Requirements%201-3.pdf).

Add toleration check test

---

cnf-certification-test/accesscontrol/suite.go

The #380 and #365 tests were added but only printed to the log file when a pod was found to have fail their respective tests.  Similar to #399 we should have addressed it everywhere.

Print to claim file instead of logrus

---

cnf-certification-test/accesscontrol/suite.go

Whoops, I accidentally wasn't printing the pod name where it should have been.

Fix toleration err message

---

.golangci.yml
CATALOG.md
cmd/tnf/fetch/fetch.go
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/identifiers/remediation.go
cnf-certification-test/lifecycle/suite.go
internal/clientsholder/clientsholder.go
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_pv.go
pkg/autodiscover/autodiscover_pv_test.go
pkg/provider/provider.go

Looks through all of the persistent volumes in the cluster and if they are not using `ReclaimPolicy: Delete` they are flagged as a failure.
Refers to section 3.3.4 in the v1.4 requirements document.
Also, I removed the `dupl` and `noctx` linters because I could get them to pass even with `nolint` tags.  🤷

Add test for persistent volume reclaim policy

---

cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/identifiers/remediation.go
cnf-certification-test/networking/suite.go
pkg/diagnostics/diagnostics.go

I wanted to fix the inconsistency between the capitalization of the word `OpenShift` to better align with the naming convention used by the rest of the docs.
`Openshift --> OpenShift`

Fix capitalization in 'OpenShift'

---

cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/accesscontrol/tolerations/tolerations.go
cnf-certification-test/accesscontrol/tolerations/tolerations_test.go

**Context**
In [this change](https://github.com/test-network-function/cnf-certification-test/pull/407), it was discussed that there is a toleration that seems to be added by k8s and is not being treated by the `access-control-pod-toleration-bypass`, so that it is not considered as a modified toleration.
The reason why this memory-issue toleration is appearing is because QoS class applied to the pods under test. If resource limits (for CPU and RAM) are defined, according to this [k8s docs](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/#taint-nodes-by-condition), it is said that "The control plane also adds the node.kubernetes.io/memory-pressure toleration on pods that have a [QoS class](https://kubernetes.io/docs/reference/glossary/?all=true#term-qos-class) …

Do not fail if memory-pressure toleration is present and qosClass is different than BestEffort

---

pkg/compatibility/compatibility.go

https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html
Also:
- 4.9 has moved to maintenance support.

Update compatibility pkg for 4.11 release

---

.golangci.yml
Makefile
README.md
cmd/tnf/generate/catalog/catalog.go
cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/chaostesting/pod_delete/pod_delete.go
cnf-certification-test/lifecycle/suite.go
cnf-certification-test/networking/suite.go
cnf-certification-test/observability/suite.go
cnf-certification-test/operator/suite.go
cnf-certification-test/platform/cnffsdiff/fsdiff.go
cnf-certification-test/platform/suite.go
internal/clientsholder/clientsholder.go
pkg/autodiscover/autodiscover.go
pkg/autodiscover/constants.go
pkg/claimhelper/claimhelper.go
pkg/loghelper/loghelper.go

https://github.com/golangci/golangci-lint/releases/tag/v1.48.0

Upgrade GolangCI-lint to v1.48.0

---

.golangci.yml
Makefile
README.md

https://github.com/golangci/golangci-lint/releases/tag/v1.49.0

Upgrade GolangCI-lint to v1.49.0

---

cnf-certification-test/networking/netutil/netutil.go
cnf-certification-test/networking/suite.go

build-depends: 25943
According to this bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1915027
The machine config operator configures iptables for every pods to prevent access to the machine config server. If these rules are seen still pass the test. 
I am not sure how well this is going to work in the future or for various versions of openshift since these rules could change
Also now running the ip6tables-save command. nft list ruleset covers both ip v4/v6 so no need for 2 calls.
https://github.com/test-network-function/cnf-certification-test-partner/pull/155 removes completely iptables and nftables to prevent any configuration

Ignoring nftable and iptables rules set by machine-config operator

---

.github/workflows/pre-main.yaml
.github/workflows/update-certification.yml
Makefile

https://github.com/test-network-function/cnf-certification-test/pull/463 bumped the go.mod, needs a manual change for the other references.

Manually bump Ginkgo to v2.1.5

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go
go.mod

This is an helper function making adding test cases to the catalog a bit easier. One call creates the full entry, the function takes the various required string as parameters, for instance TC name, description, remediation, etc

Helper for adding test cases in the catalog

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/identifiers/remediation.go
cnf-certification-test/networking/policies/policies.go
cnf-certification-test/networking/policies/policies_test.go
cnf-certification-test/networking/suite.go
internal/clientsholder/clientsholder.go
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_networkpolicies.go
pkg/autodiscover/autodiscover_networkpolicies_test.go
pkg/provider/provider.go

build-depends: 25993
Depends on: https://github.com/test-network-function/cnf-certification-test-partner/pull/144
Adds a test to make sure that any network policies attached to namespaces running CNF workloads have a default `deny-all` type of network policy for both ingress and egress traffic.
This requires work on the side of the partner running their CNF workload to make sure they have not only a default network policy but a policy that allows the traffic that they need specifically.  Eg. allowing pods in a single namespace to talk to each other.

Add test for deny-all network policy

---

cnf-certification-test/platform/sysctlconfig/sysctlconfig.go

Added a fix to the GetSysctlSettings func, the sysctlCommand should run with a chroot /host prefix.

Add fix for the sysctlCommand in sysctl-config tc

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go

Building upon https://github.com/test-network-function/cnf-certification-test/pull/452 to build catalog entries with `AddCatalogEntry()`.  Other entries can be switched later as well.

Move DenyAllIdentifier to new scheme

---

cnf-certification-test/identifiers/identifiers.go

I missed the `common.NetworkingTestKey` when building my catalog entry.

Add networking test key

---

cnf-certification-test/lifecycle/suite.go

If there are no `Pods` or `PersistentVolumes`, skip the test.

Add skip for reclaim policy test

---

cnf-certification-test/lifecycle/suite.go
pkg/provider/provider.go

Resolves #497 
Creates a list of `NonGuaranteedPods` then change `testPodNodeSelectorAndAffinityBestPractices` func to only parse through the list of `NonGuaranteedPods` to avoid any problems with runtimeClasses potentially having node selectors.

Exclude guaranteed pods from node selector check

---

cnf-certification-test/chaostesting/suite.go
cnf-certification-test/lifecycle/podsets/podsets.go
cnf-certification-test/lifecycle/podsets/podsets_test.go
cnf-certification-test/lifecycle/scaling/deployment_scaling.go
cnf-certification-test/lifecycle/suite.go
pkg/provider/provider.go
pkg/provider/provider_test.go

Created two new structs in provider.go to wrap the `Deployment` and `StatefulSet` k8s objects in our own wrappers.  Utilizing untyped variables to all for direct access to the underlying k8s struct variables in our funcs.
For example, note that no variable name is needed:
```
type Deployment struct {
*appsv1.Deployment
}
```

Consolidate into deployment/statefulset structs

---

CATALOG.md
cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/identifiers/remediation.go

Utilizes `tagExtended` to make this run as part of the extended test suite.
Similar to #493 as they are part of the same issue.
Previous PR: #136 
Marked WIP until I can test this.

Add extended test for UID 1337

---

cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/lifecycle/podsets/podsets.go
cnf-certification-test/lifecycle/suite.go
cnf-certification-test/manageability/suite.go
cnf-certification-test/networking/icmp/icmp.go
cnf-certification-test/networking/icmp/icmp_test.go
cnf-certification-test/networking/netcommons/netcommons_test.go
cnf-certification-test/networking/suite.go
cnf-certification-test/observability/suite.go
cnf-certification-test/platform/bootparams/bootparams.go
cnf-certification-test/platform/suite.go
internal/crclient/crclient.go
pkg/provider/isolation.go
pkg/provider/isolation_test.go
pkg/provider/provider.go
pkg/provider/provider_test.go

Similar to #501 that did the same for `Deployment` and `StatefulSet`.  This removes the "Data" variable from the struct that wraps the k8s structs themselves.

Switch Pod and Container to nest the k8s structs

---

cnf-certification-test/lifecycle/suite.go

https://kubernetes.io/docs/concepts/storage/persistent-volumes/#a-note-on-namespaces
```
PersistentVolumes binds are exclusive, and since PersistentVolumeClaims are namespaced objects, mounting claims with "Many" modes (ROX, RWX) is only possible within one namespace.
```
Just because the PV uses the `ObjectMeta` doesn't mean that the `Namespace` field is populated.  Removing this log line from the string.

Remove namespace from log in PV test

---

internal/daemonset/daemonset.go

Nodes with k8s version v1.24 in kind have a new toleration for the control-plane+worker nodes. We need to add it here, otherwise the pod won't run on that node, making CI to fail.
Signed-off-by: Gonzalo Reyero Ferreras <greyerof@redhat.com>

Add control-plane toleration to daemonset.

---

pkg/provider/containers.go
pkg/provider/containers_test.go
pkg/provider/deployments.go
pkg/provider/deployments_test.go
pkg/provider/nodes.go
pkg/provider/nodes_test.go
pkg/provider/pods.go
pkg/provider/pods_test.go
pkg/provider/provider.go
pkg/provider/statefulsets.go
pkg/provider/statefulsets_test.go

Take the existing provider.go and break it down into files specific to whatever objects they are dealing with:
- containers.go
- pods.go
- deployments.go
- nodes.go
- pods.go
- statefulsets.go
I plan on going back after this PR and adding more unit testing (if needed) for some of these files and their corresponding funcs.

Break down provider into multiple files

---

cnf-certification-test/suite_test.go

Diagnostic mode also needs the daemonset pods so we can get all the node information through them.
Also, TNF will stop execution if the daemonset hasn't been deployed correctly, as a lot of TCs relay on it to work.

Fix to deploy the daemonset also in diagnostic mode.

---

.golangci.yml
cnf-certification-test/lifecycle/suite.go
cnf-certification-test/platform/nodetainted/nodetainted.go
internal/crclient/crclient.go
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_events.go
pkg/autodiscover/autodiscover_events_test.go
pkg/autodiscover/autodiscover_pods.go
pkg/autodiscover/autodiscover_pods_test.go
pkg/diagnostics/diagnostics.go
pkg/junit/convert.go
pkg/postmortem/postmortem.go
pkg/postmortem/postmortem_test.go
pkg/provider/events.go
pkg/provider/events_test.go
pkg/provider/provider.go
pkg/testhelper/testhelper.go

This PR is to add post-mortem information during the pod-recreation test similar to how it was implemented in previous project:
- collects the pending pods
- collects the node status (taints)
- collects the non-normal events in the namespaces under test
- Adding a AllPods list to record pods that are pending or in other error states
Also tweaks the min-occurrences in golint to 2 instead of 1 (e.g. make a constant if a string is used more than once)

add postmortem information to claims file

---

cnf-certification-test/lifecycle/podrecreation/podrecreation.go
cnf-certification-test/lifecycle/podrecreation/podrecreation_test.go
cnf-certification-test/lifecycle/suite.go

This PR enables limiting the scope of draining a particular node by just deleting the pods that are:
- under test and 
- controlled by a statefulset or deployment 
- running on the node being drained
Previous behavior drained all pods belonging to deployments running on the node being drained

Drain only pods under test

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/identifiers/remediation.go
cnf-certification-test/networking/netcommons/netcommons.go
cnf-certification-test/networking/suite.go

Utilizes `tagExtended` to designate this test as part of the extended test suite.
I'm open to reworking the "by Partner" strings that appear in the logging.
I took advantage of the existing func `testOCPReservedPortsUsage` which essentially did what we wanted to do for this extended test.  To facilitate this, I created two funcs in the `netcommons` package: `FindRogueContainersListeningToPorts` and `FindRoguePodsListeningToPorts`.
Both the old func and new func use these two new `netcommons` functions to achieve their goals.

Add extended test for reserved ports

---

CATALOG.md
README.md
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/identifiers/remediation.go
cnf-certification-test/lifecycle/suite.go
pkg/provider/deployments.go
pkg/provider/deployments_test.go
pkg/provider/pods.go
pkg/provider/pods_test.go
pkg/provider/provider.go
pkg/provider/statefulsets.go
pkg/provider/statefulsets_test.go

build-depends: 26152
Adds a test to the `lifecycle` suite that checks for a label `AffinityRequired: true` to be supplied for workloads that require colocation of pods. 
- Tests pods, deployments, and statefulsets.
- Adds "groupings" section(s) into the provider.go.
- Adds `AffinityRequired()` and `IsAffinityCompliant()` funcs to each of the above structs.
- Had to modify `testPodNodeSelectorAndAffinityBestPractices` to avoid pods that have `AffinityRequired` flags.  This func was already looping through NonGuaranteedPods.  Maybe there is a way to do cross-sections of different lists of pods we could implement later.
- The `IsAffinityCompliant` tests are all relatively the same with some copy/pasting.

Add AffinityRequired test to lifecycle

---

cnf-certification-test/lifecycle/suite.go
cnf-certification-test/platform/suite.go
pkg/provider/filters.go
pkg/provider/filters_test.go
pkg/provider/provider.go

I created `pkg/provider/filters.go` to house all of these environment funcs to filter Pods, Deployments, StatefulSets on the fly versus once during the autodiscover.  I can see where this might be problematic as far as running the filtering multiple times however I think it will help clean up the code in the long run.
For example, see `lifecycle/suite.go`.  Instead of using our slice of NonGuaranteedPods and then filtering, I'm combining all of the logic into `GetNonGuaranteedPodsWithAntiAffinity()`.  This can help get all of the _filtering_ out of the way prior to running the test.

Turn groupings into env funcs

---

pkg/provider/containers.go
pkg/provider/pods.go
pkg/provider/provider.go

build-depends: 26082
In some recent tests where a partner is actually using Istio, there are a number container related tests that are failing/flagging istio-proxy containers.  The tests are:
```
networking-undeclared-container-ports-usage
observability-termination-policy
lifecycle-liveness
lifecycle-image-pull-policy
lifecycle-container-shutdown
```
So what I did was add a check function on the `Container` object that will allow us to ignore any containers that have a known container name that causes failures.

Skip known container names

---

CATALOG.md
cmd/tnf/generate/catalog/catalog.go
cnf-certification-test/identifiers/identifiers.go

Resolves: #551 
Any catalog entry generated by the `AddCatalogEntry` helper function will now include its tags in the catalog.  This will be the initial commit and we will have to have a subsequent commit that translates all of the existing catalog entries to use the helper function.

Add tags to the catalog entries

---

cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/lifecycle/suite.go
cnf-certification-test/networking/suite.go

Follow up to: https://github.com/test-network-function/cnf-certification-test/pull/560
This is everything from #560 minus the changes for the networking suite that might have covered up a potential bug with how we were using `ss`.

Reporting cleanup

---

cnf-certification-test/accesscontrol/pidshelper_test.go
cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/platform/bootparams/bootparams.go
cnf-certification-test/platform/hugepages/hugepages.go
cnf-certification-test/platform/isredhat/isredhat_test.go
cnf-certification-test/platform/suite.go
cnf-certification-test/platform/sysctlconfig/sysctlconfig.go
internal/clientsholder/clientsholder.go
internal/clientsholder/command.go
internal/crclient/crclient.go
pkg/diagnostics/diagnostics.go

Further compartmentalize the clientsholder `Context` struct by using a more constructor-esque style with appropriate Getter functions.
Created a new `NewContext` func to help build clientsholder.Context objects.

Switch clientsholder to user constructor style

---

.github/workflows/merge.yaml
.github/workflows/pre-main.yaml
.github/workflows/update-certification.yml
Dockerfile

https://groups.google.com/g/golang-announce/c/xtuG5faxtaU
Security: Includes security fixes for archive/tar (CVE-2022-2879), net/http (CVE-2022-2880), and regexp (CVE-2022-41715).

Update Go to v1.19.2

---

pkg/provider/deployments_test.go
pkg/provider/pods_test.go
pkg/provider/provider_test.go
pkg/provider/statefulsets_test.go

Found some stragglers when it comes to the deployment, pod, statefulset tests.

Move some tests to their respective files

---

cnf-certification-test/platform/nodetainted/nodetainted.go
cnf-certification-test/platform/nodetainted/nodetainted_test.go
cnf-certification-test/platform/suite.go

This test case was panicking in a 3-nodes cluster with OCP 4.10 due to bit 29 being set in one of the nodes.
```
runtime error: index out of range [29] with length 18
Full Stack Trace
github.com/test-network-function/cnf-certification-test/cnf-certification-test/platform/nodetainted.DecodeKernelTaints(0x20000000)
```
Some RHEL/CoreOS kernels were/are upgraded to use bits 27-31 as Red Hat extension taint bits. See https://access.redhat.com/solutions/40594 for more information about this extensions on each RHEL version.
Also, I added the standard kernel taint bit 18 which was either left out by mistake or added to the linux kernel recently.
- Changed taint messages list from slice to map.
- Refactored DecodeKernelTaints func.
- Updated UT for DecodeKernelTaints.

Added support for Red Hat kernel taints bits 27-31

---

cnf-certification-test/tnf_config.yml
internal/api/onlinecheck/api_test.go

build-depends: https://github.com/dci-labs/dallas-pipelines/pull/551
build-depends: 26470
The RocketChat container digest was updated in RH's online catalog due to a migration of very old images with invalid schemas.

Fixed UT for online certification checks.

---

CATALOG.md
README.md
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/lifecycle/suite.go
pkg/provider/deployments.go
pkg/provider/deployments_test.go
pkg/provider/filters.go
pkg/provider/statefulsets.go
pkg/provider/statefulsets_test.go

Thanks to @shaior for pointing out these redundant tests.
Essentially what we were doing was duplicating tests when all we needed to look at was the Pod YAMLs.
For example, `st.Spec.Template.Spec.Affinity.PodAntiAffinity` was what we were looking for when it came to the statefulset affinitycompliant check.  This was going into the "Template" section which essentially became the Pod YAML.
Also, I added a skip to the `highAvailability` test to skip whenever we encounter a deployment/statefulset that contains a pod spec like:
```
// Skip any AffinityRequired pods
//nolint:goconst
if dp.Spec.Template.Labels["AffinityRequired"] == "true" {
continue
}
```

Remove redundant affinity/anti-affinity tests

---

internal/api/offlinecheck/container_test.go

Looks like the SHA got changed from `c358eee360a1e7754c2d555ec5fba4e6a42f1ede2bc9dd9e59068dd287113b33` to `03f7f2499233a302351821d6f78f0e813c3f749258184f4133144558097c57b0`.

Fix the rocketchat offline test

---

.github/workflows/pre-main.yaml
.github/workflows/update-certification.yml
Makefile

https://github.com/onsi/ginkgo/releases/tag/v2.4.0
The dependabot PR hasn't came up yet, so this is preemptive.

Manual update for ginkgo v2.4.0

---

Makefile
README.md
cnf-certification-test/platform/suite.go

https://github.com/golangci/golangci-lint/releases/tag/v1.50.1

Update GolangCI-Lint to v1.50.1

---

cnf-certification-test/accesscontrol/resources/resources_test.go
cnf-certification-test/accesscontrol/tolerations/tolerations.go
cnf-certification-test/accesscontrol/tolerations/tolerations_test.go
pkg/postmortem/postmortem.go
pkg/provider/isolation_test.go

Rename `v1` to `corev1` across some files to be more consistent.
Similar to: https://github.com/test-network-function/cnf-certification-test/pull/177

Be consistent with import naming

---

pkg/provider/containers.go
pkg/provider/provider_test.go

I was looking at the `containers.go` and I saw that we have a `GetContainer()` that just makes a new `Container` object.  And it was only used in one spot, so I'm not entirely sure that it needs to exist in the first place but I wanted to change the name to what it's actually doing.

Switch GetContainer to NewContainer

---

pkg/provider/provider.go

`IsinstalledCsv` seems to be unused.

Remove unused func

---

cnf-certification-test/certification/suite.go
cnf-certification-test/chaostesting/suite.go
cnf-certification-test/lifecycle/suite.go
cnf-certification-test/manageability/suite.go
cnf-certification-test/observability/suite.go
cnf-certification-test/operator/suite.go

To match the networking suite that already has this [log line](https://github.com/test-network-function/cnf-certification-test/blob/main/cnf-certification-test/networking/suite.go#L52), I find this helpful to figure out which suite is running.

Add 'entering suite' logging strings to match other suites

---

cnf-certification-test/lifecycle/suite.go
cnf-certification-test/tnf_config.yml
pkg/configuration/configuration.go
pkg/configuration/testdata/tnf_test_config.yml

Add tnf_config entry for the ability to exclude certain deployments and/or statefulsets from the scaling tests.

Add ability to skip scaling tests via config

---

pkg/compatibility/compatibility.go

build-depends: 26624
build-depends: https://github.com/dci-labs/dallas-pipelines/pull/570
I was looking at the doc page: https://access.redhat.com/support/policy/updates/openshift
And the 4.7 release was moved to the end of life section.

Move 4.7 to 'end of life' section

---

cnf-certification-test/suite_test.go
internal/clientsholder/clientsholder.go

build-depends: 26624
build-depends: https://github.com/dci-labs/dallas-pipelines/pull/570
Serialize the merged kube config into a temporary file and save the file path so it can be read on demand.
This could be used by Brandon's wip #631 for the preflight lib integration.

Created merged kube config file in the clientsholder.

---

.github/workflows/pre-main.yaml

#204 missed this.
This is the error that is popping up in our CI runs:
```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2
```

Update checkout to v3; missed in previous updates

---

pkg/testhelper/testhelper_test.go

build-depends: 26624
build-depends: https://github.com/dci-labs/dallas-pipelines/pull/570
Brings the `testhelper` package up to `96.4% of statements`.

Add tests for testhelper pkg

---

cnf-certification-test/accesscontrol/suite.go
pkg/provider/filters.go
pkg/provider/pods.go

Adding a null check and now only check for SYS_PTRACE in capabilities.add (instead of add/drop)
Also skipping the test for pods that do not have shareProcessNamespace: true
Please review only this commit:
https://github.com/test-network-function/cnf-certification-test/pull/661/commits/d9546db979677ed450814cab82fed279a1ad8cd2
Partner repo PR:
https://github.com/test-network-function/cnf-certification-test-partner/pull/187

Fix for SYS_PTRACE panic and logic

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go

The TC removed is a duplication of lifecycle-deployment-scaling. 
There are only 2 scaling TCS: 
1. statefulset.
2. deployment.

Removed duplication of deployment scaling

---

version.json

https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.1.1
In preparation for release v4.1.1 of the test suite, we need to bump the partner release as well.

Bump partner to v4.1.1

---

cnf-certification-test/platform/bootparams/bootparams.go

Just a few minor typos in the `bootparams` package.

Fix minor typos in bootparams

---

cnf-certification-test/lifecycle/suite.go

Simple fix to use the right output variable to hold the bad statefulsets in the lifecycle-high-availability test case.

Use the right variable for bad statefulsets.

---

cnf-certification-test/networking/netcommons/netcommons.go
cnf-certification-test/networking/suite.go
pkg/provider/pods.go

Fix a couple of `networking` suite tests that still fail due to istio-proxy being injected into pods.
Created a method in the `Pod` struct called `ContainsIstioProxy` which just allows us whether or not a pod has an injected `istio-proxy` container.  The "[]Pod.Containers" are not filtered the way the "env.Containers" slices are filtered, see #554.
Notes:
- GetReservedIstioPorts() returns a hardcoded slice of ports and commented details about what they are used for.

Fix networking tests that fail with istio-proxy related issues

---

cnf-certification-test/accesscontrol/namespace/namespace.go
cnf-certification-test/chaostesting/pod_delete/pod_delete.go

We use `context.TODO()` instead of `context.Background()` everywhere else in the code.  They do the exact same thing but I want to be consistent.

Switch context.Background() to context.TODO() for consistency

---

cmd/tnf/main.go
cnf-certification-test/accesscontrol/rbac/automount.go
cnf-certification-test/accesscontrol/rbac/clusterrolebinding.go
cnf-certification-test/accesscontrol/rbac/rolebinding.go
cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/chaostesting/pod_delete/pod_delete.go
cnf-certification-test/lifecycle/podsets/podsets.go
cnf-certification-test/lifecycle/suite.go
cnf-certification-test/networking/netcommons/netcommons.go
cnf-certification-test/networking/netutil/netutil.go
cnf-certification-test/networking/suite.go
cnf-certification-test/observability/suite.go
cnf-certification-test/platform/suite.go
internal/crclient/crclient.go
pkg/autodiscover/autodiscover.go
pkg/claimhelper/claimhelper.go
pkg/configuration/configuration.go
pkg/diagnostics/diagnostics.go
pkg/diagnostics/diagnostics_test.go
pkg/provider/filters.go
pkg/provider/operators.go
pkg/provider/pods.go

Sometimes we'll see `err: %!s(<nil>)` messages in our logs because the format is incorrect.

Use '%v' when referencing an error

---

cnf-certification-test/lifecycle/suite.go

Include the lifecycle-pod-recreation tc as part of the test cases list that won't run when the TNF_NON_INTRUSIVE_ONLY env var is set to true.
Also, the env.IsIntrusive() check was not working because the "env" variable is not set at that point yet, so all the "intrusive" test cases were being run no matter the value of TNF_NON_INTRUSIVE_ONLY.

Run lifecycle-pod-recreation TC in intrusive mode only.

---

Dockerfile
docs/developers.md
docs/runtime-env.md
run-cnf-suites.sh

Use ubi-minimal as base image and remove some unneeded elements.
Image size reduced to 232MB from almost 1GB.

Optimize and clean the TNF image

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/identifiers/remediation.go

Moving the following TCs from informativre to normative:
- container-host-port
- namespace-resource-quota

upgrading some test cases to normative

---

cnf-certification-test/lifecycle/suite.go

Change the timeout value to 5 minutes for the scaling tests to accommodate slower clusters.

Bump timeout to 5 minutes for scaling tests

---

cnf-certification-test/platform/suite.go
pkg/provider/containers.go
pkg/provider/containers_test.go
pkg/provider/pods_test.go

Instead of hardcoding the `istioContainerName` variable in the suite.go, I made it a `Container` object func that provides whether or not the container is istio-proxy or not.
Also added some more tests to the `Pod` func that does similar things.
Builds upon: https://github.com/test-network-function/cnf-certification-test/pull/673/

Add IstioProxy check func; extra tests

---

pkg/provider/provider.go

The DeploymentConfig trace was shown for all non-DeploymentConfig resources by mistake.

Fixed warning trace for DeploymentConfig resources.

---

CATALOG.md
cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/lifecycle/suite.go
cnf-certification-test/lifecycle/suite_test.go
cnf-certification-test/lifecycle/tolerations/tolerations.go
cnf-certification-test/lifecycle/tolerations/tolerations_test.go

- Switched existing "toleration" test from access-control to lifecycle suite and changed it to a NormativeResult instead of InformativeResult.
- Added test case to existing `TestIsTolerationModified` func for a custom key.
- BONUS: Added two more unit tests in `cnf-certification-test/lifecycle/suite_test.go`.

Add shortcircuit to existing toleration test

---

cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/identifiers/identifiers.go

Remove the original test `TestSecConCapabilities` which tested all of the security context capabilities at once, and split them into individual tests.

Split capabilities test up into separate tests

---

.github/workflows/pre-main.yaml
.github/workflows/tnf-image.yaml
Dockerfile
Makefile
docs/test-container.md
script/get-release-level.sh

- Changed the github workflows to run `make build-image-local` instead of copy/pasting the docker build command information.
- Removed the logic from the Dockerfile that clones the repo(not sure why we ever did this) and builds the binary to just use the already built binary as part of `make build-cnf-tests` which is ran in `make build-image-local` as a pre-req.
- Added default values/strings in the Makefile.
- Removed `jq` and `git` dependencies from the first stage of the Dockerfile.
- BONUS: Added `operator-sdk` binary to the image PATH to be able to use in the preflight work in #631.

Adjust Dockerfile to be able to built locally

---

docs/test-container.md
version.json

Related to: https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.1.3

Prepare for v4.1.3 release

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go

Added two new tags `telco` and `faredge`, and based off of the spreadsheet where we determined which tests are considered to be tagged specifically.

Add additional labels to existing tests

---

.github/workflows/tnf-image.yaml

The environment variable `TNF_IMAGE_TAG` seems to not be getting set after my #744 change.  This should set it in the environment.

Ensure 'latest' image tag is built in CI

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go

#750 accidentally classified these tests under `lifecycle` instead of their original designation of `access-control`.

Fix the the capabilities tests suite classification

---

cnf-certification-test/lifecycle/suite.go
run-cnf-suites.sh

Backporting #528 and #719 back to the `4.0.x` branch for potential `v4.0.3` release.

Timeout backport

---

.github/workflows/tnf-image-legacy.yaml

Supports building the 4.0.x branch whenever a new release is published.
Notable differences compared to the tnf-image.yaml:
- Only triggers on 4.0.x branch (currently).
- Does some bash string manipulation to strip off the `.x` from the `4.0.x` to find the latest tag available in the repo.

Add legacy branch builder YAML

---

cnf-certification-test/suite_test.go
internal/clientsholder/clientsholder.go

Based on changes from #631 
Adds a `clientsHolder.KubeConfig` byte array variable.
I'm trying to make the preflight lib PR less daunting before the final merge.

Build KubeConfig byte array

---

.github/workflows/tnf-image.yaml

- Remove the "testing" sections of the image building scripts.  The code should already be tested prior to merging as part of the PR running the same tests.
- Fix the [set-output](https://dev.to/cicirello/how-to-patch-the-deprecated-set-output-in-github-workflows-and-in-container-actions-9co#:~:text=GitHub%20recently%20deprecated%20the%20set,the%20end%20of%20May%202023.) lines that are deprecated.
- Fix the `docker push` section of the 4.0.x job to only push the TNF_VERSION, not the `latest`.

Improve tnf-image.yaml; fix deprecations

---

.github/workflows/pre-main.yaml
Makefile

Follow up to: https://github.com/test-network-function/cnf-certification-test/pull/775
Changes the github workflow to call `make install-tools` to remove the multiple entry changes for this type of change in the future.

Manual update ginkgo to v2.7.0

---

docs/configuration.md
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_services.go
pkg/configuration/configuration.go
pkg/configuration/testdata/tnf_test_config.yml

This is to skip testing the hazelcast 5.6.0 services which are not compliant with the dual stack / ipv6 test.
related to https://github.com/test-network-function/cnf-certification-test-partner/pull/204
upgrading hazelcast to 5.6.0 is needed to pass Redhat Certification test. this PR will allow passing the ipv6/dual stack test

Adding an ignore list for services under test

---

.github/workflows/pre-main.yaml
.gitignore
docs/index.md
docs/test-container.md
docs/test-output.md
run-cnf-suites.sh

This is related to https://github.com/test-network-function/cnf-certification-test/pull/777
This is proposing to use tee to mirror the output and captures all the logs(including those added by Ginkgo) in the cli and container scenarios

Create log file by mirroring output in bash script

---

cnf-certification-test/lifecycle/suite.go
pkg/provider/isolation.go
pkg/provider/isolation_test.go
pkg/provider/pods.go
pkg/provider/pods_test.go

Related to: https://github.com/test-network-function/cnf-certification-test/issues/762
The pod-recreation test case falls over because _sometimes_ there can be nodeSelectors attached to pods.  This is not allowed, per best practice requirement guidelines but that doesn't stop the test from attempting to run.  The test is now modified to check for these nodeSelectors prior to entering the loop that does the `cordon`.
- Added `pod.HasNodeSelector()` func and appropriate changes.
- Added logic into the `pod-recreation` test to utilize the above `HasNodeSelector` func and detect any possible failures this test could encounter early.
- Changed `IsRuntimeClassNameSpecified` into a `Pod` struct func because it is used outside of the `isolation` file.

Add check for nodeSelectors in pod-recreation test

---

cnf-certification-test/platform/nodetainted/nodetainted.go
cnf-certification-test/platform/nodetainted/nodetainted_test.go
cnf-certification-test/platform/suite.go

This is a proposal to make the whitelist for kernel taints more flexible.
The whitelist in the previous implementation was for taints related to out-of-tree modules. This commit tries to make the whitelist to work for any bit, including the RedHat's ones.
First, I get the list of modules that have any taint letter, reading the /sys/module/module_name/taint files. When the module is responsible for a taint bit, that module will have a string letters associated to the taints. If any of those modules doesn't appear in the whitelist, the test fails.
Finally, we need to make sure there are no other taint bits active, because some of them can be active for other reasons not related to kernel modules (e.g. bit 11).
Also, updated description for taint bit 31.

Refactor for the kernel taints test case

---

docs/test-container.md
version.json

https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.1.5
Preparing for patch release `v4.1.5`.

Update partner version to v4.1.5

---

.github/workflows/pre-main.yaml
.github/workflows/tnf-image.yaml
run-tnf-container.sh
script/run-container.sh

Broken out from #631 
Using the `PFLT_DOCKERCONFIG` variable from preflight (found [here](https://github.com/redhat-openshift-ecosystem/openshift-preflight/blob/main/docs/CONFIG.md)) as a prerequisite for running the preflight library.
This change is in the PR #631 but I wanted to make it a separate change for reviewing sake.
If merged, nothing functionally changes it just has a new env variable available in the container.
build-depends: 27115

Modify scripts to mount docker config

---

.github/workflows/pre-main.yaml

`RELEASE_LEVEL` is unused the pre-main.yaml and can be removed.  It is however still used in the tnf-image.yaml because the 4.0.x (legacy) release support still uses it.

Remove unused var

---

cnf-certification-test/accesscontrol/resources/resources.go
cnf-certification-test/lifecycle/suite.go
pkg/provider/events_test.go
pkg/provider/filters.go
pkg/provider/filters_test.go
pkg/provider/isolation.go

Changed the references from `.Value()` to `IsZero()` in the requests/limits checks.
Adds some new unit tests in:
- pkg/provider/events_test.go
- pkg/provider/filters_test.go
Previously, there was no unit test coverage in either of these files.

Add more unit test coverage

---

pkg/provider/provider.go

Just a quick debug line for seeing how long it takes to build the `testEnvironment` object.

Add elapsed time for building test environment

---

CATALOG.md

The CATALOG needed to be regenerated to bring in changes for the `exclusive-cpu-pool-rt-scheduling-policy` entry.

Manually fix the catalog

---

Makefile

Instead of having to manually bump the `install-tools` path in the Makefile every time Ginkgo updates, this should dynamically grab the line that installs whatever is in the go.mod.

Dynamically install ginkgo based on go.mod in 'install-tools'

---

cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/platform/suite.go
pkg/provider/provider.go
pkg/scheduling/scheduling_test.go

Changes:
- In `TestPodRoleBindings` and `TestPodClusterRoleBindings`, instead of skipping the entire test because a Pod is missing a `serviceAccountName`, just continue and move on.
- Adjust when `ginkgo.Skip` is called when an OCP cluster is detected

Adjust ginkgo.Skip calls

---

script/run-container.sh

If `CONTAINER_TNF_DOCKERCFG` is unset after the discovery phase, just use a default string of `NA`.
#631 will require an actual docker config being created/supplied but as of right now it isn't merged yet.
Related to: #804

Safeguard against empty variable

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/identifiers/remediation.go
cnf-certification-test/networking/suite.go
go.mod
go.sum
internal/clientsholder/clientsholder.go
pkg/provider/filters.go
pkg/provider/pods.go
pkg/provider/pods_test.go

Added pod method to return whether a pod is using any sriov interface or not. Reads CNCF's networks annotation on each pod and check if any of the CNIs of that network is sriov type.

Far Edge TC: check restart-on-reboot label for sriov pods.

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/lifecycle/suite.go
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_pv.go
pkg/provider/provider.go
pkg/scheduling/scheduling_test.go

build-depends: https://github.com/dci-labs/dallas-pipelines/pull/646
VCP CNF Requirement: PODs must NOT place persistent volumes on local storage.
We following pod by pod and check:
1) if PVC is not exist : we don't have what to check and we finished the test.
2) if name of PVC is equal to PVC of the pod:
-we check if provisioner of StorageClasees equal to"kubernetes.io/no-provisioner":
if yes, we found pod that use a local storage enabled storageClass and we add to list of pods that have local storage("podWithLocalStorage")
we check all volumes in all pods under test to see if they are used. If a pod is using a volume that is using a local StorageClass, we should fail the test.
The purpose is to find pods that have PVC&&PV and to use a local storage enabled StorageClasses.

VCP CNF Requirement: PODs must NOT place persistent volumes on local storage

---

cnf-certification-test/lifecycle/podsets/podsets.go

Waiting for a Deployment to be ready should not be logged with error level.

Change log level from error to info when a deployment is not ready yet

---

pkg/scheduling/scheduling.go
pkg/scheduling/scheduling_test.go

Follow up to #803 
Adds a quick test for `PolicyIsRT()`.
Bonus: Adds some copyright blocks.

Add unit test for 'scheduling' package

---

go.mod
go.sum
internal/certdb/onlinecheck/onlinecheck.go

Updating our YAML package to v3.0.1.
https://github.com/go-yaml/yaml/releases/tag/v3.0.1
Interestingly enough, the go.mod was already in #256 but the line still remained:
`github.com/go-yaml/yaml v2.1.0+incompatible`

Update YAML to v3 for vulnerability

---

pkg/compatibility/compatibility.go

Following documentation updates [here](https://access.redhat.com/support/policy/updates/openshift).
Adds 4.12 to the `Full Support` section.
Moves 4.10 to the `Maintenance Support` section.

Add 4.12 to the compatibility matrix

---

cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/identifiers/identifiers_test.go

Follow up to #843 
`GetGinkgoTestIDAndLabels` was broken in #843 and needed to properly set the testID into the results map.

Fix the testID in the results output

---

cnf-certification-test/platform/suite.go
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_operators.go
pkg/provider/provider.go

Besides verifying that the Istio namespace exists, the presence of the Istio CR related to the installation is also taken into account when deciding if the Istio Service Mesh is active in the cluster.

Improve the Istio Service Mesh detection

---

.github/workflows/pre-main.yaml
.github/workflows/tnf-image.yaml
.github/workflows/update-rhcos-mapping.yml

The Ubuntu 22.04 runner was in beta the last time we tried it in #218.
This is out of beta now and I'm curious to see if the errors we had before happened.

Bump Ubuntu runners to 22.04

---

cnf-certification-test/preflight/suite.go
pkg/configuration/configuration.go
pkg/provider/containers.go
pkg/provider/operators.go
run-tnf-container.sh

- Moved the check for the Docker Config file into the suite.go.
- Removed the `LOCAL_DOCKERCFG` as a required parameter to the script.
- Removed `required:"true"` from the envconfig variable for the docker config.

Make docker config optional

---

.github/workflows/codeql-analysis.yml

All trigger modes have been disabled. Only manual triggering is allowed until this workflow works again.

Added manual trigger for CodeQL workflow.

---

pkg/autodiscover/autodiscover_operators_test.go

Currently, there is only: `coverage: 17.2% of statements` in the `autodiscover` package.  We should probably strive to add more unit testing surrounding these vital pieces of code.
Simple test for `GetAllNamespaces()` func.  I decided not to attempt more until #868 merges to avoid merge conflicts.

Add tests for autodiscover operators

---

cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/networking/suite.go

- For the "one process per container" test case the verification for the Istio containers is skipped, as they contain two processes. Although it still applies to the application containers.
- The "nftables" test case is skipped due to the networking rules that Istio injects in the application containers.

Skip some test cases that are incompatible with the Istio Service Mesh

---

docs/test-container.md
version.json

Preparing for the v4.1.6 release of the test suite.
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.1.6

Update -partner reference to v4.1.6

---

.github/workflows/pre-main.yaml

Speed up the PR checks by splitting up the local/binary tests from the container based tests.  This will run in parallel and make the time to check each PR faster.
For reviewers:
- Turned `smoke-tests` section into `smoke-tests-local` and `smoke-tests-container`.

Split up 'local' and 'container' PR tests

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go

build-depends: https://github.com/dci-labs/dallas-pipelines/pull/672
build-depends: 27665
Updated CATALOG.md file because we have duplicate entry for TestStorageRequiredPods.

Updated CATALOG.md file

---

cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/performance/suite.go
internal/crclient/crclient.go
pkg/scheduling/scheduling.go
pkg/scheduling/scheduling_test.go
pkg/testhelper/testhelper.go

This is a proof of concept to add a more meaningful "Failure Reason" to the claim.json results section. 
Example FailureReason field output format. 
When the test succeeds, the reason is at the end of the test log. This is because there is no function equivalent to gingko.Fail for passing test with a reason.
Also using regex to parse the ps command output to retrieve also the command args (to add more context to this particular reason ).
This is just for illustration, in the successful case
```
{
"CompliantObjectsOut": [
{
"ObjectType": "ContainerProcess",
"ObjectFields": {
"ContainerName": "task-pv-container",
"Namespace": "tnf",
"PodName": "task-pv-pod",
"ProcessCommandLine": "sleep 30",
"ReasonForCompliance": "process satisfies: SHARED_CPU_SCHEDULING: scheduling priority == 0", …
```

POC: Add Failure Reason to claim.json

---

.github/workflows/codeql-analysis.yml

The last run:
https://github.com/test-network-function/cnf-certification-test/actions/runs/4351853705/jobs/7603935304
Failed with:
```
/bin/sh: 1: ginkgo: not found
make[1]: *** [Makefile:108: build-cnf-tests] Error 127
make: *** [Makefile:60: build] Error 2
```

Re-enable CodeQL with 'make install-tools' in the steps

---

.github/workflows/tnf-image.yaml

On the `daily` cron builds, the `github.event.release.tag_name` is not populated and we end up with an error.  Using the `env.TNF_VERSION` gets the correct latest release variable every time.

Fix daily builds

---

Makefile

Building the binary to run locally should include the tools needed to run the binary immediately after.  Quality of life improvement.

Run 'make install-tools' prior to building binaries

---

cnf-certification-test/networking/suite.go

The output from a recent DCI job provides output about which ping tests fail, but the summary doesn't show up.  This will give a better experience for people looking at the results.

Add AddTestResultLog result to network connectivity test

---

cnf-certification-test/platform/suite.go

This minor check was missed in https://github.com/test-network-function/cnf-certification-test/pull/928, OCP 4.13 job was failing in fact: https://www.distributed-ci.io/jobs/f0f8d733-30d5-4994-9fb9-6006c28e210e/tests

Admit that a control plane node can use CentOS Stream starting in OCP 4.13

---

cnf-certification-test/platform/suite.go

This minor check was missed in https://github.com/test-network-function/cnf-certification-test/pull/928, OCP 4.13 job was failing in fact: https://www.distributed-ci.io/jobs/f0f8d733-30d5-4994-9fb9-6006c28e210e/tests
https://github.com/test-network-function/cnf-certification-test/pull/932 was created to fix that but condition was wrong. This should fix everything.

Admit that a control plane node can use CentOS Stream starting in OCP 4.13 (II)

---

.github/workflows/pre-main.yaml
Makefile
run-tnf-container.sh
script/run-container.sh

The discovery of the LOCAL_DOCKERCFG variable needs a default option (NA).  If the `PFLT_DOCKERCONFIG` variable does not get set, and the `$HOME/.docker/config.json` does not exist, then the variables get set to `NA`.
Prior to this, we were seeing:
```
Mounting 1 kubeconfig volume(s):
-v /opt/ocp/r207-compact/kubeconfig:/usr/tnf/kubeconfig/config:Z
Mounting 1 dockercfg volume(s):
-v 
```
And the `-v` docker run flag was not populated causing an error: `Error: invalid reference format`.

Add default NA case for docker config discovery

---

cnf-certification-test/preflight/suite.go
cnf-certification-test/preflight/suite_test.go

Since the `preflight` tests are marked as `TagCommon` and are living under the `preflight` test suite, any labeling that occurs that includes those two strings allows the preflight tests to run prior to the `It` blocks being created.
If there is a label set such as `platform-alteration-isredhat-release` (like in QE), we gracefully return our way out of the function so as to not run the preflight tests if we don't need them.

Safeguard against preflight tests running if not specified

---

cnf-certification-test/preflight/suite.go
pkg/provider/containers.go
pkg/provider/operators.go

There has been some recent DCI runs where it seems like an empty slice of InstallPlans is throwing an error.  We should probably have a safeguard against this sort of scenario.

Add some more logging; safeguard against empty InstallPlans

---

.github/actions/setup/action.yml
.github/workflows/self-hosted.yml
.github/workflows/tnf-image.yaml

Adds a new YAML for the new self-hosted runner.  Currently this is still running the same tests we use in the github hosted runners but I hope to expand on the strategy in the future and maybe use the self-hosted runner to run our QE tests.

Add new self-hosted PR tester YAML

---

go.mod
go.sum

Using a `replace` directive to lock in the version of -preflight we are using.  For some reason in #956 the automation is deleting our reference to preflight?  Not sure.

Lock the preflight version with replace; update ginkgo

---

cnf-certification-test/lifecycle/podrecreation/podrecreation.go
cnf-certification-test/platform/suite.go

Make sure the debug pod is available for the node under test.
+ Added info trace for cordon/uncordon operations.

hugepages tc: avoid panic if debug pod doesn't exist for node under test

---

docs/configuration.md
pkg/autodiscover/autodiscover.go
pkg/autodiscover/constants.go
pkg/configuration/configuration.go
pkg/configuration/utils.go
pkg/provider/provider.go

The namespace for the debug daemonset is now configurable via yaml file. In case the field is not set, the namespace "cnf-suite" will be used.
Example:
debugDaemonSetNamespace: cnf-cert
+ Minor refactors.

Make the namespace for the debug daemonset configurable.

---

pkg/provider/containers.go
pkg/provider/containers_test.go

`HasIgnoredContainerName` func was missing unit tests.  This file has everything covered by the `SetPreflightResults` func now.

Add more coverage for containers.go

---

pkg/autodiscover/autodiscover.go
pkg/provider/provider.go

My PR #967 (sha e7c7753), broke (at least) the test case affiliated-certification-container-is-certified because the config struct was not copied into the env.Config field.
Any other test case that needed to check the config in run-time, e.g. to consult whitelists, were also affected.

Bug fix: config struct was not copied into global env.

---

pkg/provider/statefulsets_test.go

Using the [fake](https://pkg.go.dev/k8s.io/client-go/kubernetes/fake) package to spoof some APIs.
This brings the overall `provider` package to:
`ok  	github.com/test-network-function/cnf-certification-test/pkg/provider	0.733s	coverage: 52.3% of statements`
`GetUpdatedStatefulset` was uncovered as far as unit testing.  Other funcs will be covered in separate PRs to keep changes separate.

Add test with fake statefulset APIs

---

pkg/compatibility/compatibility.go
pkg/compatibility/compatibility_test.go

Resolves #980 
Adds a variable called `ocpBetaVersions` which is just a slice of "major.minor" versions.
Adds a short-circuit func called `BetaRHCOSVersionsFoundToMatch` which will short circuit the `IsRHCOSCompatible` function if we have some beta versions running.

Handle beta OCP versions

---

.github/workflows/pre-main.yaml
Makefile

- Changed `make install-lint` to use `go install` instead of curling the binary.
- Added additional `Install hadolint` step in pre-main.yaml that uses brew for macOS installs.
- Adds `macos-latest` to matrix for running tests.
Since we are running these scripts locally as well as in CI, they might as well pass both places.

Add MacOS to CI matrix

---

.github/workflows/update-rhcos-mapping.yml

Follow up to discussion in #982 
If `make test` fails, the PR with the RHCOS map update won't be created.

Run unit tests on RHCOS map update

---

cnf-certification-test/lifecycle/scaling/deployment_scaling.go
cnf-certification-test/lifecycle/scaling/deployment_scaling_test.go
internal/clientsholder/clientsholder.go

Added tests for:
- ScaleDeploymentHelper
- ScaleHpaDeploymentHelper
Adds a helper function `SetTestK8sClientsHolder` that lets us override the `k8sclient` with a spoofed fake client.

Add unit tests for scaling package

---

.github/workflows/update-rhcos-mapping.yml

Follow up to: https://github.com/test-network-function/cnf-certification-test/pull/984
We need `Go` before we can run `make test`.

Install Go before make test

---

cnf-certification-test/preflight/suite.go

#831 added this safeguard but the check for the empty string needs to also include the value "NA".  This check was added in #861.
Should be an easy fix and we can release 4.2.2 to pick it up.
For example, here are the ENV vars from a 4.2.1 run:
```
"Environment: {Home:/root Kubeconfig:/usr/tnf/kubeconfig/config ConfigurationPath:/usr/tnf/config/tnf_config.yml NonIntrusiveOnly:true LogLevel:trace OfflineDB:/usr/offline-db AllowPreflightInsecure:false PfltDockerconfig:NA}"
```

Safeguard against NA docker config

---

.github/workflows/self-hosted.yml

Since we only have one `self-hosted` runner instance, combining the local binary and container tests makes sense to shorten times.
Also, I have removed the need to run this when commits are pushed to the `main` branch after merging.  Not necessary and overloads the runner.

Combine container and local self-hosted tests

---

docs/test-container.md
version.json

https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.2.2
(We forgot to update this for 4.2.1). 😅

Prepare for version 4.2.2

---

cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/preflight/suite.go

Switch the `preflight` suite tests to be labeled `TagPreflight` instead of `TagCommon`.  This makes the caller have to explicitly include that label to be able to run them.
Message in the logs:
`WARNING[Apr 10 09:12:00.854][suite.go: 50] LabelFilter is set but 'preflight' tests are not targeted. Skipping the preflight tests. `

Add tag 'preflight' to make tests explicit

---

CATALOG.md
cmd/tnf/generate/catalog/INTRO.md
cmd/tnf/generate/catalog/TEST_CASE_CATALOG.md
cmd/tnf/generate/catalog/catalog.go
cmd/tnf/generate/catalog/catalog_test.go

Adding a summary section in the catalog.md to list test cases counts. Also improved the intro a bit and removed static catalog starter files.

Adding summary to catalog.md

---

.github/workflows/pre-main.yaml

We use the brew install for `hadolint` as well.  Figured we would let this perform the install for us.
https://formulae.brew.sh/formula/checkmake

Switch checkmake (macos) to brew

---

cnf-certification-test/lifecycle/podsets/podsets.go
pkg/autodiscover/autodiscover_scaleObject.go

Switched from %e (scientific notation) to default format %v.

Fix error traces in scale objects autodiscover.

---

Makefile
cmd/tnf/generate/qe_coverage/qe_coverage.go
cmd/tnf/generate/qe_coverage/qe_coverage_test.go
cmd/tnf/main.go

Parses the (bool) qe flag from each catalog test case identifier and computes the total and per test suite coverage percentages.

Added qe-coverage-report subcommand to tnf tool.

---

cnf-certification-test/tnf_config.yml
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_operators.go
pkg/autodiscover/autodiscover_pods.go
pkg/autodiscover/autodiscover_pods_test.go
pkg/autodiscover/autodiscover_podset.go
pkg/autodiscover/autodiscover_podset_test.go
pkg/configuration/config_test.go
pkg/configuration/configuration.go
pkg/configuration/testdata/tnf_test_config.yml
pkg/configuration/utils.go
pkg/configuration/utils_test.go

The deprecated label used for operator will be match with any value. The previous PR introducing new labelling procedure broke this wildcard mechanism. This PR adds it back.
fix regression with last PR introducing new labels:
- using a list of strings instead of Map to store labels
- use the correct label for statefulset and deployments under test

Fix for backward compatible label support

---

.github/workflows/pre-main.yaml
.github/workflows/self-hosted.yml

Speed up the CI by not running the unit tests as part of `make build`.  Those are already ran in other `jobs` in the CI already and do not need to be repeated.
`make build` currently runs the unit tests first, then builds.

Only build during smoke tests, do not run unit tests

---

.github/workflows/pre-main.yaml

Adds calls to the `preflight` suite in the container-based and non-container-based smoke tests.
Just to note, the `preflight` suite of tests was removed from common in https://github.com/test-network-function/cnf-certification-test/pull/1004

Add 'preflight' specific calls to CI

---

Dockerfile

The image building started failing after the recently updated git version (#1091) was updated again this weekend... See job:
https://github.com/test-network-function/cnf-certification-test/actions/runs/5043287587/jobs/9044891444

Update git version for docker image build to 2.39.3

---

.github/actions/documentation/Dockerfile
Dockerfile-documentation

The link allows `Dependabot` to monitor the `Dockefile` inside a dot directory. There is an unfortunate downside. The PR created by `Dependabot` will replace the link with the actual file with a new version. We should not merge this PR (produced by `Dependabot`), but bump versions in the `Dockefile` manually.
UPDATE: The better solution is to move the `Dockerfile` to root with another name `Dockerfile-documentation` and create `Dockerfile` link to it.

Add a link to Dockerfile for dependabot monitoring

---

Dockerfile
Dockerfile-documentation

Pinning the package versions does not work if the upstream repo removes the packages.  The base image _knows_ which recommended binaries to install so we do not need to lock them in.

Remove pinned versions; add hadolint ignore

---

.github/workflows/self-hosted.yml

This only applies to the self-hosted runner setup.

Prune the self-hosted runner prior to building cluster

---

.github/workflows/pre-main.yaml
.github/workflows/self-hosted.yml

As per the test in the PR #1134, all the test cases can run in all the current github runners except these two:
- affiliated-certification-container-is-certified-digest: our test-parner resources aren't certified, so this will never pass.
- access-control-security-context: currently failing, although it's worth to investigate why our test workloads are not in category SC1.
This PR https://github.com/test-network-function/crd-operator-scaling/pull/46 must have been merged first, as it will fix another test case.

Github workflows updated to run all tests cases except two.

---

pkg/compatibility/compatibility.go

https://access.redhat.com/support/policy/updates/openshift
New updates to the page with lifecycle dates for 4.13.
4.12 is moved to maintenance support phase.

Update compability pkg with 4.13 info

---

cnf-certification-test/networking/policies/policies.go
cnf-certification-test/networking/policies/policies_test.go

Currently, the networking-network-policy-deny-all test case expects network policies to not have an empty pod selector, and fails to detect default deny-all policies like the one described in [1].
This commit changes that behavior, and modifies the pod selector logic, to match the behavior described in the documentation: "An empty podSelector selects all pods in the namespace."
[1] - https://kubernetes.io/docs/concepts/services-networking/network-policies/#default-deny-all-ingress-traffic

Fix network policy tests with empty podSelector

---

cnf-certification-test/accesscontrol/securitycontextcontainer/securitycontextcontainer.go
cnf-certification-test/accesscontrol/securitycontextcontainer/securitycontextcontainer_test.go
pkg/stringhelper/stringhelper.go
pkg/stringhelper/stringhelper_test.go

- Removed `subslice` and `contains` function and created a `stringhelper.SubSlice` helper function with corresponding unit tests.
- Re-ordered the subslice check to take the `drop` slice first followed by the `required` slice.  Because you want to check your SCCs against the required SCCs.
- Adjust camel case of `PodListcategory` to `PodListCategory`.
- Added a comment about the `NOK` value on the RunAsNonRoot in category 1.

Improve the SCC package

---

.golangci.yml
Makefile
docs/test-standalone.md

https://github.com/golangci/golangci-lint/releases/tag/v1.53.2
I also had to remove `depguard` and `nakeret` from the config as there were new failures.

Update GolangCI to 1.53.2

---

cnf-certification-test/accesscontrol/pidshelper_test.go
cnf-certification-test/networking/icmp/icmp.go
cnf-certification-test/networking/icmp/icmp_test.go
cnf-certification-test/networking/suite.go
pkg/diagnostics/diagnostics_test.go
pkg/scheduling/scheduling_test.go
pkg/testhelper/testhelper.go
script/results-embed.html
script/results.html

This PR adds the following: 
- failure reason for connectivity tests
- better rendering of failure reason fields. Now the fields are ordered by the addition order. A list is used instead of a map to store the order. Fixed html to better scale
- added fast rendering of configuration items. Added a progress bar when loading large set of objects
Note: the format of the failure reason is changed so new claim files would not be able to be parsed with older pages

adding failure reason to icmp connectivity tests

---

CATALOG.md
cnf-certification-test/identifiers/doclinks.go
cnf-certification-test/identifiers/doclinks_test.go
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/identifiers/remediation.go

Created links that point back directly to the [cnf-best-practices](https://github.com/test-network-function/cnf-best-practices) document directly.
There are a few places where I found we don't have a reference in the document that goes to the catalog so I marked them as either `NoDocLinkExtended` or `NoDocLinkFarEdge`.

Add best practice links to catalog

---

cnf-certification-test/identifiers/identifiers.go

Dependant on [this PR](https://github.com/test-network-function/cnfcert-tests-verification/pull/358)

Mark pod-role-binding as QE test implemented

---

cnf-certification-test/results/html/results-embed.html
cnf-certification-test/results/html/results.html
cnf-certification-test/results/results.go
cnf-certification-test/suite_test.go
pkg/testhelper/testhelper.go

build-depends: 28703
This is adding an indication for the reason for skipping a test in the Failure Reason field of the claim file. Also added display of aborted test cases.
HTML page updated to display aborted test cases and skip reason

Adding support for skip reason and HTML rendering

---

docs/test-standalone.md
internal/certdb/config/config.go
internal/certdb/config/config_test.go
internal/certdb/offlinecheck/container.go
internal/certdb/offlinecheck/container_test.go
internal/certdb/onlinecheck/api_test.go
internal/certdb/onlinecheck/onlinecheck.go

build-depends: 28703
The registry.redhat.io is hardcoded internally in Pyxis to registry.access.redhat.com. Rewrites registry when processing requests.
Note: Awaiting clarifications from Pyxis team on the on how to use the docker_image_id and image_id fields to consistently get the image digest value

Fix for hardcoded registry registry.redhat.io

---

CATALOG.md
cnf-certification-test/networking/netcommons/netcommons.go
cnf-certification-test/networking/suite.go
pkg/testhelper/testhelper.go

Added Pod level and Port level reports
This PR is the continuation the closed PR https://github.com/test-network-function/cnf-certification-test/pull/1205

Add failure-reason for ocp/partner -reserved-ports and undeclared port usage

---

cnf-certification-test/networking/netcommons/netcommons_test.go

Adds an expected error test case for the getIPVersion() function.  I noticed we don't test for empty strings.
As a background, there is discussion about whether or not to support headless services when it comes to the best practices.  This test case doesn't handle the "None" string required for headless, but rather an empty string case which _shouldn't_ happen but might as well test for it.
If further changes are needed for supporting headless services, we will add that as well.
https://kubernetes.io/docs/concepts/services-networking/service/#headless-services

Add emptystring test case for getIPVersion()

---

cnf-certification-test/manageability/suite.go
pkg/provider/containers.go
pkg/provider/containers_test.go
pkg/testhelper/testhelper.go

build-depends: 28703
- Add compliant/nonCompliant objects for these two tests.
- Add Container.IsTagEmpty() func with corresponding unit tests.

Add report objects for manageability suite tests

---

cnf-certification-test/identifiers/identifiers.go

Update required for [this PR](https://github.com/test-network-function/cnfcert-tests-verification/pull/352)
QE test coverage : 77%

Mark cluster-role-bindings as QE test covered

---

pkg/provider/containers.go
pkg/provider/operators.go

Similar to #681 
These were some stragglers I found that were using `Background()` instead of `TODO()`.  These are essentially the same function but I like conformity.  😄

Switch context.Background() to TODO() for consistency

---

CATALOG.md
cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/platform/hugepages/hugepages_test.go
cnf-certification-test/platform/nodetainted/nodetainted.go
cnf-certification-test/preflight/suite.go
cnf-certification-test/suite_test.go
internal/certdb/onlinecheck/onlinecheck.go
pkg/testhelper/testhelper.go

Covers all of the tests in the `access-control` test suite with compliant/non-compliant objects.
Bonus contraction removal `doesn't` to `does not` similar to #264

Add access-control failure reason objects

---

cnf-certification-test/certification/suite.go
pkg/testhelper/testhelper.go

Added failure reason objects for:
- `affiliated-certification-helm-version`
- `affiliated-certification-container-is-certified`
- `affiliated-certification-operator-is-certified`
- `affiliated-certification-helmchart-is-certified`
- `affiliated-certification-container-is-certified-digest`
Added two new funcs in the testhelper:
- `NewHelmChartReportObject`
- `NewOperatorReportObject`

Add affiliated-certification failure reason objects

---

.github/workflows/self-hosted.yml

`docker system prune` cleans everything including images.  We're hitting dockerhub rate limits because we are constantly pulling images so I'm going to help it by not pruning images we have already pulled.

Help the self-hosted runner by not pruning images

---

internal/crclient/crclient.go
pkg/scheduling/scheduling.go
pkg/scheduling/scheduling_test.go

Not sure why, but "ps" seems not to be able to handle the URG signal, returning an error status code. As per some comments in github, looks like the golang runtime might have sent the socket related URG signal. See:
https://github.com/golang/go/issues/37942
https://stackoverflow.com/questions/72568024/go-preempt-can-exit-out-of-a-loop
The ps program shows this output:
[command.go: 72] stderr: Signal 23 (URG) caught by ps (3.3.15).
Apparently, ps works well, but it just returns with an error status code due to the received SIGURG.
A retry mechanism doesn't work well here: in my tests, I saw the ps command failing up to 5 times in a row, so I think it's better trapping the signal with the bash built-in command "trap". This is the new command sent to the node's shell to get all the …

Fix for the unstable test cases of the performance test suite.

---

Makefile
docs/test-standalone.md

https://github.com/golangci/golangci-lint/releases/tag/v1.53.3

Update GolangCI-lint to v1.53.3

---

cnf-certification-test/identifiers/identifiers.go

Dependant on https://github.com/test-network-function/cnfcert-tests-verification/pull/371

Mark ssh-daemons as QE test covered

---

Makefile
cnf-certification-test/results/html/results-embed.html
cnf-certification-test/results/html/results.html
cnf-certification-test/suite_test.go
go.mod
script/get-claim-version.sh
version.json

Claim file version added to the version.json file
The new version is integrated as a static variable in the tnf exec and added to the claim file in the versions section. 
The result.html check the claim file version with its own hard coded supported version before rendering any results.
If there is a mismatch, a warning modal is displayed with the option to continue or stop.
needs https://github.com/test-network-function/test-network-function-claim/pull/94 to merge

Check claim file format version before attempting rendering results

---

.github/workflows/pre-main.yaml

The job that runs tnf using the container was failing due to not enough disk space to untar the preflight image.
Debugging through ssh with tmate action showed that used disk space reached 98-99% right before running the preflight test suite.
Deleting the unnamed/dangling container images right after building the tnf docker image frees around 3.5GB of disk space.

Github CI: clean up unnamed/dangling container images to save disk space.

---

docs/test-standalone.md

Related to: https://github.com/test-network-function/cnf-certification-test/pull/1176
We should be recommending users to run `all` suites instead of the `common,extended` labels.

Update instructions for running 'all' suites

---

.github/workflows/pre-main.yaml

The job "Run Local Smoke Tests" is also running out of free disk space, making the check to fail.
This change will clean the oct container image after it's been used and the go mod cache after the cnf cert suite program has been compiled.

Github CI: Remove oct container image and the go mod cache to save disk space.

---

cnf-certification-test/suite_test.go

An ERROR message was appearing at the end when the test suite was launched in diagnostic mode (no labels used), because the archiver package was trying to read a non-existent xml junit file.
```
ERROR  [Jul 25 19:36:43.837][suite_test.go: 226] Failed to compress results artifacts: failed to get file info from cnf-certification-tests_junit.xml: stat cnf-certification-tests_junit.xml: no such file or directory
```
The error itself was not making the program to return any error code, thus it was not detected in github ci.
As that file is never created in diagnostic mode, this change just avoids adding it to the list of files to zip at the end. Also, the program will return with error code if there's some error while creating the results+html zip file.

Avoid zipping junit xml file in diagnostic mode.

---

cnf-certification-test/accesscontrol/suite.go

The error message for `access-control-pod-service-account` is a bit confusing, because it makes you think that you are not using a service account, but it may happen that the pods are attached to the default service account.
As described in the [docs](https://github.com/test-network-function/cnf-certification-test/blob/main/CATALOG.md#access-control-pod-service-account), the service account must be a valid one. So, updating the message consequently to emphasise that
Same for `access-control-pod-role-bindings`; error message said namespace but it should say serviceAccountName

Update the error message in some access-control tests

---

cnf-certification-test/identifiers/identifiers.go

With these, we get 85% of test covered.
Dependant on the merge of https://github.com/test-network-function/cnfcert-tests-verification/pull/396
and https://github.com/test-network-function/cnfcert-tests-verification/pull/385

85% QE coverage : with storage-required-pods + helm-chart-certified

---

.github/workflows/qe.yaml

Adding QE runners into our CI.  Starting with the `lifecycle` suite of tests first.

Add github action for qe-tests

---

pkg/provider/provider.go

~~Adding support for case where the image ID repo/name is different from Image~~
The original issue was cause by shorten names for the image in the spec, for instance using "httpd:2.4.57" instead of "docker.io/library/httpd:2.4.57" in the spec
Using the status instead of the spec value as the status will render the full url. Removed original fix as it requires further investigation wrt which repo/image name to use when imageID and image fields do not match.

Fix for parsing the image ID and image

---

.github/workflows/pre-main.yaml

Similar to how we cleanup the `oct` image.

Remove gradetool image to save space

---

cnf-certification-test/certification/suite.go
cnf-certification-test/certification/suite_test.go
internal/certdb/onlinecheck/onlinecheck.go
internal/certdb/onlinecheck/onlinecheck_test.go
pkg/configuration/config_test.go
pkg/configuration/configuration.go
pkg/configuration/testdata/tnf_test_config.yml
pkg/provider/provider.go
pkg/provider/provider_test.go

Re-add support for short image names such as httpd:2.4.57
revert https://github.com/test-network-function/cnf-certification-test/pull/1305 to use the spec version of the image name as the user entered it
Rename the following:
- ContainerImageIdentifier.Name to ContainerImageIdentifier.Repository -> e.g. "testnetworkfunction/cnf-test-partner"
- ContainerImageIdentifier.Repository to ContainerImageIdentifier.Registry -> e.g. "quay.io"

Fix regression for short image names

---

cnf-certification-test/lifecycle/suite.go

If a node has passed the test properly before another node fails it, the test info won't be dumped as the bool controlling this would be already set to false.

lifecycle: fix bug preventing dumping test info after a failure

---

.github/workflows/qe.yaml

All networking QE tests are [now passing](https://github.com/test-network-function/cnfcert-tests-verification/pull/418) in Kind so they can be enabled for PR testing.  🎉

Enable networking QE PR tests

---

docs/runtime-env.md
docs/test-container.md
pkg/provider/provider.go
pkg/provider/provider_test.go
version.json

Partner release: https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.3.4

Prepare for version v4.3.4

---

.github/workflows/pre-main.yaml

Disabling the "Free Disk space" Github action temporarily until issue is fixed 
https://github.com/jlumbroso/free-disk-space/issues/9
pointing to temp repo implementing: https://github.com/jlumbroso/free-disk-space/pull/11
https://github.com/edcdavid/free-disk-space

Pointing to a temp "Free disk space" github action repo for now 

---

cnf-certification-test/operator/phasecheck/phasecheck.go
cnf-certification-test/operator/phasecheck/phasecheck_test.go
cnf-certification-test/operator/suite.go

The two main modifications are:
* Only wait for an operator to be ready when it's in a state that could potentially lead to a Succeeded state. For instance, it does not make sense to wait when it's in the Failed state.
* Do not log with logrus.Faltalf() the timeout condition, as this causes the CNF Certification Suite to return with an error exit status. It should set the operator as non compliant but continue with the remaining tests.
The combination of these two points cause the CNF Certification Suite to fail and stop executing if an operator never reaches the Succeeded state, when only a test case failure should occur.
The only test case affected is operator-install-status-succeeded.

operator: fix the process to check if an operator is ready

---

cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/operator/phasecheck/phasecheck.go
pkg/tnf/status.go

It avoids the common pattern of calling `tnf.ClaimFilePrint()` followed or preceded by a `logrus` function to print a log with a different level than `TRACE`. It also avoids log duplication when doing this.
The issue is fixed in a couple of places as an example, not with the intent of being exhaustive.

Add tnf.Log() function to allow log level selection

---

cnf-certification-test/performance/suite.go

If debug pods are not available this test would pass when it should fail. Adding an internal error non compliant container object to report the failure.

Add non compliant object for internal error when getting PID namespace

---

cnf-certification-test/platform/nodetainted/nodetainted.go
cnf-certification-test/platform/nodetainted/nodetainted_test.go
cnf-certification-test/platform/suite.go
pkg/testhelper/testhelper.go

Adds message ("Node contains taints not covered by module allowlist") to the scenario where a tainted kernel is detected, and none of the modules in the allowlist are found to be covered.  
Bonus: Also changed references to 'whitelist' to 'allowlist'.

Update message for tainted kernel allowlist being empty

---

.github/workflows/qe.yaml

Builds on the work done in the following PRs:
- https://github.com/test-network-function/cnfcert-tests-verification/pull/459
- https://github.com/test-network-function/cnfcert-tests-verification/pull/456
- https://github.com/test-network-function/cnfcert-tests-verification/pull/455
- https://github.com/test-network-function/cnfcert-tests-verification/pull/446
- https://github.com/test-network-function/cnfcert-tests-verification/pull/445
- https://github.com/test-network-function/cnfcert-tests-verification/pull/444
These three suites now run in parallel mode and cuts the execution time down greatly.  🎉 
For example, the `networking` suite used to run for ~30 minutes and now I have seen it run in 80 seconds.
The QE tests were disabled in #1341 to improve the processing speeds.

Renable QE tests

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go

Related to: https://github.com/test-network-function/cnf-certification-test/issues/1119
We perform a filtering on the pods labeled for test prior to running the rest of the CPU isolation test [here](https://github.com/test-network-function/cnf-certification-test/blob/main/cnf-certification-test/lifecycle/suite.go#L179).  If the pods requests and limits are not identical, they are left out which can cause a "skip" to occur.

Add clarification for cpu-isolation test in catalog

---

cnf-certification-test/tnf_config.yml
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_operators.go
pkg/autodiscover/autodiscover_test.go
pkg/configuration/config_test.go
pkg/configuration/configuration.go
pkg/configuration/testdata/tnf_test_config.yml

Reverts test-network-function/cnf-certification-test#1389
Reverting until entire config change is ready.

Revert "config: use a string slice to hold the target namespaces"

---

cnf-certification-test/platform/bootparams/bootparams.go
cnf-certification-test/platform/suite.go
pkg/testhelper/testhelper.go

`getCurrentKernelCmdlineArgs` was previously using the partner workload containers to issue the command "cat /proc/cmdline" instead of the debug pods.

Use debug pod for getCurrentKernelCmdlineArgs

---

CATALOG.md
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/networking/suite.go

Now indicates that networks should have at least 2 pods configured for the test to run. Also move the networking code so that all test case are collocated

Fix skip message for networking tests

---

cnf-certification-test/tnf_config.yml

The structure of this field was updated on https://github.com/test-network-function/cnf-certification-test/pull/1313, but the tnf_config.yml example was not updated. Doing it here

Update tnf_config.yml file with the correct fields for certifiedcontainerinfo

---

cnf-certification-test/certification/suite.go
pkg/testhelper/testhelper.go

This is a leftover from #1218 where this modifications to this test were missing.
* Created a new func `NewCertifiedContainerReportObject` that will print the details of the certified container object to the user.

Add report objects for testContainerCertificationStatus

---

cmd/tnf/claim/compare/compare.go
cmd/tnf/claim/compare/configurations/configurations.go
cmd/tnf/claim/compare/configurations/configurations_test.go
cmd/tnf/claim/compare/testcases/testcases.go
cmd/tnf/claim/compare/testdata/claim_access_control.json
cmd/tnf/claim/compare/testdata/claim_observability.json
cmd/tnf/claim/compare/testdata/diff1.txt
cmd/tnf/claim/compare/testdata/diff1_reverse.txt
cmd/tnf/claim/compare/testdata/diff2_same_claims.txt
cmd/tnf/pkg/claim/claim.go

The tnf config, in claim.configurations.Config, is compared using the agnostic traversal of the json nodes.
As it doesn't make sense to compare abnormal events, the comparison tool will just show the number of abnormal events in the cluster that appear on each claim file.

Added tnf config and abnormal events count to claim comparison tool.

---

cnf-certification-test/lifecycle/suite.go

Similar to: #1433 
Multiple compliant pod objects listed here when they only need to be listed once.

Fix report objects for toleration bypass test

---

cnf-certification-test/accesscontrol/suite.go

Previously the reason was empty which is confusing to someone reading the output in the HTML parser.

Add 'reason' in report object for nodeport test

---

cnf-certification-test/platform/suite.go

We should only need to list the node once in compliant objects.
Compliant objects are spamming the output in the html parser:

Fix report objects for sysctl config test

---

cnf-certification-test/performance/suite.go

There was a space in the "(X seconds)" string that looked like "( X seconds)" which made it look weird.  Fixing this for the HTML parser output.

Fix spacing in exec probe output

---

cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/certification/suite.go
cnf-certification-test/lifecycle/suite.go
cnf-certification-test/manageability/suite.go
cnf-certification-test/networking/suite.go
cnf-certification-test/observability/suite.go
cnf-certification-test/operator/suite.go
cnf-certification-test/performance/suite.go
cnf-certification-test/platform/suite.go
pkg/testhelper/testhelper.go
pkg/testhelper/testhelper_test.go

Currently only the type of objects responsible for skipping test cases is displayed, add also the name of the object
before we had []*Pods, which becomes []*Pods ( env.GetHugepagesPods() )

Add the name of the object responsible for skipping in addition to type

---

cnf-certification-test/suite_test.go
pkg/configuration/utils.go

Every time the configuration package is imported the init() function, which process the environment variables for the CNF suite, is called. We don't want this to happen when using it for CNF commands, so the logic has been moved elsewhere in the code.

configuration: delete the init function

---

cnf-certification-test/certification/suite.go

This is a regression compared with previous logic. Containers with digest **only** images would not be tested in the container-is-certified test, or in the container-is-certified-digest test. 
For digest images, the repo and name fields are no longer populated since they could be anything, only the digest counts. However, since we skip containers with images that have both empty repository and name we would also skip digest only images. This same check in the container-is-certified-digest test would skip containers that have only a digest defined, only testing the image digest when it was defined using a repository, name and tag. This fix remove the unnecessary check in both container-is-certified and container-is-certified-digest tests.
PR causing regression: …

Fix: run container-is-certified also in the case of digest only images

---

.github/workflows/qe.yaml

We don't need to recreate the Kind clusters on the 24 hour mark.  They are alive and running and only need to be recreated if missing.

Remove 24hr check from QE YAML

---

Dockerfile

In a Docker multi-stage build the value of the environment variables is not preserved between different stages, so if they want to be used they must be redefined. In this case the env var OSDK_BIN was used with an empty value, causing the COPY operation to bring the whole filesystem of the builder image to the final TNF image.
The fix reduces the TNF image size from 787MB to 355MB.

Bug fix: reduce the TNF image size

---

Makefile

I don't believe we need to run the `results-html` make path here when running `make test`.  We do it on other make paths but this one seems unneeded.

Remove 'results-html' from 'make test' path

---

Makefile

Because the `oct` image is tagged as latest, we should always --pull our base images:
https://docs.docker.com/engine/reference/commandline/pull/

Always --pull when building Dockerfile

---

cnf-certification-test/certification/suite.go

This is an unnecessary skip and can be removed.
EDIT: I know we are actively working to remove these test cases but its a good cleanup until they are gone.
cc https://github.com/test-network-function/cnf-certification-test/pull/1455

Remove skips for testContainerCertificationStatus

---

pkg/provider/provider.go
pkg/provider/provider_test.go

This is to support the case when the status.containerStatuses[].name is different from the spec.containers[].name (is it a best practice?). Instead get the imageID from any of the available states.
added a unit test for the getPodContainers function

check for all possible states instead of matching container name with container name in status field

---

cnf-certification-test/certification/suite.go

Adding passing/failing digest in the output of the affiliated-certification-container-is-certified-digest test

adding digest in the failure reason of of the affiliated-certification-container-is-certified-digest test

---

.github/workflows/pre-main.yaml
.github/workflows/qe-hosted.yml

The failure with the `google-cloud-sdk` removal happens during the "large packages" section.  So I commented these out temporarily (to see if it clears it up).

Remove 'large packages' from disk cleanup

---

.github/workflows/pre-main.yaml
.github/workflows/qe-hosted.yml

Follow up to #1478 
Adding `continue-on-error` to allow this to fail and not fail our CI runs.

Continue on error

---

docs/runtime-env.md
docs/test-container.md
pkg/provider/provider.go
pkg/provider/provider_test.go
version.json

https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.5.0
We are going from v4.4.0 to v4.5.0 because of the non-backwards compatible changes to the TNF config.

Prepare for v4.5.0

---

.github/workflows/pre-main.yaml

When a PR is submitted, pre-main.yaml workflow will create the container and push it into quay.io. This change will notify via gchat msg whenever there is an issue with one of the steps that resulted in that new unstable image not being created (hence not pushed) properly.

Send gchat alert message to dev team if unstable image creation failed.

---

.github/workflows/tnf-image.yaml

Same as #1500 but for official releases images.

Send gchat alert message to dev team if release image creation failed.

---

.github/actions/setup/action.yml
.github/workflows/codeql-analysis.yml
.github/workflows/merge.yaml
.github/workflows/pre-main.yaml
.github/workflows/qe-hosted.yml
.github/workflows/update-rhcos-mapping.yml
Dockerfile
go.mod

https://groups.google.com/g/golang-announce/c/XBa1oHDevAo

Update Go to v1.21.2

---

CATALOG.md
cnf-certification-test/identifiers/doclinks.go
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/identifiers/remediation.go
cnf-certification-test/lifecycle/suite.go
pkg/provider/provider.go

Refactored local storage test to support single node clusters. Local storage is not recommended for multinode cluster. Local storage is recommended for single node clusters, but only one local storage provisioner should be used: either lvms or kubernetes' noprovisionner  
Not backward compatible because of renamed test case: 
- renamed lifecycle-storage-required-pods  to lifecycle-storage-provisioner
related to https://github.com/test-network-function/cnf-certification-test-partner/pull/361

check for local storage provisioners for SNO clusters

---

.github/workflows/qe-hosted.yml
.github/workflows/qe.yaml

Not needed as we do not dump the log files anyways.

Disable DEBUG_TNF flag in QE runs

---

cmd/tnf/generate/config/config.go
cmd/tnf/generate/config/const.go

The options allow adding a list of managed Deployments and StatefulSets.
Also, the Collector option has been hidden from the Create menu as this feature is still in development.

config: add two more options to the CNF config generator

---

.github/workflows/qe-hosted.yml
.github/workflows/qe.yaml

Builds upon: https://github.com/test-network-function/cnfcert-tests-verification/pull/541
Basically this allows the QE tests to run the spec twice (as of now) to make sure it isn't just a flake.

Enable flaky retries for QE

---

.github/workflows/pre-main.yaml

Related to: #1540 
This seems to be causing issues.  Commenting out the sanity check until it's fixed.  I also reorganized the calls to the checkout of the collector repo.

Disable collector sanity check temporarily

---

go.mod
go.sum

https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.7.1

Update preflight to v1.7.1

---

.checkmake
.github/workflows/pre-main.yaml
.yamllint.yml
Makefile

Also, updates the GitHub workflow for linters in order to use GitHub Actions when possible and unify all of them in one job.
To install locally the missing linters check [markdownlint](https://github.com/igorshubovych/markdownlint-cli), [typos](https://github.com/crate-ci/typos), [ShellCheck](https://github.com/koalaman/shellcheck#from-your-terminal) and [Yamllint](https://github.com/adrienverge/yamllint).

linters: add some missing linters to the Makefile

---

k8s/README.md
k8s/cnf-certsuite.yaml
k8s/kustomization.yaml

The yaml template and the kustomization file inside the k8s folder allow the deployment of the CNF Cert Suite Pod using:
`oc apply -f k8s/cnf-certsuite.yaml`
or
`oc kustomization k8s | oc apply -f -`
See the README.md file inside the k8s folder for more information and some possible configuration changes.
As this is a developer's "feature", I decided not to include it in the official CNF Cert Suite documentation markdown files.

Added yaml template to deploy the CNF Cert Suite in a kubernetes/Openshift cluster.

---

cnf-certification-test/performance/suite.go
pkg/scheduling/scheduling.go

It applies to `rt-apps-no-exec-probes`.
The reason a process cannot be found after it has been properly retrieved previously could be that the process has finished. So, in this case it seems more adequate to just ignore it than to produce an error. If the error is of another kind, the container is added to the non compliant list but the processing for that container continues instead of breaking, to have more info on the processes.
The commit also changes the verification order in that test case, making the faster check of exec probes at the beginning, skipping the slower part in which the processes are list.
Finally, the compliant containers are added to its list with the reason for compliance.

performance: avoid failing test case if a process cannot be found

---

pkg/compatibility/compatibility.go

https://docs.openshift.com/container-platform/4.14/release_notes/ocp-4-14-release-notes.html
OCP 4.14 is now generally available so the compatibility matrix needs an update to stay current.
See the "Life Cycle Dates" section here: https://access.redhat.com/support/policy/updates/openshift

Add OCP 4.14 to the compatibility matrix

---

docs/runtime-env.md
docs/test-container.md
pkg/provider/provider.go
pkg/provider/provider_test.go
version.json

https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.5.3

Prepare for v4.5.3

---

cnf-certification-test/accesscontrol/suite.go
pkg/testhelper/testhelper.go

Allows a CNF to declare roles across the different namespaces that it uses. Each rolebinding can only allow roles in their own namespace to remote service accounts. This avoids duplicating the same role in multiple namespaces.
See: https://octopus.com/blog/k8s-rbac-roles-and-bindings

Allow Role bindings across namespaces

---

cnf-certification-test/performance/suite.go
internal/crclient/crclient.go

Reverts commit d7dc6cd1d4d482b1b8e39e4c3789429c5785fd9a and adds logic to whitelist processes belonging to the exec probes as described in comment: https://github.com/test-network-function/cnf-certification-test/pull/1564#discussion_r1376928075

Do not consider the exec probes in performance-rt-apps-no-exec-probes

---

.github/workflows/qe-ocp-413-intrusive.yaml
.github/workflows/qe-ocp-413.yaml
.github/workflows/qe-ocp-414-intrusive.yaml
.github/workflows/qe-ocp-414.yaml

We are going to start testing OCP 4.14 QE as part of our nightlies.  Notable changes:
- Changed `qe-ocp.yaml` --> `qe-ocp-413.yaml`.
- Changed `qe-ocp-intrusive.yaml` --> `qe-ocp-413-intrusive.yaml`.
- Added `qe-ocp-414.yaml` --> `qe-ocp-414.yaml`.
- Added `qe-ocp-414-intrusive.yaml` --> `qe-ocp-414-intrusive.yaml`.
With future releases of OCP, we'll test the two releases in General Availability.  The 4.13 runner will be deprecated and 4.15 will be added.

Setup QE OCP 4.14 runner

---

.github/workflows/pre-main.yaml

Only the test cases of the observability test suite have been ported to the new ginkgoless mini-framework (checksdb).
The gradetool's [config](https://github.com/test-network-function/cnf-certification-test/blob/ginkgo_removal/generated_policy.json) file was updated accordingly.

ginkgo_removal branch: enable github checks on new PRs.

---

.github/workflows/qe-ocp-413.yaml
.github/workflows/qe-ocp-414.yaml

Still trying to figure out where some of these parallel failures are coming from.  While I do that, these nightlies can run in sequence.

Temporarily disable QE parallel flag for nightlies

---

cnf-certification-test/manageability/suite.go
generated_policy.json
main.go

Building upon the work done by @greyerof, this PR will transition the `manageability` suite to what we're calling "ginkgoless".

Transition manageability suite to ginkgoless

---

cnf-certification-test/webserver/webserver.go
internal/clientsholder/clientsholder.go
main.go

The kubeconfig sent via web form is now copied to a temporary file.
Also, I created a new function in the clientsholder package to recreate the oc clients for each webserver run, using the kubceonfig file sent via web form.

Fix for the webserver kubeconfig file handling.

---

cnf-certification-test/performance/suite.go
generated_policy.json
main.go
pkg/testhelper/testhelper.go

Also, added a couple of generic helper functions that create skip functions to be used in the check.WithSkipCheckFn() call.
- testhelper.GetNoContainersUnderTestSkipFn(env)
- testhelper.GetNoPodsUnderTestSkipFn(env)
Both return a closure function over the env pointer, and the signature of that function is the expected by the checksdb's runner:
func() (skip bool, string)

Transition performance suite to ginkgoless.

---

.github/workflows/pre-main.yaml
.github/workflows/qe-hosted.yml
.github/workflows/qe-ocp-413-intrusive.yaml
.github/workflows/qe-ocp-413.yaml
.github/workflows/qe-ocp-414-intrusive.yaml
.github/workflows/qe-ocp-414.yaml
.github/workflows/qe.yaml
.github/workflows/tnf-image.yaml

After testing it in a private repo, it works when the webhook URL+query is surrounded by single quotes.

Fix gchat alert message.

---

pkg/provider/isolation.go
pkg/provider/isolation_test.go

The bug happens when deploying pods with containers that don't have any cpu req/limit defined in its spec but they do have any other resource (like mem) set.
cut.Resources.Requests and cut.Resources.Limits are maps, whose keys are the different resources (mem, cpu, hugepages) that were explicitly set in the container spec.
Requests.Cpu() returns a defaulted (zeroed) Quantity for the cpu resource if that resource type doesn't exist in the requests map, which will happen if cpu reqs/limits are not explicitly set in the pod spec.

Fixed function AreCPUResourcesWholeUnits().

---

cnf-certification-test/certification/suite.go
generated_policy.json
main.go
pkg/tnf/status.go

Non-backward compatibility: the tc/check
"affiliated-certification-helm-version" will be skipped if no helm
chart releases were discovered. Also, in case we discovered some chart
releases and helm is v3, every chart release will be added as a compliant
report object.
~PR #1620 needs to be merged first, as this code uses the helper function
"testhelper.GetNoContainersUnderTestSkipFn()" created by that PR.~
Also, added the expansion of the "args..." in the ClaimFilePrintf call
to Logf.

Transition certification suite to ginkgoless.

---

.github/workflows/qe-hosted.yml

Similar to: https://github.com/test-network-function/cnfcert-tests-verification/pull/607
Just as a note, the PR checks for the performance suite will fail due to an error introduced in this PR: https://github.com/test-network-function/cnf-certification-test/pull/1631

Re-enable QE PR checks

---

cnf-certification-test/observability/suite.go
pkg/checksdb/check.go
pkg/checksdb/checksgroup.go
pkg/testhelper/testhelper.go

The `check.WithSkipFn(skipFunc)` has been replaced by a variadic func version to allow more than one skip functions to be called: `check.WithSkipFn(skipFunc1, skipFunc2...)`
By default, the check will be skipped if any skip function returns true when they're called (which happens before running the CheckFn).
If we need to skip the check in case all the skip functions return true, the check.WithSkipModeAll() needs to be used.
Examples:
1. Skip check if no deployments ***or*** no statefulsets were found (`testhelper.SkipIfEmptyAny()`):
```
check := checksdb.NewCheck(id, labels).
WithSkipCheckFn(testhelper.GetNoDeploymentsUnderTestSkipFn(&env), testhelper.GetNoStatefulSetsUnderTestSkipFn(&env)).
WithCheckFn(func() error {
..
})
```
2. We want to skip the check if no deployments ***and*** no …

Allow more than one skip functions per check.

---

cnf-certification-test/certification/suite.go
generated_policy.json
main.go
pkg/tnf/status.go

The content of PR #1622 was accidentally removed from ginkgo_removal branch by commit 1c11b94.

Reapplied PR #1622

---

cnf-certification-test/networking/suite.go
main.go
pkg/testhelper/testhelper.go

Similar to: https://github.com/test-network-function/cnf-certification-test/pull/1614

Transition networking suite to ginkgoless

---

cnf-certification-test/lifecycle/suite.go
main.go
pkg/testhelper/testhelper.go

Similar to: #1616 
The biggest changes here that are out of the ordinary are to the pod-recreation test which was still using direct `ginkgo.Fail` calls.

Transition lifecycle suite to ginkgoless

---

cnf-certification-test/lifecycle/podsets/podsets.go
cnf-certification-test/lifecycle/suite.go
generated_policy.json
pkg/testhelper/testhelper.go

The WithSkipCheckFn works doing OR (default behaviour) or AND operations with **all** the skip functions that have been passed. It's not possible to mix them, so I had to create a helper function to check whether both the env.Deployments and env.StatefulSets slices are empty.
Examples:
```
check1.WithSkipCheckFn(skipFn1, skipFn2)
```
check1 will be skipped if **any** of those skip functions return true (OR op because check.SkipMode=SkipModeAny by default).
```
check2.WithSkipCheckFn(skipFn1, skipFn2).
WithSkipModeAll()
```
check2 will be skipped if **both** skipFn1 and skipFn2 return true (AND op = check.SkipMode=SkipModeAll).
Also:
- Some refactor was done in the lifecycle-pod-recreation check to create deployments and statefulsets compliant/nonCompliant objects lists.
- Added skip …

Lifecycle ts: fix to avoid some checks to be skipped.

---

cnf-certification-test/accesscontrol/suite.go
internal/clientsholder/clientsholder.go
pkg/provider/pods.go
pkg/provider/pods_test.go

Pods' Owner references are traversed using unstructured generic objects until the top owner are reached and then recorded. If the top owner includes a CSV that is "cluster wide", we allow cluster role bindings to be used by the pods. 
A CSV is clusterwide if:
- the IsClusterWide variable in out operator object is set (checks the target namespaces) 
- the CSV installMethods are either multi-namespace or all-namespace

Allow cluster role bindings for pods ultimately owned by a cluster wide operator

---

run-basic-batch-operators-test.sh

Moving improved operator batch script in cnf repo. Added support for html page

Add-batch-cert-script

---

cmd/tnf/claim/compare/compare_test.go
cmd/tnf/claim/compare/testcases/testcases_test.go
cmd/tnf/claim/show/failures/failures_test.go
cmd/tnf/pkg/claim/claim_test.go
go.mod
pkg/junit/convert_test.go
pkg/scheduling/scheduling_test.go

Remove `"gotest.tools/v3/assert"` from the go.mod as we are using `"github.com/stretchr/testify/assert"` everywhere else.
Adjust some expected vs actual parameters.

Remove gotools; adjust expected/actual

---

.github/workflows/pre-main.yaml
cmd/tnf/claim/compare/testcases/testcases.go
cmd/tnf/claim/compare/testcases/testcases_test.go
cmd/tnf/claim/compare/testdata/claim_access_control.json
cmd/tnf/claim/compare/testdata/claim_observability.json
cmd/tnf/claim/show/csv/csv.go
cmd/tnf/claim/show/failures/failures.go
cmd/tnf/claim/show/failures/failures_test.go
cmd/tnf/claim/show/failures/testdata/claim1.json
cmd/tnf/claim/show/failures/testdata/claim2.json
cmd/tnf/pkg/claim/claim.go
cmd/tnf/pkg/claim/claim_test.go
pkg/checksdb/checksdb.go
version.json

Change the `[]claim.Result` to `claim.Result` when it comes to results being recorded in the claim file.
This involved changing all of the `testdata/` folders that contained sample JSON files.

Switch to 1-to-1 TestID to Result struct

---

.github/workflows/pre-main.yaml
.github/workflows/qe-hosted.yml
cmd/tnf/claim/compare/testcases/testcases.go
cmd/tnf/claim/compare/testcases/testcases_test.go
cmd/tnf/claim/compare/testdata/claim_access_control.json
cmd/tnf/claim/compare/testdata/claim_observability.json
cmd/tnf/claim/show/csv/csv.go
cmd/tnf/claim/show/failures/failures.go
cmd/tnf/claim/show/failures/failures_test.go
cmd/tnf/claim/show/failures/testdata/claim1.json
cmd/tnf/claim/show/failures/testdata/claim2.json
cmd/tnf/pkg/claim/claim.go
cmd/tnf/pkg/claim/claim_test.go
cnf-certification-test/results/results.go
version.json

Cherry picked the changes from #1666 which was targeted for the `ginkgo_removal` branch and brought them back to main.  I'm not entirely sure this is needed but none of the changes were specific to `ginkgo_removal` so we could still do with removing the slice of results in main as well.  
Also it would make the transition easier for the parser and the gradetool repos once we merge everything in.
This would bump the `claimFormat` value to v0.2.0 and `parserTag` to v0.2.0.

Cherry pick 1-to-1 result struct change

---

internal/cli/cli.go
main.go
pkg/checksdb/check.go
pkg/checksdb/checksdb.go
pkg/checksdb/checksgroup.go
pkg/configuration/utils.go
pkg/versions/versions.go
run-cnf-suites.sh

There are four sections displayed:
1. Basic information about the CNFCERT version and artifacts 
2. Live results for the tests that are running
3. Table that summarizes the result of each test suite 
4. Log output for those tests that failed

cli: display information about the CNFCERT run

---

cnf-certification-test/lifecycle/podrecreation/podrecreation.go
cnf-certification-test/lifecycle/suite.go
pkg/checksdb/check.go
pkg/checksdb/checksdb.go
pkg/checksdb/checksgroup.go

Created an `abortChan` that the check itself is able to trigger if we need to abort the entire suite.

Remove ginkgo.AbortSuite

---

pkg/checksdb/checksdb.go

This reverts commit e3efa08541d18e5b12fad64f351eac61fc21c94e.

Revert "Only capture ctrl-c while tests are running"

---

pkg/checksdb/checksdb.go

This allows terminating the program when running in webserver mode

Only capture ctrl-c while tests are running

---

cnf-certification-test/accesscontrol/suite.go

The actual test is looping through `env.Services`.  Currently in `main` we also skip if no pods or no containers exist but in the new ginkgo_removal branch, we only consider a test "passed" if there are no `nonCompliantObjects` and >0 `compliantObjects`.

Switch skip for nodePort test

---

cnf-certification-test/accesscontrol/suite.go

We never get to the point of setting `check.SetResult` if we are missing nonCompliant or compliant objects.

Remove early return with empty objects

---

cnf-certification-test/lifecycle/podrecreation/podrecreation.go
internal/cli/cli.go
pkg/checksdb/check.go
pkg/checksdb/checksdb.go
pkg/checksdb/checksgroup.go

The check.Abort() has been modified to panic with a message wrapped in a checksdb type. The deferred function in runCheck() will do nothing in case that especial (own) panic is detected, and no other check of that group will run.
This way we stop the goroutine for group.RunChecks() as soon as possible to avoid race conditions with the main goroutine, which will call group.OnAbort() and will register all the remaining checks as skipped, using the reason from the msg channel.

Non graceful abort for unrecoverable/critical failures inside checkFn.

---

cnf-certification-test/networking/suite.go

Remove this early `return` in the networking suite that skips the `check.SetResult` if a skip occurs.
QE networking suite now passes successfully with this change.

Remove early return in networking suite

---

cnf-certification-test/certification/suite.go
cnf-certification-test/observability/suite.go
cnf-certification-test/operator/suite.go
cnf-certification-test/performance/suite.go
cnf-certification-test/platform/suite.go
cnf-certification-test/preflight/suite.go

Update some of the calls to `checksGroup.Add` to match others in separate suites.  No functional changes.

Consolidate checksGroup.Add calls

---

.github/workflows/qe-ocp-413-intrusive.yaml
.github/workflows/qe-ocp-413.yaml
.github/workflows/qe-ocp-414-intrusive.yaml
.github/workflows/qe-ocp-414.yaml

Following the documentation from here:
https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-expanding-configurations
I'm trying to enable the QE nightlies to run against the `ginkgo_removal` branch as well in both QE and here.
The reason I'm making this change on the main branch is because it is the default branch and that's where jobs are fired from.

Enable QE nightlies for ginkgo_removal

---

main.go
pkg/flags/flags.go
run-cnf-suites.sh

The directory not only contains the claim file but also the log file, the compressed file with the results and some other helper files.

flags: change "claimloc" for "output-dir"

---

pkg/diagnostics/diagnostics.go

backporting https://github.com/test-network-function/cnf-certification-test/pull/1715

Fix for fatal error in diagnostics (#1715)

---

cnf-certification-test/accesscontrol/suite.go
internal/cli/cli.go
internal/log/log.go
pkg/certsuite/certsuite.go
pkg/checksdb/check.go
pkg/checksdb/checksgroup.go
pkg/provider/pods.go

The aim of this change is adding a bit of visual responsiveness to the current cli output of the ginkoless branch when the checks run.
For each running check it will show the elapsed time and the last log line emitted using check.Log() func. Once the check finishes, the cli line will also be rewritten but only the result will be left.
E.g.: while the check is running:
```
[ RUNNING ] lifecycle-pod-recreation (4s)   INFO  [Dec 18 07:50:14.778] [suite.go: 642] [lifecycle-pod-recreation] Draining and Cordoning node kind-worker3:
```
And when it's finished:
```
[ PASS ] lifecycle-pod-recreation
```
Also, if the check was skipped, aborted/errored, the reason will also appear so the user can quickly have an idea of what happened to that check.
E.g:
```
[ SKIP ] …
```

CLI output improvements: check's elapsed time and last log trace.

---

internal/cli/cli.go

This is a follow-up PR for #1745.
- Switched isTTY to func to remove the need for the init().
- Avoid printing a new line if log trace is received. The new RUNNING log line will appear every 10secs only.

CLI output: non-tty mode improvements.

---

pkg/certsuite/certsuite.go
pkg/claimhelper/claimhelper.go

We should reference the `flags.OutputDir` here to place the file in the correct place.

Adjust location of the XML output file

---

run-basic-batch-operators-test.sh

This adding several fixes with the intent for improve stability of the script: 
- install all namespace operators in their own namespace ("test-namespace") instead of openshift-operators. the namespace is deleted after each operator test
- keep installing operators with specific namespaces in their required namespace
- added retry function to wait until oc command succeed
- added function to wait until the cluster becomes reachable

batch operator script - fix long term errors

---

pkg/claimhelper/claimhelper.go
pkg/claimhelper/claimhelper_test.go
pkg/flags/flags_test.go

Follow up to #1753 
Changes:
- Adds `omitempty` to all XML attr's.
- Parse the startTime and endTime stamps correctly and place the duration in the XML.
- Set `FailureMessage` and `SkippedMessage` structs to pointers so they can be nil if not used.
Additional:
- Sort XML output alphabetically.

Adjust XML output

---

cnf-certification-test/observability/suite.go
pkg/checksdb/check.go
pkg/checksdb/checksdb.go
pkg/checksdb/checksgroup.go

observability: review logs

---

.github/workflows/pre-main.yaml
.github/workflows/qe-hosted.yml

Wrap the calls for `make rebuild-cluster` and `make install` with retries to avoid any flapping.

Add retries for -partner setup calls

---

cmd/tnf/generate/catalog/catalog_test.go
cnf-certification-test/accesscontrol/rbac/automount.go
cnf-certification-test/accesscontrol/rbac/automount_test.go
cnf-certification-test/accesscontrol/suite.go
internal/clientsholder/clientsholder.go
pkg/arrayhelper/arrayhelper_test.go
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_events.go
pkg/autodiscover/autodiscover_events_test.go
pkg/autodiscover/autodiscover_networkpolicies_test.go
pkg/autodiscover/autodiscover_podset_test.go
pkg/autodiscover/autodiscover_pv.go
pkg/autodiscover/autodiscover_pv_test.go
pkg/autodiscover/autodiscover_rbac.go
pkg/autodiscover/autodiscover_rbac_test.go

Various unit tests and k8s client parameter adjustments.  Instead of calling the `clientsholder` everytime we need the k8s client, just pass the client in as a parameter to make it easier for unit testing.
This isn't _all_ of the references to the `clientsholder`, just a couple of low hanging fruit.

Additional unit test coverage

---

cnf-certification-test/networking/icmp/icmp.go
cnf-certification-test/networking/icmp/icmp_test.go
cnf-certification-test/networking/netcommons/netcommons.go
cnf-certification-test/networking/policies/policies.go
cnf-certification-test/networking/policies/policies_test.go
cnf-certification-test/networking/suite.go

networking: review logs

---

cnf-certification-test/platform/cnffsdiff/fsdiff.go
go.mod
go.sum

The functionality required was already provided by our `stringhelper` package.

Remove dependency with golang-set

---

cnf-certification-test/certification/suite.go

Remove early returns without first using `check.SetResult`

Fix helmVersion test

---

.github/workflows/qe-ocp-413-intrusive.yaml
.github/workflows/qe-ocp-413.yaml
.github/workflows/qe-ocp-414-intrusive.yaml
.github/workflows/qe-ocp-414.yaml

Point these `rm -rf` calls to the actual directories being used instead of the hardcoded /tmp/ path.

Adjust the directories cleaned up in QE nightlies

---

.github/workflows/pre-main.yaml
.github/workflows/qe-hosted.yml
.github/workflows/qe-ocp-413-intrusive.yaml
.github/workflows/qe-ocp-413.yaml
.github/workflows/qe-ocp-414-intrusive.yaml
.github/workflows/qe-ocp-414.yaml

I've seen a couple of times over the past couple of weeks where something upstream fails to pull/fetch/download/etc and fails the image build.  Adding retries should help smooth out the failures.

Add retries for 'make build-image-local'

---

.github/workflows/pre-main.yaml

In the `pre-main.yml`, we disabled the gradetool while working on the `ginkgo_removal`.  We should re-enable it now.

Re-enable gradetool

---

go.mod
go.sum
pkg/configuration/configuration.go
pkg/provider/provider.go

This is to reserve CPU and memory for the daemonset in case resources are scarce

Adding configurable cpu requests/limit for the debug daemonset

---

.github/workflows/pre-main.yaml
.github/workflows/qe-hosted.yml

Now that the size of the virtual disks of the free tier is doubled, I'm testing whether or not we need these disk space cleanups anymore to speed up our runs.
See: https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/

Remove free disk space cleanup

---

pkg/certsuite/certsuite.go
pkg/checksdb/checksdb.go
pkg/checksdb/checksgroup.go
pkg/checksdb/labels.go
pkg/checksdb/labels_test.go

The labels evaluator filtering mechanism is set at program startup and remains the same throughout its lifetime, so it seeems a better fit to have it as a global variable instead of recreating it every time it's needed.

checksdb: turn the labels evaluator into a global variable

---

pkg/provider/filters.go
pkg/provider/scale_object_test.go
pkg/testhelper/testhelper.go
pkg/testhelper/testhelper_test.go

Changes:
- Added documentation for public functions in `provider/filters.go` and `testhelper/testhelper.go`.
- Added unit testing for functions that do not require an active cluster for checking skips.
- Added unit testing for report object creation.

Add unit tests for testhelper package

---

.github/workflows/pre-main.yaml

That "make make" was making the second step to fail silently, since the commands were separated by ";" instead of "&&."

Fix cluster bootstrapping step.

---

docs/configuration.md
script/run-container.sh

https://developers.redhat.com/products/openshift-local/overview
If you are running an instance of OpenShift Local (formerly CodeReady Containers) on your local machine and want to run the containerized version of the test suite against it, you have to use `--add-host` for the container to be able reach the apiserver correctly.

Add functionality for running against local CRC instances

---

run-cnf-suites.sh

When running cnf cert operator we want to allow setting cnf suites run's timeout.
With this change we enable setting timeout using an environment variable.

enable changing cnf suites timeout using env var

---

cnf-certification-test/platform/suite.go
pkg/provider/nodes.go
pkg/provider/nodes_test.go

Add a simple loop to check and make sure we are only testing nodes that have CNF workload deployed on them for the tainted node test.
A scenario this applies to would be if a user was purposefully tainting some nodes.  The debug daemonset would be spawned on those nodes but the CNF workload would not.

Add filter for tainted node test

---

go.mod
go.sum

https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.8.1

Update preflight to v1.8.1

---

.github/workflows/pre-main.yaml
.github/workflows/qe-hosted.yml

The job "smoke-tests-container" of the "Test Incoming Changes" workflow was running out of disk space again. Debugging with tmate I saw that there's another 75GB disk mounted (sdb) in /mnt that's not being used.
```
runner@fv-az975-229:~/work/cnf-certification-test/cnf-certification-test$ df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        73G   73G  463M 100% /
tmpfs           7.9G  172K  7.9G   1% /dev/shm
tmpfs           3.2G  1.6M  3.2G   1% /run
tmpfs           5.0M     0  5.0M   0% /run/lock
/dev/sda15      105M  6.1M   99M   6% /boot/efi
/dev/sdb1        74G  4.1G   66G   6% /mnt
tmpfs           1.6G   12K  1.6G   1% /run/user/1001
runner@fv-az975-229:~/work/cnf-certification-test/cnf-certification-test$ lsblk
NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0 …
```

Github CI: Step to use /mnt for docker storage.

---

cnf-certification-test/networking/icmp/icmp.go
cnf-certification-test/networking/icmp/icmp_test.go
cnf-certification-test/networking/netcommons/netcommons.go
pkg/provider/pods.go
pkg/provider/provider.go

Changes include:
- Changing `MultusIPs: map[string][]string` to `MultusNetworkInterfaces: map[string][]provider.CniNetworkInterface`.
- Making `provider.CniNetworkInterface` struct public.
- Modifying the TestPing() func to accept interface name.

Specify network interface for ICMP tests

---

cnf-certification-test/tnf_config.yml

@jmontesi noticed that we're skipping too many test cases in the smoke tests of github CI.
I've been reviewing the operator test suite ones: no operators (csvs) were tested because of a misalignment in the expected labels in the csv. This started happening when the default/deprecated label was finally remvoed in PR #1760.

Github ci: fixed example label for operators autodiscovery.

---

.github/workflows/pre-main.yaml
Makefile

The "tnf check results" command verifies that the test results are equal to the expected results found in a template file.
It provides a simpler and more integrated way of verification than the external gradetool.

workflows: use the tnf check command instead of the gradetool

---

.github/workflows/pre-main.yaml
.golangci.yml
Makefile
docs/test-standalone.md

https://github.com/golangci/golangci-lint/releases/tag/v1.56.2 
I had to disable the `revive` linter because it was flagging unit testing func calls that are mocked.

Update GolangCI-lint to v1.56.2

---

pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_operators.go

The Istio Service Mesh detection required a two step process:
1) Check for the existence of the "istio-system" namespace.
2) Check for the presence of a CR from the Istio Operator called
"installed-state".
But it has been reported that when Istio is installed using the Helm chart method this CR is not created. So, the step 2 above has been replaced for checking the presence of the "istiod" Deployment, which is in charge of running the Istio discovery service.

autodiscover: modify Istio Service Mesh detection

---

cnf-certification-test/tnf_config.yml
pkg/autodiscover/autodiscover.go
pkg/certsuite/certsuite.go
pkg/configuration/configuration.go
pkg/provider/provider.go

Configuration field for collector's endpoint was added to `tnf_config.yaml`.
In addition, prod collector's DNS was set as the default endpoint.

Add configuration field for collector's endpoint

---

.github/actions/slack-webhook-sender/action.yml
.github/workflows/pre-main.yaml
.github/workflows/tnf-image.yaml

Created an action that sends a customizable message along with some static information related to the workflow's job it is running.
It's currently used in conjunction with `if: ${{ failure() }}` to send a message to configured webhook as an alert for a failing job, but can be reused for any other purpose, as long as the webhook endpoint accepts the json object that will be sent to.
The webhook is free to format the final message accordingly but these are the fields it will receive:
```
{
"attempt": "1",
"message": "Alert or custom message!",
"job_url": "https:/github.com/path/to/workflow/job",
"commit_url": "https://github.com/path/to/commit",
"repo_url": "https://github.com/path/to/repo"
}
```
Where job_url, commit_url and attempt point to the job where the workflow is/was running, the …

Changed alert msg to be sent to a slack webhook.

---

cnf-certification-test/preflight/suite.go
pkg/certsuite/certsuite.go
pkg/provider/containers.go
pkg/provider/operators.go
pkg/provider/provider.go

The logs show that the test environment is built twice before starting running the test cases, which should not be necessary. However, disabling this rebuild of the test environment lead to an error while marshaling the `TestConfiguration` to JSON format. This PR refactors the way the Preflight test results are processed in order to produce an output of the test environment adequate for JSON marshaling without the need to rebuild it.
The problem came with the direct addition of the struct `plibRuntime.Results` into our `Container` struct. This former struct contains an interface that prevents the struct to be properly transformed to JSON. To solve this issue, another struct called `PreflightResultsDB` that only contains the information needed has been used instead. 
The test environment …

Avoid unnecessary rebuild of the test environment

---

internal/clientsholder/clientsholder.go
pkg/certsuite/certsuite.go

When the `KUBECONFIG` environment variable is set it should take precedence over the Kubeconfig stored in `$HOME/.kube/config`.

clientsholder: change Kubeconfig precedence

---

cnf-certification-test/accesscontrol/namespace/namespace.go
cnf-certification-test/accesscontrol/pidshelper.go
cnf-certification-test/accesscontrol/rbac/automount.go
cnf-certification-test/accesscontrol/rbac/roles.go
cnf-certification-test/accesscontrol/resources/resources.go
cnf-certification-test/accesscontrol/securitycontextcontainer/securitycontextcontainer.go
cnf-certification-test/accesscontrol/suite.go

Adding documentation for all the functions in access-control.

Documentation for all the functions in Access-control

---

.github/workflows/pre-main.yaml
.github/workflows/tnf-image.yaml
Dockerfile
Makefile

Modifies the Dockerfile and the workflows to build correctly for each platform, arm64 and amd64.
There are two automation workflows:
- `.github/workflows/pre-main.yaml` (creates the 'unstable' image)
- `.github/workflows/tnf-image.yaml` (creates the tagged releases)
These are both now modified to build images for both arm64 and amd64 images, package them into a manifest, and then push to our registries.
When I tested this locally, you can see I created an image named `bapalm/test-suite:v0.0.1`:
It says "See Child Manifests".
If you expand on the child manifests you can see:

Enable multi-platform image builds

---

.github/workflows/pre-main.yaml
.github/workflows/tnf-image.yaml
Dockerfile
Makefile

Reverts test-network-function/cnf-certification-test#1942
I have found out a lot about multi-stage builds since merging this.  I am going to revert and improve with another PR.

Revert "Enable multi-platform image builds"

---

.github/workflows/pre-main.yaml

https://github.com/crate-ci/typos/releases/tag/v1.20.0 seems to have broken our linting.  We can re-enable and fix later.

Temporarily disable typos linter

---

.github/workflows/tnf-image.yaml
Makefile

Follow up to #1943 
Essentially the reason the latest nightly build failed, is because it checks out the most recent tag of code, then attempted to run a `make` path that doesn't yet exist at that point in time.  
I removed the `tnf-` make paths and moved the logic straight to the github action workflow to build the images and create the manifests.

Fix tnf image build

---

.github/workflows/pre-main.yaml
.github/workflows/tnf-image.yaml

Follow up to #1943 
Related to: https://github.com/test-network-function/cnf-certification-test-partner/pull/417
Turns out we don't need to do so much manual building and image creation when there's already an action that does all of this for us.

Switch the build-and-push action for multi-arch

---

.github/workflows/pre-main.yaml

Utilize `needs` to break up this workflow and force image builds to wait for the tests to pass.

Only build image if tests pass

---

.github/workflows/qe-hosted.yml

Playing around with concurrency to see if I can speed up the overall QE testing for PRs.
- Builds the image first in job, and if it is successful then runs all of the QE PR checks.
- This saves roughly ~3-5 minutes off of each workflow job.  Which can help improve overall resource usage on the free tier of github actions as we only have 20 available runner slots at any given time.

Build image first for QE PR runs

---

internal/log/custom_handler.go
internal/log/log.go
pkg/checksdb/check.go

The fatal log level is added to the generic top-level log functions as well as the check's log methods. When used the log message is printed in the log file and sdterr, then the program exits with an error code.

log: add fatal level

---

cnf-certification-test/identifiers/identifiers.go

Those tests are not covered in QE. The flag was likely set by mistake.

identifiers: unset the qe covered flag for some new tests

---

cnf-certification-test/operator/suite.go

It pollutes the log file to the point that file editors struggle to handle it. Also, it does not seem to be helpful from a practical point of view in the way it is printed.

operator: delete very long debug log

---

.github/workflows/qe-ocp-415-intrusive.yaml

Since there might be a possibility of the `helm` certification tests running at the same time, lets kick these runs off at different times.
This PR adjusts the 4.15 nightly run to start at 5AM UTC.  The 4.14 nightly run is unchanged and starts at midnight UTC.

Kick off self-hosted runner QE runs at different times

---

script/rhcos_versions.sh

The script was missing 4.15 and 4.16 which was causing failures in our new 4.15 OCP QE cluster.

Add 4.15 and 4.16 to RHCOS versions script

---

pkg/compatibility/compatibility.go

https://access.redhat.com/support/policy/updates/openshift
Moved 4.13 to maintenance support section.

Add OCP 4.15 to lifecycle matrix

---

CATALOG.md
README.md
cmd/tnf/generate/catalog/catalog.go
docs/configuration.md
docs/index.md
docs/test-output.md
docs/test-spec.md
docs/test-standalone.md
docs/workload-developers.md
mkdocs.yml

The references to "CNF Certification" or "CNF Certification Suite" have been changed to "Red Hat Best Practices Test Suite for Kubernetes" or a simplified version of this name, such as "Test Suite", when the meaning is clear from the context.
Also, to broaden the scope of the potential targets of the Test Suite the work "CNF" has been replaced for "workload" where applicable.

docs: CNF Certification rename to Red Hat Best Practices for Kubernetes

---

CATALOG.md
cnf-certification-test/identifiers/exceptions.go
cnf-certification-test/identifiers/identifiers.go
cnf-certification-test/identifiers/remediation.go

The references to "CNF Certification" or "CNF Certification Suite" have been changed to "Red Hat Best Practices Test Suite for Kubernetes" or a simplified version of this name, such as "Test Suite", when the meaning is clear from the context.
Also, to broaden the scope of the potential targets of the Test Suite the work "CNF" has been replaced for "workload" where applicable.

Catalog rename

---

.github/workflows/qe-ocp-414-intrusive.yaml
.github/workflows/qe-ocp-414.yaml
.github/workflows/qe-ocp-415-intrusive.yaml
.github/workflows/qe-ocp-415.yaml

No need to build the image for these nightlies every run.  We already build the `unstable` image and it is available already.
Uses another job to pull the image prior to kicking off all of the tests.
Similar to: 
- https://github.com/test-network-function/cnf-certification-test-partner/pull/316
- https://github.com/test-network-function/cnfcert-tests-verification/pull/718

Switch QE nightlies to use unstable image

---

.github/workflows/pre-main.yaml

It seems that there is a bug with the `macos-latest` runners (which are now ARM based).  Let's temporarily remove this.

Remove macos runner from unit tests

---

README.md

Group dynamic badges are placed together on the left, while static badges are positioned to the right.

Group badges

---

CATALOG.md
cmd/tnf/generate/catalog/catalog.go
cnf-certification-test/identifiers/identifiers.go

This PR 
* adds the definition of 4 security context categories and link to refer to that section from the security-context test case.
* refactors the existing content generation for better readability

style : Modify catalog generation to add 4 security contexts categories

---

pkg/certsuite/certsuite.go

The evaluator for label expressions needs to be initialized before calling the method checksdb.FilterChecksIDs().

Bug fix: avoid runtime panic (SIGSEGV) when using the list flag

---

cmd/tnf/main.go
cmd/tnf/run/run.go
main.go
pkg/certsuite/certsuite.go
pkg/flags/flags.go
pkg/provider/provider.go

Use `./tnf run <flags>` to run the test suite. See `./tnf run -h `for more info.
The original way of running the test suite using the "cnf-certification-test" binary and the bash scripts is still available and used in the GitHub CI. This change just add the possibility of running the test suite with the "tnf" command.

cmd/tnf: add subcommand to run the test suite

---

.github/workflows/update-rhcos-mapping.yml

Looks like the `oc` client isn't preloaded into ubuntu-24.04.

Switch RHCOS job back to 22.04

---

cmd/certsuite/run/run.go
pkg/configuration/configuration.go
pkg/provider/provider.go
pkg/provider/provider_test.go

This is the image used for the debug DaemonSet.
Also, keep the method to set the debug image using environment variables for compatibility with the old binary but save the variables into the "TestParameters" struct to have them grouped together with the rest of environment variables.

cmd/certsuite: add flags for selecting the TNF debug image

---

cnf-certification-test/platform/suite.go
pkg/compatibility/compatibility.go
pkg/compatibility/compatibility_test.go
pkg/provider/nodes.go
pkg/provider/provider.go
pkg/provider/provider_test.go

The `ocpBetaVersions` slice was only containing entries for 4.13 and 4.14.  I added more entries for 4.15, 4.16, and 4.17 and I also added a unit test for the version that @ramperher reported as failing.
Bonus, I changed the strings that report "master" nodes to "control plane" nodes.

Bug fix: adjust OCP beta slice

---

.github/workflows/qe-hosted.yml
.github/workflows/qe-ocp-414-intrusive.yaml
.github/workflows/qe-ocp-414.yaml
.github/workflows/qe-ocp-415-intrusive.yaml
.github/workflows/qe-ocp-415.yaml

Related to: #2095 
Using what I learned in the `use_binary` branch, this enables testing against the binary on the nightly runs.  This does not change the PR QE runs as I added a conditional that only applies whenever kicked via `schedule`.

Add binary test to nightlies

---

.github/workflows/pre-main.yaml
.gitignore
cmd/certsuite/check/results/results.go
docs/index.md
docs/test-container.md
docs/test-output.md
internal/log/log.go
run-basic-batch-operators-test.sh

From "cnf-certsuite.log" to "certsuite.log" to be in line with the recent renaming of the test suite.

log: rename global log file

---

.github/workflows/pre-main.yaml

The same tasks using the new "certsuite" binary are already working as expected, so there is no need to duplicate the verification.
Also, in line with the recent renaming some "tnf" references are changed to "certsuite".

CI workflows: delete legacy tasks using the old binary

---

.github/workflows/qe-ocp-pre-main.yaml

Enable both the `operator` and `affiliatedcertification` suites on PRs.  Targeting 4.16 off the bat.

Enable OCP testing on PRs

---

cnf-certification-test/accesscontrol/suite.go
cnf-certification-test/lifecycle/podsets/podsets_test.go
cnf-certification-test/lifecycle/scaling/deployment_scaling_test.go
cnf-certification-test/lifecycle/scaling/statefulset_scaling.go
pkg/autodiscover/autodiscover.go
pkg/autodiscover/constants.go
pkg/podhelper/podhelper.go
pkg/podhelper/podhelper_test.go
pkg/provider/pods.go
pkg/provider/pods_test.go
pkg/provider/provider.go

**Issue** [JIRA Link](https://issues.redhat.com/browse/CNFCERT-885)
**Includes**
- Logic to get all pods managed by the operators under test from the namespaces mentioned through `targetNamespaces` in CSV. The client code gets this from `env.AllOperatorPods` 
- Refactoring of the retrieval of owner references code (moved from `provider` to `podhelper`
**NOTE** 
To be used in [this PR](https://github.com/test-network-function/cnf-certification-test/pull/1967)

feat : Add helper function to get all operator pods

---

Makefile
cnf-certification-test/results/html/results.html
script/get-results-html.sh

It avoids the need to download the parser repo to just copy the results.html file. The script that to does this is also deleted.

Makefile: use curl to get the parser webpage (results.html)

---

.github/workflows/pre-main.yaml
Dockerfile

build-depends: https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/356
The container image is updated to avoid building the old binary and copying stuff that it is not required anymore.
The "certsuite" binary is installed in "/usr/local/bin" so that it can be directly called.
The GitHub workflows have been updated accordingly.
An update in DCI and QE will be necessary as well.

Dockerfile: do not build the legacy binary

---

.github/workflows/qe-ocp-417-intrusive.yaml
.github/workflows/qe-ocp-417.yaml

Adds YAMLs for 4.17 OCP nightlies.
Related to: https://github.com/test-network-function/cnfcert-tests-verification/pull/818
https://mirror.openshift.com/pub/openshift-v4/clients/ocp-dev-preview/
This page lists a very early version of the 4.17 release which I deployed internally.

Add 4.17 nightly YAML

---

script/run-basic-batch-operators-test.sh

- Added a helper function to ensure all packages are reachable before writing them in the operator list.
- Delete catalog only after all the operators in operator list were tested.

Fix batch script to enable run on an entire catalog

---

cnf-certification-test/platform/isredhat/isredhat.go
cnf-certification-test/platform/isredhat/isredhat_test.go

Support RHEL releases with "Beta" in the name like `Red Hat Enterprise Linux release 8.5 Beta (Ootpa)`

Adjust RHEL regex to support Beta versions

---

internal/clientsholder/clientsholder.go

In current state, it is not possible to run the suites from inside a cluster, without `kubeconfig` being specified (using `-k` flag), as the `KUBECONFIG` existence is checked before trying to create a client using an in cluster configuration.
The change in this PR allows the following flow (see [function](https://github.com/test-network-function/cnf-certification-test/blob/cb5fe52b41919f25ae5e14b49fcdb0d027eb4a32/internal/clientsholder/clientsholder.go#L215)):
- Try creating a client using in cluster configuration - if it worked, use it.
- If it didn't work see if there is a specified `KUBECONFIG` (through `-k` flag or default directory), if there is, use it.
- If there is no `KUBECONFIG` specified - return an error

Remove unnecessary kubeconfig check

---

.github/workflows/upload-release-assets.yaml
Makefile

It builds and uploads the Certsuite binaries compressed in tar.gz for x86_64 and ARM 64.
build-depends: 31882

workflows: add new workflow to upload release assets

---

script/run-basic-batch-operators-test.sh

tnf_config file directory when executing command is miss matched with the one defined [here](https://github.com/test-network-function/cnf-certification-test/blob/7d772bb7c4e96795c85a50998e41a148a4c33b9e/script/run-basic-batch-operators-test.sh#L621)

fix tnf_config.yaml directory typo batch script command

---

cnf-certification-test/tnf_config.yml
expected_results.yaml

https://issues.redhat.com/browse/CNFCERT-990
This PR makes the lifecycle-cr-scaling test cases as PASSED from skipped as the tnf_config is configured to use the the deployed test operator (cr-scale-operator) and run this test case.

configure : Test operator labels in tnf_config yaml

---

cmd/certsuite/main.go
cmd/certsuite/version/version.go

It displays the Certsuite version as well as the Claim file version.

cmd/certsuite: add new command to show the version

---

cmd/certsuite/info/info.go
cmd/certsuite/main.go
cmd/certsuite/version/version.go
internal/cli/cli.go

At the moment only the "--test-case/-t" flag is supported to show the information available in the Catalog for a particular test case.

cmd/certsuite: add new "certsuite info" command to display Catalog info

---

version.json

related to: https://github.com/test-network-function/parser/pull/47

Bump parser version to v0.4.6

---

version.json

This is to pick up: https://github.com/test-network-function/parser/pull/48

Bump parser version to v0.4.7

---

CATALOG.md
tests/identifiers/identifiers.go

Changing the `access-control-namespace` test to be `Optional` instead of `Mandatory`.
Related links:
- https://test-network-function.github.io/cnf-best-practices-guide/
- https://github.com/test-network-function/test-network-function/commit/4c2f48dde4ad12207986864859c9018c40f3dbad 
For future reference, we decided to change this to optional instead of just removing the `openshift-` prefix from the list because we wanted future visibility into potential failures/problems if a partner somehow uses one of these namespaces.

Adjust 'access-control-namespace' test to be Optional

---

CATALOG.md
tests/identifiers/identifiers.go

Another option when compared to: #2244 
The best practices document mentions that pods should be `Leveraging read only root filesystem when possible.` 
https://test-network-function.github.io/cnf-best-practices-guide/#cnf-best-practices-cnf-security
So this makes it seem that we should mark this test as Optional instead of Mandatory.

Mark read-only filesystem test as Optional

---

tests/lifecycle/scaling/scaling_helper_test.go

Brings this file's coverage to `100%`.  The overall `scaling` package only has 30.4% coverage at the time of this PR.

Add scaling helper unit tests

---

cmd/certsuite/check/results/results.go

The folder "cnf-certification-test" no longer exists.

cmd/certsuite: update default value for log file in "check results"

---

.github/workflows/pre-main.yaml
.github/workflows/qe-hosted.yml
.github/workflows/tnf-image.yaml
Makefile

While we are working towards renaming the test suite, the repo, and the image name, we should push the new image tag right along side of the old image tag so there is a period of backwards compatibility.
For this proof-of-concept, I chose to use `testnetworkfunction/k8s-best-practices-certsuite` as the name of the new image since it best matches the new best practices repository name: https://github.com/test-network-function/k8s-best-practices-guide
I created the repo in Quay: https://quay.io/repository/testnetworkfunction/k8s-best-practices-certsuite
Bonus: Remove unused Makefile paths.

Add 'new' image tag to push during CI runs

---

cmd/certsuite/info/info.go
cmd/certsuite/main.go
cmd/certsuite/main_test.go

Also adds a unit test for the "certsuite version" command.

cmd/certsuite: refactor main to allow unit testing subcommands

---

Dockerfile
Makefile

Seeing if things break if I remove these dependencies.
Follow up, it looks we can safely remove the `jq` and `gcc` deps.

Remove some dependencies from the image

---

cmd/certsuite/info/info.go
cmd/certsuite/main_test.go
cmd/certsuite/run/run.go
internal/cli/cli.go
pkg/certsuite/certsuite.go
pkg/configuration/configuration.go

As the "info" command already gets detailed Catalog information, it looks more convenient to integrate the functionality for listing test cases in it.
Also adds a new unit test for the "list" flag as part of the "info" command.

cmd/certsuite: move the "list" flag from "run" to "info"

---

.github/workflows/pre-main.yaml
.github/workflows/tnf-image.yaml
cmd/certsuite/run/run.go
docs/runtime-env.md
version.json

https://quay.io/repository/testnetworkfunction/k8s-best-practices-debug?tab=tags
https://github.com/test-network-function/k8s-best-practices-debug 
Instead of building and pushing the `debug` image from the `cnf-certification-test-partner` repo, we decided to de-couple the `debug` image from the complexity of the partner repo and just build it separately.
Changes to the partner repo (which is primarily used for the CI-related tasks) shouldn't affect the debug image (and versioning scheme) going forward.

Change debug-partner to k8s-best-practices-debug

---

tests/observability/suite.go

Use all the labels defined in the PDB's selector "MatchLabels" fields to match workloads, as the Kubernetes documentation specifies that those labels should be ANDed.
Also, take into account the "MatchExpressions" field of the selector when it can be properly converted to a map.

tests/observability: fix observability-pod-disruption-budged test case

---

cmd/certsuite/run/run.go
pkg/certsuite/certsuite.go
pkg/checksdb/checksdb.go
pkg/claimhelper/claimhelper.go
pkg/configuration/configuration.go
pkg/labels/labels.go
pkg/labels/labels_test.go

Adds a flag `--sanitize-claim` which defaults to false.  This is mostly used for QE.
Modifies the `NewLabelsExprEvaluator` and related functions to its own package named `labels`.

Add option to sanitize claim file result output

---

pkg/claimhelper/claimhelper.go

`GetConfigurationFromClaimFile` was unused along with `UnmarshalClaimFile`

Remove unused func in claimhelper

---

pkg/claimhelper/claimhelper.go
pkg/claimhelper/claimhelper_test.go

Cover more functionality in the `claimhelper` package with unit tests.

Add claimhelper pkg unit tests

---

.github/workflows/merge.yaml
.github/workflows/pre-main.yaml
.github/workflows/qe-hosted.yml
.github/workflows/qe-ocp-414-intrusive.yaml
.github/workflows/qe-ocp-414.yaml
.github/workflows/qe-ocp-415-intrusive.yaml
.github/workflows/qe-ocp-415.yaml
.github/workflows/qe-ocp-416-intrusive.yaml
.github/workflows/qe-ocp-416.yaml
.github/workflows/qe-ocp-417-intrusive.yaml
.github/workflows/qe-ocp-417.yaml
.github/workflows/qe-ocp-pre-main.yaml
.github/workflows/tnf-image.yaml
.github/workflows/update-rhcos-mapping.yml
Makefile
docs/cluster-deploy/README.md
docs/cluster-deploy/cnf-certsuite.yaml
docs/configuration.md
docs/developers.md
docs/runtime-env.md
docs/test-output.md
tests/lifecycle/suite.go

This PR needs to be merged in tandem with: https://github.com/test-network-function/cnfcert-tests-verification/pull/857/
TODO: Remove the `tnf_rename` ref's in the code after merge.

Various CI Updates

---

.github/workflows/pre-main.yaml
cmd/certsuite/run/run.go
docs/runtime-env.md
version.json

https://github.com/redhat-best-practices-for-k8s/certsuite-probe/releases/tag/v0.0.6

Update certsuite-probe to v0.0.6

---

.github/workflows/pre-main.yaml
.golangci.yml
Makefile
internal/cli/cli.go
internal/clientsholder/command.go
internal/results/archiver.go
pkg/provider/containers.go
pkg/provider/operators.go
pkg/provider/pods.go
script/run-basic-batch-operators-test.sh
tests/accesscontrol/suite.go
tests/identifiers/doclinks.go
tests/identifiers/identifiers.go
tests/lifecycle/scaling/deployment_scaling_test.go
tests/lifecycle/scaling/statefulset_scaling.go
tests/lifecycle/suite.go
tests/networking/netutil/netutil.go
tests/platform/hugepages/hugepages.go
webserver/webserver.go

Looks like there was an update to the linter which is now flagging things previously unflagged.
This seems to mostly target integer conversions which have been unflagged in the past.

Update GolangCI-lint to v1.60.2; various fixes

---

.github/workflows/pre-main.yaml
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_service_accounts.go
pkg/autodiscover/autodiscover_services_accounts_test.go
pkg/provider/pods.go
pkg/provider/provider.go
tests/accesscontrol/suite.go
tests/common/rbac/automount.go
tests/common/rbac/automount_test.go
tests/operator/suite.go

Refactoring to collect service accounts in autodiscover package and save them to claim file
- All service accounts are collected during discovery in AllServiceAccounts slice
- The AllServiceAccountsMap is mapping service account namespace + service account name to the service account objects for conveniently searching service accounts
- The AllServiceAccountsMap is part of the provide.Pod object. This allows for unit testing and easy access of the service account information in IsAutomountServiceAccountSetOnSA
- IsAutomountServiceAccountSetOnSA queries the Automount service account token from the pod object
- AllServiceAccounts and testServiceAccount are saved in the claim file
TODO:  
- ~system tests~
- doc

Gather service accounts in claim file

---

.github/workflows/pre-main.yaml

This PR avoids failing `pre-main` workflow when collector's sanity check fails - instead it will only send a warning message to the our slack channel.

Avoid failing workflow when collectors sanity check fails

---

.golangci.yml
internal/cli/cli.go
internal/clientsholder/command.go
internal/results/archiver.go
pkg/provider/containers.go
pkg/provider/operators.go
tests/accesscontrol/suite.go
tests/lifecycle/scaling/deployment_scaling_test.go
tests/lifecycle/suite.go
tests/networking/netutil/netutil.go
tests/platform/hugepages/hugepages.go
webserver/webserver.go

- Excludes `G115` from the `gosec` linter.
- Disables `printf` linting under `govet`.

Update golangci settings

---

.github/workflows/qe-ocp-arm-416.yaml

This job should be checking out `main` instead of `limit_procs`.

Remove bad ref to QE repo in ARM runs

---

.github/actions/setup-partner-cluster/action.yml
.github/workflows/qe-hosted.yml

We are seeing out of disk space warnings on these QE PR and nightly runs that are hosted by Github.

Adjust docker to use /mnt sdb for storage in QE hosted

---

cmd/certsuite/main_test.go
expected_results.yaml
internal/clientsholder/clientsholder.go
tests/identifiers/doclinks.go
tests/identifiers/identifiers.go
tests/identifiers/remediation.go
tests/observability/suite.go
tests/observability/suite_test.go

build-depends: https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/421
Test setup: 
OCP 4.11.18 running as a local CRC-2.12.
On the top, deploying [eventtest-operator](https://github.com/redhatci/eventtest-operator?tab=readme-ov-file#demo-2-on-crc-2120-41118) using API [events.k8s.io/v1beta1](https://github.com/redhatci/eventtest-operator/blob/main/scripts/send_events.py#L39-L40) deprecated in OCP-4.12 / k8s 1.25. This API is used dynamically, out of Python kubernetes package. 
```
$ oc version
Client Version: 4.11.18
Kustomize Version: v4.5.4
Server Version: 4.11.18
Kubernetes Version: v1.24.6+5658434
$ make show
kubectl get crds | grep event
eventtests.eventtest.com                                          2024-07-31T12:10:01Z
kubectl get eventtests -n default
NAME …
```

Add check to ensure workload compliance with the next k8s version

---

.github/workflows/pre-main.yaml
cmd/certsuite/run/run.go
docs/runtime-env.md
version.json

https://github.com/redhat-best-practices-for-k8s/certsuite-probe/releases/tag/v0.0.8

Update probe image to v0.0.8

---

cmd/certsuite/generate/catalog/catalog.go
go.mod
pkg/claimhelper/claimhelper.go
tests/accesscontrol/namespace/namespace.go
tests/lifecycle/podrecreation/podrecreation.go
tests/platform/isredhat/isredhat.go
tests/platform/nodetainted/nodetainted.go

I noticed that we were only using `logrus` as a direct dependency in 3 lines.  By switching these lines over to the `log` package we can remove logrus as a direct dependency.

Remove logrus as direct dependency

---

.github/workflows/pre-main.yaml

This PR removes collector's sanity check from pre-main workflow, as it was moved to collector's repo (see [job](https://github.com/redhat-best-practices-for-k8s/collector/blob/541336366ae37433f3b18a94bb8c0a3ebdb070eb/.github/workflows/pre-main.yaml#L172)).

Remove collector's sanity check from pre-main workflow

---

tests/observability/suite_test.go

TestEvaluateAPICompliance seemed to be flaky when comparing expected vs actual.
I removed the `ElementsMatch` assertions and just swapped it for searching through the slices manually.

Fix flaky test TestEvaluateAPICompliance

---

.github/workflows/qe-ocp-arm-416.yaml
.github/workflows/qe-ocp-pre-main.yaml

No need to run these jobs on the OCP self-hosted runners if the author is dependabot.

Restrict OCP self-hosted PR runners

---

tests/observability/suite_test.go

Follow up to: #2430 
Simply looping wasn't enough because the map can be in any order.

Brute force TestEvaluateAPICompliance unit test fix

---

cmd/certsuite/upload/results_spreadsheet/results_spreadsheet.go
cmd/certsuite/upload/results_spreadsheet/sheet_utils.go

In order to allow the use of some functions that are used in certsuite sub command `upload results-spreadsheet` creation  in the "operator-results-spreadsheet" repo (that extends the use of the existing spreadsheet), this PR makes those functions public.

Make necessary results spreadsheet functions public 

---

cmd/certsuite/upload/results_spreadsheet/results_spreadsheet.go

This PR adds `credentials` as an argument of  `CreateSheetsAndDriveServices` func  in order to allow the use of it independently from using `upload results-spreadsheet` sub-command.
In current state, the credentials are sent using a flag to the mentioned sub command, which limits functions using this variable to run using the sub-command only.
In the `operator-results-spreadsheet` repo, we would like to allow the use of `CreateSheetsAndDriveServices` func (which uses the `credentials` variable) in order to add more columns to an existing sheet, and for that we need the credentials to be set manually.

Add Setter and Getter functions to results spreadsheet google creds

---

cmd/certsuite/upload/results_spreadsheet/const.go
cmd/certsuite/upload/results_spreadsheet/results_spreadsheet.go

This PR adds\adjusts public constants to allow consistency and easy modification as they will be used in the `operator-results-spreadsheet` repo.

Add public constants for results spreadsheet

---

cmd/certsuite/claim/compare/compare_test.go
cmd/certsuite/claim/compare/testdata/claim_access_control.json
cmd/certsuite/claim/compare/testdata/diff1.txt
cmd/certsuite/claim/compare/testdata/diff1_reverse.txt
cmd/certsuite/claim/compare/versions/versions_test.go
cmd/certsuite/pkg/claim/claim.go
cmd/certsuite/pkg/claim/claim_test.go

Some UTs were commented on commit 62f679d, so this commit uncomment and fixes them.
Also, supported claim schema has been switched to v0.5.0

Fixes for certsuite claim compare UTs.

---

tests/accesscontrol/securitycontextcontainer/securitycontextcontainer.go

Container's securityContext.readOnlyRootFilesystem field should only be checked if SCC.ReadOnlyRootFilesystem is true. Otherwise, it means it can have any value.

Fix for the SCC categories check.

---

cmd/certsuite/upload/results_spreadsheet/const.go
cmd/certsuite/upload/results_spreadsheet/results_spreadsheet.go
cmd/certsuite/upload/results_spreadsheet/sheet_utils.go

This PR adds some constants related to the results spreadsheet to allow consistency in the `operator-results-spreadsheet` repo.
Also,  `getHeadersFromSheet` function was converted to a public function to allow its us in that repo as well.

Add Results spreadsheet constants and public functions

---

pkg/compatibility/compatibility.go

https://access.redhat.com/support/policy/updates/openshift 
Moved 4.14 and 4.15 to Maintenance Support section.
Apparently we forgot to make the 4.16 changes when that went GA as well.

compatibility: Add 4.16 and 4.17 records to matrix

---

cmd/certsuite/claim/compare/testcases/testcases_test.go
cmd/certsuite/generate/catalog/catalog_test.go
pkg/arrayhelper/arrayhelper_test.go
pkg/autodiscover/autodiscover_operators_test.go
pkg/podhelper/podhelper_test.go
pkg/provider/operators_test.go
tests/accesscontrol/securitycontextcontainer/securitycontextcontainer.go
tests/lifecycle/podsets/podsets_test.go
tests/networking/netcommons/netcommons_test.go
tests/platform/operatingsystem/operatingsystem_test.go
tests/platform/sysctlconfig/sysctlconfig_test.go

Take advantage of `slices` and `maps` built in packages when comparing maps and string slices.
The `maps` and `slices` packages were added in Go 1.21: https://tip.golang.org/doc/go1.21#library

Switch comparisons from reflect.DeepEqual to slices/maps libs

---

cmd/certsuite/claim/compare/testcases/testcases_test.go
cmd/certsuite/generate/catalog/catalog_test.go
pkg/arrayhelper/arrayhelper_test.go
pkg/autodiscover/autodiscover_operators_test.go
tests/platform/operatingsystem/operatingsystem_test.go
tests/platform/sysctlconfig/sysctlconfig_test.go

@greyerof pointed out that under the Assert.Equal function call, its doing the comparison using reflect.DeepEqual anyways.
Follow up to #2484 to just completely remove the comparison if we're using assert equal anyways.

Assert equal vs Assert true for comparisons

---

cmd/certsuite/upload/results_spreadsheet/results_spreadsheet.go

This PR adds the following log messages to the results spreadsheet app:
- A message indicating starting to generate raw results sheet.
- A message indicating results raw results sheet has been generated.
- A message indicating starting to generate conclusion sheet.
- A message for each individual workload spreadsheet that has been created.
- A message indicating results conclusions sheet has been generated.
When the app finishes running, a msg with saying the results spreadsheet has been created successfully will appear together with a url of the created spreadsheet.

Add log messages to results spreadsheet app

---

CATALOG.md
expected_results.yaml
pkg/testhelper/testhelper.go
tests/identifiers/doclinks.go
tests/identifiers/identifiers.go
tests/identifiers/remediation.go
tests/operator/suite.go

Adds an `operator` suite test for making sure they are not using hugepages in their pods that utilizes the existing `pod.HasHugepages()` function.
Note, I have left the test case as fully `Optional` for now until we discuss Mandatory or Optional as a group.

operator: Add no hugepages test

---

CATALOG.md
expected_results.yaml
tests/identifiers/doclinks.go
tests/identifiers/exceptions.go
tests/identifiers/identifiers.go
tests/identifiers/remediation.go
tests/operator/suite.go

Adds a test looking for the existence of the olm.skipRange annotation on the CSV.
Note: We will have to switch the expected result of this test to `skipped` when Hazelcast operator is removed.
build-depends: https://github.com/dci-labs/dallas-pipelines/pull/1245

operator: add olm.skipRange annotation test

---

CATALOG.md
expected_results.yaml
pkg/provider/pods.go
pkg/provider/pods_test.go
tests/identifiers/doclinks.go
tests/identifiers/identifiers.go
tests/identifiers/remediation.go
tests/networking/suite.go

Adds a test that checks that Network Attachment Definitions are specifying their MTU values explicitly.
EDIT: I was trying to follow the quick start guide [here](https://github.com/openshift/sriov-network-operator/blob/master/doc/quickstart.md) for the SRIOV network operator but I don't have access to the necessary [hardware](https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/doc/supported-hardware.md).
We'll have to maybe figure out how to test this via QE on supported hardware in the future.

networking: Add MTU value test for SRIOV NAD's

---

cmd/certsuite/claim/show/csv/cnf-type.json

Adding the following operators to the default list of telco operators
lvms-operator
power-monitoring-operator
loki-operator
tempo-operator

Updating the default list of telco operators

---

CATALOG.md
expected_results.yaml
pkg/provider/provider.go
tests/identifiers/doclinks.go
tests/identifiers/identifiers.go
tests/identifiers/remediation.go
tests/operator/suite.go

Adds a new mandatory test in the `operator` suite that checks to ensure the same CSV is not installed more than once.  CSVs installed by OLM are uniquely named `operator.version` format.  However it is possible to have the CSV exist in more than one namespace.  The best practices document forbids that from being the case.
If you try to install an operator more than once in the same cluster using the UI, it prevents it with the following message:
So the only way you could get around this would be to manually apply YAMLs I would assume.  I was able to do that in my own cluster.

operator: Multiple same operators installed test

---

pkg/provider/containers.go
pkg/provider/containers_test.go
pkg/provider/pods.go
pkg/provider/pods_test.go
pkg/stringhelper/stringhelper.go
tests/accesscontrol/suite.go

In the current test, the check we check RunAsNonRoot separately for pods then for its containers. However the pod RunAsNonRoot is just a default value for containers so it should not be checked separately. The pod value for RunAsNonRoot is used only if the RunAsNonRoot is not present in the container (nil). 
This PR changes the logic of the test to use the pod configuration as a default value for the container.
see https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-container
> Set the security context for a Container
> To specify security settings for a Container, include the securityContext field in the Container manifest. The securityContext field is a [SecurityContext](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1 …

fix for RunAsNonRoot check

---

cmd/certsuite/claim/compare/testcases/testcases.go
pkg/checksdb/checksdb.go

@greyerof pointed out in another PR to remove my `nolint` for gocritic on a loop so I figured I'd go and clear out the rest of them in the test suite.

Remove loop-related gocritic nolint entries

---

pkg/autodiscover/autodiscover.go
pkg/podhelper/podhelper.go
pkg/podhelper/podhelper_test.go
pkg/provider/operators.go
pkg/provider/pods.go
pkg/provider/provider.go

This change adds an autodiscovery mechanism for operand pods that "belong" to CSVs/Operators under test. This is a separate and complementary way to the by-label/by-namespace already existing discovery modes.
Usually, operands are deployed by operators by means of a CR. Ideally, operators designers should also flag that CR as owner of those operand pods that are deployed in the cluster.
The autodiscovery mechanism for operand pods creates a list of CRDs owned by the CSVs under test. Then, it iterates over every pod found in the configured namespaces in order to get whether its owner is a CR of any of those CRD types. If so, it's added to the list of pods under test if it wasn't already there.

Operand pods autodiscovery

---

.github/actions/setup-partner-cluster/action.yml
.github/workflows/qe-ocp-pre-main.yaml
config/certsuite_config.yml
expected_results.yaml

Linked to https://github.com/redhat-best-practices-for-k8s/certsuite-sample-workload/pull/510

Removed hazelcast operator from smoke tests.

---

script/run-basic-batch-operators-test.sh

Some calls to certsuite where expecting a local executable, instead we are pulling the latest unstable image and copying certsuite executable from it. Podman is no longer used to run the certsuite, the certsuite executable is directly called.

Use certsuite executable from image everywhere in the batch operators test script

---

.golangci.yml
Makefile
pkg/provider/containers_test.go

https://github.com/golangci/golangci-lint/releases/tag/v1.62.2

Update GolangCI-lint to v1.62.2

---

tests/identifiers/doclinks.go
tests/identifiers/identifiers.go
tests/identifiers/remediation.go

Follow up to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2479
These are leftover variables that are unused from when these tests were part of the `operator` suite specifically.

Remove legacy RunAsUser vars

---

tests/operator/suite.go

As reported in issue https://github.com/redhat-best-practices-for-k8s/certsuite/issues/2593, the test case operator-single-crd-owner might produce false positives.
The original implementation didn't handle cases where a single CRD name can have more than one version.
I was able to test the false positive (original code) and this fix in OCP 4.16.3 with package "amq-broker-rhel8" which also owns same CRD with different versions.

Fix for operator-single-crd-owner test case.

---

.github/workflows/pre-main.yaml
CATALOG.md
cmd/certsuite/run/run.go
docs/runtime-env.md
expected_results.yaml
pkg/autodiscover/autodiscover.go
pkg/provider/catalogsources.go
pkg/provider/catalogsources_test.go
pkg/provider/provider.go
pkg/testhelper/testhelper.go
pkg/testhelper/testhelper_test.go
tests/identifiers/doclinks.go
tests/identifiers/identifiers.go
tests/identifiers/remediation.go
tests/operator/catalogsource/catalogsource.go
tests/operator/catalogsource/catalogsource_test.go
tests/operator/helper.go
tests/operator/helper_test.go
tests/operator/suite.go
version.json

Adds a test for operator image bundles.  They must have a bundleCount less than 1000 images.  This is new from the v1.6 document.

operator: image bundle < 1000 references test

---

script/rhcos_versions.sh

`4.18` candidates are starting to show up in the mirrors.  Time to add this to the daily script.

Add 4.18 to the RHCOS script

---

pkg/compatibility/compatibility.go

Follow up to #2613 
The beta versions slice needed to be adjusted as well.

Add 4.18 to beta versions slice

---

pkg/provider/containers.go
pkg/provider/pods.go
pkg/stringhelper/stringhelper.go
pkg/stringhelper/stringhelper_test.go
tests/accesscontrol/suite.go

This test case had the same issue that was fixed here: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2557
With the prior implementation, the test case failed if pod's level SCC's runAsUser was set to 0 but container's SCC runAsUser was set to any non-zero value, like 1001. This should pass as container's SCC runAsUser value takes precedence over pod's one.
I followed the same approach: the field RunAsUser in container's SCC takes precedence over pod's level one.
Also, replaced the helper function stringhelper.BoolToString with stringhelper.PointerToString(), which works for any type now, as long as it has a stringer method implementation.

Fix for access-control-security-context-non-root-user-id-check

---

.github/workflows/qe-ocp-pre-main.yaml
pkg/autodiscover/autodiscover_operators.go

PR #2479 fixed the autodiscovery of operator's pods and also added them to the pods-under-test list. The problem is that, when using namespace discovery mode, it was also adding every cluster-wide operator's controller pods to that list.
With this change, the operator (controller's pod) must be running in one of the configured/test namespaces in order to consider that CSV as part of the operators under test.

CSVs autodiscovery fix.

---

pkg/provider/operators.go

In the `provider.go`, we have:
```
env.OperatorGroups, err = GetAllOperatorGroups()
if err != nil {
log.Fatal("Cannot get OperatorGroups: %v", err)
}
```
Where if we fail to do a lookup for the OperatorGroups, we are issuing a `log.Fatal` which then crashes the execution.  In my opinion we should handle this gracefully if its a basic `Not Found` error.
This is an example of running against a cluster without any OperatorGroups without this change:
```
bpalm at bpalm-mac in ~/Repositories/go/src/github.com/redhat-best-practices-for-k8s/certsuite on main [?$]
$ ./certsuite run -l accesscontrol
FATAL: Cannot get OperatorGroups: the server could not find the requested resource (get operatorgroups.operators.coreos.com)
```

provider: prevent fatal log when no operatorGroups

---

go.mod
go.sum
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_operators.go
pkg/autodiscover/autodiscover_operators_test.go

Switches the following funcs to use more specific interfaces:
- findOperatorsMatchingAtLeastOneLabel
- getAllOperators
- findOperatorsByLabels
- findSubscriptions
- getAllInstallPlans
- getAllPackageManifests
Pins the version of the `operator-lifecycle-manager` library to v0.30.0.  Updates to the `github.com/openshift/api` library to latest as well.  For some reason, if you try to update the openshift/api library by itself, it downgrades the olm library to v0.27.0 without explanation.

Catalogsource unit testing

---

tests/networking/suite.go

If a pod does not have any listening ports, that should be considered a `compliant` object.
I'm not sure if this will break any of the QE tests so we will see if anything comes back broken.

Add compliant object for listening port test

---

.github/workflows/qe-ocp-hosted.yml

This was adding too many jobs to our 20 slot free tier runners.

Remove 'main' push trigger from CRC YAML

---

pkg/certsuite/certsuite.go

Only delete the tarball if `OmitArtifactsZipFile` is set.

Fix tarball deletion logic

---

pkg/certsuite/certsuite.go

Stop printing the key to the execution log.

Remove APIKey from execution log

---

tests/accesscontrol/suite.go

The check was incorrectly testing the presence of the capability with the Capabilities.String(), which includes both add and drop ones, producing false negatives when the required capability is in the drop list.
This fix is the same as the one applied in PR #2352 for other access-control tcs.

Fix for test case access-control-sys-nice-realtime-capability.

---

.github/workflows/pre-main.yaml
.github/workflows/tnf-image.yaml
Dockerfile
Makefile

Most of the changes relate to having to download the correct version of the operator SDK binary to install in the image for preflight.
There are docker build variables like `TARGETARCH` that let you target architectures directly.
I suppose this is a disclaimer, but we have no way of actually _testing_ this change right now on those environments.
Builds on work done in:
- https://github.com/redhat-best-practices-for-k8s/privileged-daemonset/pull/247 
- https://github.com/redhat-best-practices-for-k8s/certsuite-probe/pull/16
- https://github.com/redhat-best-practices-for-k8s/oct/pull/269
- https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2736

Add support for PPC64LE and S390x image builds

---

pkg/certsuite/certsuite.go

Override env vars with cmdline flags if available.
Follow up to:
#2629 

connect api: override rhconnect vars from cmdline

---

pkg/provider/provider.go

#2736 switched this to `Always` pull but we should switch back until we can possibly make it a toggle via the config file.

Switch back to IfNotPresent pull policy

---

pkg/stringhelper/stringhelper_test.go

Adds a unit test for `HasAtLeastOneCommonElement()`.

stringhelper: add unit test for oneCommonElement

---

internal/clientsholder/clientsholder.go
pkg/podhelper/podhelper.go
pkg/podhelper/podhelper_test.go

Created two new test helper functions to help with spoofing the `DynamicClient` and `GroupResources` of the clientsholder struct:
- `SetTestK8sDynamicClientsHolder`
- `SetTestClientGroupResources`
It's only a test with a single case because we're already testing `followOwnerReferences()` but I think it gets the job done where I'm attempting to find the top owner of a pod owned by a deployment. 
Bonus: Added specific unit tests for function `SearchAPIResource` as well.

podhelper: add GetTopOwner unit tests

---

pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_nads.go
pkg/autodiscover/autodiscover_nads_test.go
pkg/autodiscover/autodiscover_operators.go
pkg/autodiscover/autodiscover_sriov.go

Break some functions from the `autodiscover.go` out to their own corresponding files.  No functional changes to these functions.
New files:
- autodiscover_nads.go
- autodiscover_sriov.go
Funcs moved:
- autodiscover_operators.go

Reorganize autodiscover files

---

tests/operator/openapi/openapi.go
tests/operator/openapi/openapi_test.go
tests/operator/suite.go

Breaks logic for this test out into `IsCRDDefinedWithOpenAPI3Schema` function with corresponding unit tests.

operator: add openAPI3 schema unit tests

---

tests/operator/helper.go
tests/operator/helper_test.go
tests/operator/suite.go

Created `OperatorInstalledMoreThanOnce` helper function and corresponding unit tests for the logic for the 'same-operators' test.

operator: add same operator unit tests

---

tests/operator/access/access.go
tests/operator/access/access_test.go
tests/operator/suite.go

Broke the logic out from the test to its own func called `PermissionsHaveBadRule` and wrote some unit tests around it.

operator: add scc permissions unit tests

---

.github/workflows/qe-ocp-arm-416.yaml
.github/workflows/qe-ocp-pre-main.yaml

I removed the "disable-self-hosted" label from PR #2763 but the pre-main self-hosted workflow jobs didn't run.
As suggested in github docs, the way to trigger the workflow when a label is added removed is using pull_request's activity types.
We did this in the [do-not-merge workflow file](https://github.com/redhat-best-practices-for-k8s/certsuite/blob/main/.github/workflows/do-not-merge.yaml#L5) and it works well there.
See
https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#label
"If you want to run your workflow when a label is added to or removed from an issue, pull request, or discussion, use the labeled or unlabeled activity types for the issues, pull_request, pull_request_target, or discussion events instead."

Fix to disable/enable pre-main self-hosted workflows.

---

expected_results.yaml
pkg/testhelper/testhelper.go
tests/accesscontrol/suite.go

There's no point in running this check if there isn't any node using realtime kernel, so I added a custom skip function for it.
Anyway, if nodes with realtime kernel exist, it's still possible/compliant to deploy workload pods in non-realtime kernel nodes, irrespective of the sys_nice cap. For pods deployed in realtime kernel nodes, it's mandatory for this cap to be set at container level.

Skip access-control-sys-nice-realtime-capability if there's no nodes using realtime kernel.

---

.github/workflows/pre-main.yaml
cmd/certsuite/run/run.go
docs/runtime-env.md
version.json

https://github.com/redhat-best-practices-for-k8s/certsuite-probe/releases/tag/v0.0.14
Looks like the `debugTag` value was missed in one of our last updates so that gets moved from `v0.0.12` to `v0.0.14`.

Update probe to v0.0.14

---

.github/actions/setup-partner-cluster/action.yml
.github/workflows/pre-main.yaml
.github/workflows/qe-hosted-arm.yml

https://github.blog/changelog/2025-01-16-linux-arm64-hosted-runners-now-available-for-free-in-public-repositories-public-preview/
`ubuntu-22.04-arm` runners are now available.  Checking to see what breaks if we run our workflows against them.

Experiment with arm64 free tier runners

---

.github/workflows/pre-main.yaml

Adding the `os` to the name of the file uploaded at the end of the Smoke Test runs.

Add OS to tarball artifact name

---

expected_results.yaml
pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_clusteroperators.go
pkg/autodiscover/autodiscover_clusteroperators_test.go
pkg/provider/provider.go
pkg/testhelper/testhelper.go
tests/identifiers/doclinks.go
tests/identifiers/identifiers.go
tests/identifiers/remediation.go
tests/platform/clusteroperator/clusteroperator.go
tests/platform/clusteroperator/clusteroperator_test.go
tests/platform/suite.go

Adds a new test named `cluster-operator-health` to the `platform-alteration` suite that does a simple Availability check for all of the cluster operators.  To pass this test, they all need to be `Available: True`.  If operators are in a `Progressing`, `Degraded`, or any other state, it will not be a compliant object.
This only runs on OCP clusters and will skip on Kubernetes clusters.

platform-alteration: add test for cluster operator health

---

pkg/testhelper/testhelper.go

This message corresponds to the probe not running correctly.  In logs, this needs more context for users.
Current message:

Add additional context when probe fails

---

.github/dependabot.yml

There are alot of PR's from this repo on a daily basis that create alot of noise. Switching to weekly, and grouping the go dependencies into one PR should cut down on the noise.
- Setting interval to `weekly` instead of `daily`.
- Adding `groups` field to `gomod` dependencies.

updating dependabot config to be weekly and group go dependencies

---

.github/actions/setup/action.yml
.github/workflows/codeql-analysis.yml
.github/workflows/merge.yaml
.github/workflows/pre-main.yaml
.github/workflows/preflight.yml
.github/workflows/update-rhcos-mapping.yml
.github/workflows/upload-release-assets.yaml
Dockerfile
go.mod
internal/clientsholder/command.go
internal/results/archiver.go
pkg/provider/containers.go
pkg/provider/operators.go
tests/accesscontrol/suite.go
tests/lifecycle/suite.go
tests/operator/suite.go
tests/platform/hugepages/hugepages.go

https://go.dev/doc/go1.24
Changes:
- Using `go-version-file` option thanks to @acornett21 
- Go 1.24.x now complains if you don't properly format your strings so this is now fixed.

Update Go to v1.24.0

---

CATALOG.md
tests/identifiers/identifiers.go

The Following test case `single-or-multi-namespaced-allowed-in-tenant-namespaces` is only mandatory in the extended scenario. Updated the catalog to reflect this.
Catalog updated also picked up the latest testcase

Making Operator tenant test case optional

---

.github/workflows/qe-ocp-hosted.yml

https://github.com/palmsoftware/quick-ocp/releases/tag/v0.0.5 has a new feature that enables caching and speeds up runs.

Enable bundle cache for OCP nightlies

---

.github/workflows/merge.yaml

This checkout should happen before `Set up Go`.

Fix 'merge.yaml' checkout

---

.github/workflows/codeql-analysis.yml
.github/workflows/preflight.yml
.github/workflows/qe-hosted-arm.yml
.github/workflows/qe-hosted.yml
.github/workflows/qe-ocp-414-intrusive.yaml
.github/workflows/qe-ocp-414.yaml
.github/workflows/qe-ocp-415-intrusive.yaml
.github/workflows/qe-ocp-415.yaml
.github/workflows/qe-ocp-416-intrusive.yaml
.github/workflows/qe-ocp-416.yaml
.github/workflows/qe-ocp-417-intrusive.yaml
.github/workflows/qe-ocp-417.yaml
.github/workflows/qe-ocp-arm-416.yaml
.github/workflows/qe-ocp-hosted.yml
.github/workflows/scorecard.yml
.github/workflows/tnf-image.yaml
.github/workflows/update-rhcos-mapping.yml

Related to: https://github.com/openshift-kni/eco-goinfra/pull/961
We had a discussion in the eco-go* maintainers meeting about preventing forks from running the crons that were in the github YAMLs.  This should do the trick here too.

ci: prevent forks from running nightly crons

---

script/rekick-failed-workflows.sh

Quick script for kicking recently failed jobs via the `gh` command line tool.

script: add scripting for rekicking failed jobs

---

.github/workflows/pre-main.yaml
.golangci.yml
Makefile
cmd/certsuite/claim/show/csv/csv.go
internal/clientsholder/clientsholder.go
pkg/autodiscover/autodiscover_operators.go
pkg/autodiscover/autodiscover_pods.go
pkg/autodiscover/autodiscover_podset.go
pkg/podhelper/podhelper_test.go
pkg/provider/containers.go
pkg/provider/isolation.go
pkg/provider/operators.go
pkg/provider/pods.go
pkg/provider/provider.go
pkg/provider/statefulsets_test.go
tests/accesscontrol/suite.go
tests/lifecycle/scaling/deployment_scaling_test.go
tests/lifecycle/tolerations/tolerations.go
tests/observability/suite.go

https://golangci-lint.run/product/migration-guide/
I migrated the config over to their `v2` style with the `migrate` command.  Also I fixed a number of things it started flagging.

golangci-lint: migration to v2

---

.github/dependabot.yml

https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference
Utilize some more granular group options for these updates.

dependabot config: modify groups

---

.github/dependabot.yml

Follow up to #2878 
Trying to figure out why these aren't grouping together correctly.  Max PRs open is now set to 3.

dependabot config: additional options

---

.github/dependabot.yml

More tweaks, trying to get it nailed down.
- Add `other-go-modules` group to group everything that isn't related to k8s.io or rhbp4k8s.
- Create `docker-images` group to group anything docker related either in our Dockerfile or in the docs dockerfile.

Additional groupings

---

.github/dependabot.yml

The updater seems to be throwing this message:
```
updater | 2025/03/28 15:45:54 WARN <job_988588101> Please check your configuration as there are groups where no dependencies match:
- docker-images
```

Remove UBI patterns

---

.github/dependabot.yml

Related to: https://github.com/dependabot/dependabot-core/issues/6704
Turns out that there are dependencies under `.github/actions/` that aren't being updated like the others and they need their own specific group.

Add grouping for 'actions' folder specifically

---

.github/actions/slack-webhook-sender/action.yml

Removing the protocol in the url should avoid slack to create the link previews.
Ref: https://slack.com/help/articles/204399343-Share-links-and-set-preview-preferences#:~:text=Turn%20off%20link%20previews&text=Select%20Preferences%20from%20the%20menu,text%20previews%20of%20linked%20websites.

Avoid URL previews in slack msgs for alerts.

---

CATALOG.md
tests/identifiers/exceptions.go
tests/identifiers/identifiers.go

Change the exception process and description in the catalog for the access-control-requests-and-limits test.
TestDallasWorkload: tnf-test-cnf-green

Adjust exception process for requests-and-limits test

---

docs/cluster-deploy/README.md
docs/cluster-deploy/certsuite.yaml
docs/cluster-deploy/kustomization.yaml

Kustomize sections updated to use "certsuite run" instead of certsuite.sh.
Also:
- Configmap field name updated for extension 'yml' instead of 'yaml'. Also, the content has been updated to match config/certsuite_config.yml
- By default, the certsuite will add the intrusive=false to avoid intrusive test cases. The kustomize (commented) section was updated to remove it completely so they can run if needed/wanted.

Updates on cluster deploy kustomize and README

---

docs/cluster-deploy/README.md
docs/cluster-deploy/certsuite.yaml
docs/cluster-deploy/kustomization.yaml
docs/test-run.md

A follow up to the below, where it was pointed out the docs should be updated, since it wasn't clear that for a container the binary was in $PATH.
- #2903
Remove references to `./` in the `test-run` page. It still makes sense to keep this in the developer pages/guide.

update test run docs to remove ./ for clarity

---

Dockerfile

When trying to figure out where the `certsuite` binary lived in the container, I noticed the `tree` output, had the binary duplicated in two places within the `/usr` location.
Fix the duplication, and remove the folders in `/usr/local/bin`, creating a flat directory of all binaries.

fix bin directory to no longer have folders and duplicate binaries

---

.github/workflows/update-rhcos-mapping.yml

The RHCOP map job was failing:
https://github.com/redhat-best-practices-for-k8s/certsuite/actions/runs/14721502972/job/41316072020#step:3:293
This change adds a check to install the `oc` client if missing.  
It's failing because the new change to the ubuntu-24.04 runners don't have the openshift-cli installed by default anymore for some reason.

script: Add check for 'oc' client

---

.github/workflows/update-rhcos-mapping.yml
script/rhcos_versions.sh

Follow up to #2939 
* [`.github/workflows/update-rhcos-mapping.yml`](diffhunk://#diff-2d1a584ee822c30599041287a454454f095a481b9b36b4ca1245ef0c672a2cb9L32-R39): Updated the installation script for the `oc` CLI to use a temporary directory for downloading and extracting files, ensuring better cleanup and avoiding potential conflicts for the README.md.
* [`script/rhcos_versions.sh`](diffhunk://#diff-3dea480ebe3843b10c2201ee2d777ff376105b6f9fc88429e3542d65f86cc656L5-R5): Added support for OpenShift channels `4.20` and `4.19` to the `CHANNELS` array.

Further updates to RHCOS job; add 4.19 and 4.20

---

.github/workflows/qe-ocp-418-intrusive.yaml
.github/workflows/qe-ocp-418.yaml

Adds a nightly QE runs for 4.18.  Instead of using a self-hosted runner, we're using the [new functionality](https://github.com/palmsoftware/quick-ocp/pull/13) in `quick-ocp` where we can specify certain OCP versions using the `desiredOCPVersion` flag.

nightly: add 4.18 QE runs

---

.github/workflows/qe-ocp-418-intrusive.yaml
.github/workflows/qe-ocp-418.yaml

This pull request introduces a cleanup step in two GitHub Actions workflows to optimize disk space usage by removing Docker images after they are no longer needed. 
Enhancements to workflows:
* [`.github/workflows/qe-ocp-418-intrusive.yaml`](diffhunk://#diff-6f51a6efe331a185a86bf75986d3b9fa18a340a00080a4d075469d6719f5739aR121-R124): Added a step to clean up Docker images (`TEST_CERTSUITE_IMAGE_NAME` and `TEST_CERTSUITE_IMAGE_TAG`) before the next job runs, ensuring efficient use of disk space.
* [`.github/workflows/qe-ocp-418.yaml`](diffhunk://#diff-c08ac0e5886c9b068215f1837fb2a43f2aaafa9594d22dadb6edea3ca9944ff7R120-R123): Added a similar cleanup step to remove Docker images after testing, preventing unnecessary disk space consumption.

Cleanup images in 4.18 runs

---

.github/workflows/qe-ocp-418-intrusive.yaml
.github/workflows/qe-ocp-418.yaml

Follow up to #3031 
Run an additional system prune to just make sure there is nothing leftover and we can save as much space as possible.

418 nightly: additional system prune

---

.github/workflows/qe-ocp-419-intrusive.yaml
.github/workflows/qe-ocp-419.yaml
script/rekick-failed-workflows.sh

OCP 4.19 is [now available](https://docs.redhat.com/en/documentation/openshift_container_platform/4.19/html/release_notes/index) and `quick-ocp` is [now supporting](https://github.com/palmsoftware/quick-ocp/pull/20) 4.19 as well.  
Creating explicit 4.19 YAMLs for testing nightly.

Add nightly 4.19 QE testing

---

Dockerfile

https://github.com/operator-framework/operator-sdk/releases/tag/v1.41.1
Related to:
- https://github.com/redhat-best-practices-for-k8s/certsuite-sample-workload/pull/575

Update operator-sdk to v1.41.1

---

.github/workflows/pre-main.yaml
cmd/certsuite/run/run.go
docs/runtime-env.md
version.json

https://github.com/redhat-best-practices-for-k8s/certsuite-probe/releases/tag/v0.0.19

Update probe to v0.0.19

---

cmd/certsuite/pkg/claim/claim_test.go
go.mod
go.sum
pkg/provider/catalogsources.go
pkg/versions/versions.go
tests/observability/suite.go
tests/operator/suite.go

https://github.com/Masterminds/semver/releases/tag/v3.4.0
Removes the extra `v1.5.0` library that we were somehow including and causing confusion.  Standardizes on the `v3` version of semver.

Update and consolidate semver library

---

.github/workflows/pre-main.yaml
cmd/certsuite/run/run.go
docs/runtime-env.md
version.json

https://github.com/redhat-best-practices-for-k8s/certsuite-probe/releases/tag/v0.0.20

Update probe to v0.0.20

---

pkg/autodiscover/autodiscover.go
pkg/autodiscover/autodiscover_pods.go
pkg/autodiscover/autodiscover_pods_test.go
pkg/autodiscover/autodiscover_test.go
pkg/certsuite/certsuite.go
pkg/claimhelper/claimhelper.go
pkg/claimhelper/claimhelper_test.go
pkg/provider/provider.go

- Created a new `PodStates` struct in the `env`, this is unstructured, but could be switched to exact `Phases` if we feel we want to keep track of all phases
- I don't love the unstructured nature, but wasn't sure how granular we wanted to be. 
- Add logic to compare before/after `ready` states and log the diff
- Updated `NewClaimBuilder` to take in an `env` so that this can be modified, since `env` by nature is a singleton.
- Exported various methods that needed to be called outside of the `autodiscover` pkg.
Below is the output of the `claim.json` with this. 
```json
❯ cat results/claim.json | jq .claim.configurations.podStates
{
"AfterExecution": {
"non-ready": 0,
"ready": 2
},
"BeforeExecution": {
"non-ready": 0,
"ready": 3
}
}
```
Below is the sample log file (though it seems to only …

adding a new PodStates struct to env for ready/non-ready pod comparison

---

.github/workflows/update-dashboard.yml

The nightlies dashboard workflow was failing at the commit step due to protected branch restrictions:
```
remote: error: GH006: Protected branch update failed
remote: - Changes must be made through a pull request
```
- Replace direct commit to `main` with `peaceiris/actions-gh-pages@v4`
- Deploy to `nightlies/` subdirectory to avoid overwriting existing docs
- Use standard GitHub Pages deployment approach
- Bypasses protected branch restrictions
- Dashboard will deploy to `gh-pages` branch properly
- Available at https://redhat-best-practices-for-k8s.github.io/certsuite/nightlies/
- Fixes the protected branch deployment issue from the previous run
- Completes the fix started in PR #3121
- Enables automated nightlies dashboard updates

Fix dashboard deployment to use gh-pages branch

---

README.md

```
$ make markdownlint 
markdownlint '**/*.md'
README.md:27 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 2]
README.md:28 MD012/no-multiple-blanks Multiple consecutive blank lines [Expected: 1; Actual: 3]
make: *** [markdownlint] Error 1
```

Fix markdownlint errors

---

CATALOG.md
README.md
expected_results.yaml
tests/accesscontrol/resources/resources.go
tests/accesscontrol/resources/resources_test.go
tests/accesscontrol/suite.go
tests/identifiers/doclinks.go
tests/identifiers/exceptions.go
tests/identifiers/identifiers.go
tests/identifiers/impact.go
tests/identifiers/remediation.go

Removes the `limits` from the original `requests-and-limits` test as we are no longer going to be enforcing the check for limits.  This has been a controversial check and will be "smoother" with it removed.

Remove 'limits' from requests-and-limits test

---

internal/results/rhconnect.go
pkg/checksdb/checksdb.go
pkg/collector/collector.go

This pull request introduces a timeout for HTTP client requests when uploading claim files to the collector, improving reliability and preventing potential hangs during network issues.
Reliability improvements:
* Added a 30-second timeout to the `http.Client` used in `SendClaimFileToCollector` to ensure uploads do not hang indefinitely.
* Imported the `time` package in `pkg/collector/collector.go` to support the new timeout functionality.

Add 30 second timeout to collector request

---

.github/workflows/qe-hosted-arm.yml
.github/workflows/qe-hosted.yml

I noticed that the qe-hosted-arm.yml was failing over and over because the testimage.tar was not available.  That's because the `Setup partner cluster` step was modifying the docker install under the covers and the image was no longer available.
**Workflow optimization and artifact management:**
* Added a new `build-binary-for-qe` job in `.github/workflows/qe-hosted.yml` to build the `certsuite` binary once and upload it as an artifact, reducing redundant builds in each QE suite.
* Updated the `qe-testing` job to depend on both the image and binary build jobs, ensuring tests only run if both artifacts are available.
* Added steps in the `qe-testing` job to download the binary artifact and make it executable, but only during scheduled runs.
* Removed the redundant step that built the …

Adjust hosted QE runs for efficiency

---

.github/workflows/pre-main.yaml
cmd/certsuite/run/run.go
docs/runtime-env.md
version.json

https://github.com/redhat-best-practices-for-k8s/certsuite-probe/releases/tag/v0.0.24

Update probe to v0.0.24

---

pkg/provider/pods.go
pkg/provider/provider.go

In the autodiscover step, we were seeing logs like:
```
[ERROR] [Aug 11 13:59:35.951] [pods.go: 68] Could not get PCIs for Pod "networkingputa-55774dd985-6b5ks" (namespace "networking-tests-cybnlyllme"), err: could not unmarshal network-status annotation, err: unexpected end of JSON input
```
This was caused because we are specifically looking for `"k8s.v1.cni.cncf.io/network-status"` annotations on pods.  I'm adding some safeguards to make the process more readable and "safer" with an empty string check.
New logs look like:
```
[INFO] [Aug 11 14:49:14.821] [pods.go: 69] Pod "networkingputa-566559c666-n99kj" (namespace "networking-tests-exwmmpfwvk") missing or empty annotation "k8s.v1.cni.cncf.io/network-status". Present annotations: [openshift.io/scc k8s.ovn.org/pod-networks …
```

Multus annotation safeguards

---

.github/workflows/qe-ocp-418-intrusive.yaml
.github/workflows/qe-ocp-418.yaml
.github/workflows/qe-ocp-419-intrusive.yaml
.github/workflows/qe-ocp-419.yaml

Temporarily commenting out the image runs due to memory constraints in the runner VMs.  Something seems to have changed upstream that's now giving us less memory to work with.

Disable 'image' runs from nightlies

---

.github/workflows/pre-main.yaml
cmd/certsuite/run/run.go
docs/runtime-env.md
version.json

https://github.com/redhat-best-practices-for-k8s/certsuite-probe/releases/tag/v0.0.25

Update probe to v0.0.25

---

.github/workflows/probe-update.yaml

Similar to other workflows that look at releases that I use:
- https://github.com/palmsoftware/quick-k8s/blob/main/.github/workflows/calico-update.yml
- https://github.com/palmsoftware/quick-k8s/blob/main/.github/workflows/olm-update.yml
This will check for new probe versions and make the appropriate `sed` replaces.

Add probe update workflow

---

.github/workflows/pre-main.yaml
.github/workflows/probe-update.yaml

Because of permissions problems, I modified the `pre-main.yml` to just grab the debugTag variable from version.json instead so the update job doesn't have to modify another workflow.

Modify precheck images job

---

Dockerfile

We're getting this error from time to time due to transient dependency mistmatches in official repositories:
```
$ docker run
registry.access.redhat.com/ubi9/ubi:9.6@sha256:8f1496d50a66e41433031bf5bdedd4635520e692ccd76ffcb649cf9d30d669af dnf update --assumeyes --disableplugin=subscription-manager 
Red Hat Universal Base Image 9 (RPMs) - BaseOS  1.1 MB/s | 588 kB 00:00
Red Hat Universal Base Image 9 (RPMs) - AppStre 4.3 MB/s | 2.4 MB 00:00
Red Hat Universal Base Image 9 (RPMs) - CodeRea 555 kB/s | 287 kB 00:00
Error:
Problem: The operation would result in removing the following protected
packages: systemd
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
``` …

Dockerfile: add --nobest for dnf update.

---

tests/lifecycle/podrecreation/podrecreation.go

In Go 1.25 (#3176) they introduced a simpler way to spawn goroutines instead of the usual `wg.Add(1)` line.  All you need is `wg.Go(func(){})`
https://tip.golang.org/doc/go1.25

Simplify WaitGroup for Go 1.25

---

.github/workflows/qe-ocp-414-intrusive.yaml
.github/workflows/qe-ocp-414.yaml
.github/workflows/qe-ocp-415-intrusive.yaml
.github/workflows/qe-ocp-415.yaml
.github/workflows/qe-ocp-416-intrusive.yaml
.github/workflows/qe-ocp-416.yaml
.github/workflows/qe-ocp-417-intrusive.yaml
.github/workflows/qe-ocp-417.yaml

This pull request updates the GitHub Actions workflows for OCP 414, 415, 416, and 417 (both intrusive and non-intrusive variants) to use the `${{ runner.temp }}` directory for storing and loading Docker image artifacts instead of the fixed `/tmp` path. This change improves portability and reliability across different runner environments.
**Workflow improvements:**
* Changed the Docker build output destination from `/tmp/testimage.tar` to `${{ runner.temp }}/testimage-<version>.tar` in all relevant workflow files, ensuring the use of the runner's temporary directory. [[1]](diffhunk://#diff-7c7a796d8d04f13a7219994504949f30901f04632757c1850c40ef4d76fd6354L40-R40) [[2]](diffhunk://#diff-9499a4a976b22ea2752cd9cf3932bbe0db259aa38974b1eccb7e3cbf614d8c89L40-R40) …

Fix /tmp permissions for self-hosted
