redhat-best-practices-for-k8s/certsuite

- internal/ocpclient/command.go
This is a backport of the fix in the IPv4/v6 testcases to attempt to fix current issues
> fix ExecCommandContainer for github

- Makefile
- README.md
https://github.com/golangci/golangci-lint/releases/tag/v1.44.2
> Upgrade GolangCI-lint to v1.44.2

- CATALOG.md
- cnf-certification-test/accesscontrol/suite.go
- cnf-certification-test/identifiers/identifiers.go
- cnf-certification-test/lifecycle/scaling/scaling.go
- cnf-certification-test/lifecycle/scaling/scaling_test.go
- cnf-certification-test/lifecycle/suite.go
- cnf-certification-test/networking/suite.go
- cnf-certification-test/observability/suite.go
- cnf-certification-test/operator/suite.go
- cnf-certification-test/platform/suite.go
- go.mod
- pkg/autodiscover/autodiscover.go
- pkg/autodiscover/autodiscover_pods.go
- pkg/autodiscover/autodiscover_podset.go
- pkg/autodiscover/autodiscover_podset_test.go
- pkg/provider/provider.go
- script/create-missing-test-files.sh
Add statefulset autodiscovery
Add HPA autodiscovery
Add deployment autoscaling without HPA
Add deployment autoscaling with HPA
> Add deployments autodiscovery

- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
https://groups.google.com/g/golang-announce/c/RP1hfrBYVuk/m/I7ouYouLAAAJ
Similar to:
- https://github.com/test-network-function/cnfcert-tests-verification/pull/47
- https://github.com/test-network-function/test-network-function/pull/643
- https://github.com/test-network-function/cnf-certification-test-partner/pull/88
- https://github.com/test-network-function/test-network-function-claim/pull/39
> Update Go to 1.17.8

- cnf-certification-test/platform/isredhat/isredhat.go
- cnf-certification-test/platform/isredhat/isredhat_test.go
- cnf-certification-test/platform/suite.go
Adds the `isRedHatRelease` test to the new test suite.
> Add isRedHat test

- cnf-certification-test/accesscontrol/namespace/namespace.go
- cnf-certification-test/accesscontrol/suite.go
- cnf-certification-test/lifecycle/scaling/scaling.go
- cnf-certification-test/observability/suite.go
- cnf-certification-test/operator/suite.go
- cnf-certification-test/platform/suite.go
- internal/clientsholder/clientsholder.go
- internal/crclient/crclient.go
- pkg/autodiscover/autodiscover.go
- pkg/autodiscover/autodiscover_crds.go
- pkg/provider/provider.go
As a singleton, the "NewClientsHolder" function name was a bit
misleading, since it will only return a new struct the first time it's
called.
> Added Get function to get the clientsholder's singleton.

- README.md
- run-cnf-suites.sh
Implementation taken from PR#571 (test-network-function repo)
> run-cnf-suites.sh: add filtering by label option

- cnf-certification-test/lifecycle/graceperiod/graceperiod.go
- cnf-certification-test/lifecycle/podsets/podsets.go
- cnf-certification-test/lifecycle/suite.go
- pkg/provider/provider.go
SatetfulSets --> StatetfulSets
> Correcting some typos

- cnf-certification-test/networking/suite.go
Testing services in namespace.
> TestNodePort

- cnf-certification-test/lifecycle/ownerreference/ownerreference_test.go
This file is now covered with `100.0% of statements`.
> Add tests for ownerreference package

- pkg/testhelper/testhelper_test.go
Brings this file to `coverage: 100.0% of statements`.
> Add tests for 'testhelper' package

- cnf-certification-test/networking/declaredandlistening/declaredandlistening.go
- cnf-certification-test/networking/declaredandlistening_test.go
> Solution for issue on Nokia

- cnf-certification-test/operator/suite.go
`priviledges` --> `privileges`
> Quick typo fix

- pkg/autodiscover/autodiscover_pods.go
- pkg/autodiscover/autodiscover_pods_test.go
Brings the autodiscover_pods.go file to 81.8% coverage.
> Add tests for autodiscover_pods

- cnf-certification-test/lifecycle/podrecreation/podrecreation.go
> removing uneeded sleep - missed from PR review

- cnf-certification-test/lifecycle/podrecreation/podrecreation.go
- pkg/autodiscover/autodiscover_podset.go
#150 missed some additional places where we could inline some more Options{} structs.
> More inlining

- pkg/autodiscover/autodiscover_pods.go
Filters out pods that:
- Are not in a running state
- Have a DeletionTimestamp set
> Add a pod status filter to the findPodsByLabel() function

- README.md
#143 missed the actual title of the repo itself.  😅 
EDIT: Bonus!  🎉 
I added a couple more badges for our repo!  Godoc and a LICENSE badge.
> Change the README title and more!

- cnf-certification-test/platform/suite.go
> fix selinux testcase

- cnf-certification-test/certification/suite.go
- cnf-certification-test/lifecycle/suite.go
The diff makes this look more complicated than it is.  All I am doing is moving the:
```
testID := identifiers.XformToGinkgoItIdentifier(identifiers.XXX)
ginkgo.It(testID, ginkgo.Label(Online, testID), func() {
```
To wrap the calling functions like it is done in other test suites.  I also moved the `testhelper` skip checks out of the func if applicable.
> Make suite.go more consistent

- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/tnf-image.yaml
- .github/workflows/update-certification.yml
https://github.com/actions/checkout/releases/tag/v3.0.2
`checkout` v3 is the latest available.
> Upgrade to v3 checkout action

- CATALOG.md
- cnf-certification-test/identifiers/identifiers.go
Update test case catalog with Best Practices v1.3 references
> Update test case catalog with Best Practices v1.3 references

- cnf-certification-test/identifiers/identifiers.go
- cnf-certification-test/lifecycle/suite.go
> Shudtown typo

- internal/api/offlinecheck/container.go
- internal/api/offlinecheck/helm.go
- internal/api/offlinecheck/operator.go
- internal/api/onlinecheck/onlinecheck.go
- internal/clientsholder/clientsholder.go
- internal/crclient/crclient.go
- pkg/autodiscover/autodiscover.go
- pkg/autodiscover/autodiscover_podset.go
- pkg/provider/provider_test.go
Fix some more contractions in the logs/comments of the code.
* Can't --> Cannot
* Didn't --> Did not
* Won't --> Will not
> Remove more contractions

- CATALOG.md
- cnf-certification-test/identifiers/identifiers.go
- cnf-certification-test/platform/suite.go
- pkg/autodiscover/autodiscover.go
- pkg/autodiscover/autodiscover_operators.go
Verifies if service mesh is exist by using in Istio.
> updated service mesh

- cnf-certification-test/networking/netcommons/netcommons_test.go
> Add netcommons tests

- .github/workflows/pre-main.yaml
https://github.com/actions/upload-artifact/releases/tag/v3.1.0
> Use upload-artifact v3

- pkg/provider/provider_test.go
> Fix provider tests

- Dockerfile
Copy the version map over to the image.  #327 missed doing this.
> Copy the RHCOS mapping file to image

- cnf-certification-test/chaostesting/pod_delete/pod_delete.go
- cnf-certification-test/chaostesting/pod_delete/pod_delete_test.go
- cnf-certification-test/chaostesting/suite.go
- Fixed some typos.
- Changed error strings.
- Added some unit tests surrounding `GetLabelDeploymentValue` and new func `parseLitmusResult`.
> Cleanup chaostesting; add tests

- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/update-certification.yml
- Dockerfile
Release notes: https://groups.google.com/g/golang-announce/c/nqrv9fbR0zE
Lots of fixes in this release.
> Update Go to 1.18.4

- CATALOG.md
- cnf-certification-test/identifiers/identifiers.go
- cnf-certification-test/identifiers/remediation.go
- cnf-certification-test/networking/suite.go
The ports reserved by Openshift are 22623 and 22624.
> networking: new test to check the usage of OCP reserved ports

- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/update-certification.yml
- Dockerfile
https://groups.google.com/g/golang-announce/c/YqYYG87xB10?pli=1
> Update Go to 1.18.5

- CATALOG.md
- cnf-certification-test/accesscontrol/suite.go
- cnf-certification-test/identifiers/identifiers.go
- cnf-certification-test/identifiers/remediation.go
- internal/clientsholder/clientsholder.go
- pkg/autodiscover/autodiscover.go
- pkg/autodiscover/autodiscover_resources.go
- pkg/autodiscover/autodiscover_resources_test.go
- pkg/provider/provider.go
Depends on #372 and https://github.com/test-network-function/cnf-certification-test-partner/pull/140
This is just a branch off of the #372 PR so I didn't have to wait for that to merge.
https://github.com/test-network-function/cnf-certification-test-partner/pull/140 needs to merge first so the CI starts passing because our test environment currently doesn't have a limit range set.
> Add namespace resource quota test

- CATALOG.md
- cnf-certification-test/identifiers/identifiers.go
Some easy changes to add capitalization where appropriate.
> Fix capitalization in the catalog

- go.mod
- go.sum
https://github.com/test-network-function/test-network-function-claim/releases/tag/v1.0.6
> Update -claim to v1.0.6

- .github/workflows/pre-main.yaml
- .github/workflows/update-certification.yml
- Makefile
https://github.com/test-network-function/cnf-certification-test/pull/469 missed this.
> Ginkgo v2.1.6 manual update

- pkg/stringhelper/stringhelper.go
`RemoveDuplicates` was unused.  Removing.
> Remove unused func

- internal/api/onlinecheck/onlinecheck_test.go
`ok  	github.com/test-network-function/cnf-certification-test/internal/api/onlinecheck	3.460s	coverage: 62.1% of statements`
> Add test for onlinecheck package

- cmd/tnf/fetch/fetch.go
This improvement tries to minimize the number of files changed for the offline catalog whenever new operators have been added as certified in the online catalog. The per-page information fields "total", "page_size", and "page" have been removed to avoid this change to appear in the automatic PR for all the pages:
Those fields can be removed as they're never used by the test case.
The "total" field will be shown only in the last page, just for debugging/reference.
> Fetch tool improvement to minimize changes in operator pages.

- cnf-certification-test/networking/policies/policies_test.go
Forgot to add these tests in #423
> Add test for LabelsMatch

- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/update-certification.yml
- Dockerfile
https://groups.google.com/g/golang-announce/c/x49AQzIVX-s
Similar changes:
- https://github.com/test-network-function/cnfcert-tests-verification/pull/132
- https://github.com/test-network-function/test-network-function-claim/pull/62
- https://github.com/test-network-function/l2discovery/pull/15
- https://github.com/test-network-function/privileged-daemonset/pull/7
- https://github.com/test-network-function/oct/pull/1
> Update Go to 1.18.6

- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/update-certification.yml
- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/x49AQzIVX-s
> Upgrade Go to v1.19.1

- .github/workflows/update-certification.yml
- .github/workflows/update-rhcos-mapping.yml
https://github.com/peter-evans/create-pull-request/releases/tag/v4.1.2
> Update 'create-pull-request' action

- .github/workflows/pre-main.yaml
- .github/workflows/tnf-image.yaml
https://docs.openshift.com/container-platform/4.11/release_notes/ocp-4-11-release-notes.html
> Bump RELEASE_LEVEL to 4.11

- cnf-certification-test/accesscontrol/suite.go
- cnf-certification-test/certification/suite.go
- cnf-certification-test/lifecycle/suite.go
- cnf-certification-test/manageability/suite.go
- cnf-certification-test/networking/suite.go
- cnf-certification-test/observability/suite.go
- cnf-certification-test/operator/suite.go
- cnf-certification-test/platform/suite.go
I didn't move _all_ of them over to the `AddTestResultLog` function, just some of them where it made sense.
What do you think about the loss of some of the context in the claim file output?
> Moved some more funcs over to AddTestResultLog

- pkg/provider/isolation.go
> fix typo in isolation.go

- cnf-certification-test/lifecycle/podsets/podsets.go
- cnf-certification-test/lifecycle/suite.go
- cnf-certification-test/observability/suite.go
- pkg/provider/provider.go
`StatetfulSets` --> `StatefulSets`
> Typo: StatetfulSets to StatefulSets

- .github/workflows/pre-main.yaml
- .github/workflows/update-certification.yml
- Makefile
#585 bumped the go.mod to 2.3.1, time to update the rest.
> Manual update of Ginkgo to 2.3.1

- cnf-certification-test/accesscontrol/resources/resources.go
- cnf-certification-test/accesscontrol/resources/resources_test.go
- cnf-certification-test/accesscontrol/suite.go
Improvements:
- Move the logic out of suite.go
- Created `resources` package and moved logic into it.  Created `resources_test.go` to house the unit tests.
- Instead of checking nil, check the value of the `Resources` objects.
> Fix requests and limits test

- .golangci.yml
- Makefile
- README.md
https://github.com/golangci/golangci-lint/releases/tag/v1.50.0
> Upgrade GolangCI-lint to v1.50.0

- pkg/provider/provider.go
Added warning traces in the autodiscovery process when pod's containers that are being stored in the target containers list are not ready/running yet.
> Warning trace if discovered container is not ready or not running

- cnf-certification-test/platform/nodetainted/nodetainted.go
- cnf-certification-test/platform/nodetainted/nodetainted_test.go
- cnf-certification-test/platform/suite.go
Add testing for nodetainted package.
- Remove `TaintedFuncs` interface, not needed anymore.  Adjust accordingly.
- Change `runCommand` to be a var for easier unit test spoofing.
- `NewNodeTaintedTester` accepts a context object to pass around, not the client itself.
- Unit tests added, bringing the package coverage up to 82.4%.
> Consolidate nodetainted and add testing

- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/update-certification.yml
- Dockerfile
https://groups.google.com/g/golang-announce/c/mbHY1UY3BaM?pli=1
> Update Go to v1.19.3

- cnf-certification-test/identifiers/identifiers.go
Building upon #631 
Adds some default values while running `AddCatalogEntry`.
> Add default values for catalog entries

- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.1.0
> Bump partner version to v4.1.0 in prep for release

- docs/reference.md
- docs/runtime-env.md
- docs/test-output.md
I also added a link to the v1.3 document in the References section.
> Add which files to collect for certification to README

- pkg/provider/operators.go
- pkg/provider/provider.go
> Move more operator-related items

- .github/workflows/pre-main.yaml
- .github/workflows/update-certification.yml
- Makefile
> Manually update Ginkgo to v2.5.0

- pkg/provider/provider.go
- pkg/provider/provider_test.go
#621 missed removing these funcs.  The privileged daemonset library handles all of this now.
> Remove WaitForDebugDaemonset funcs

- pkg/stringhelper/stringhelper.go
- pkg/stringhelper/stringhelper_test.go
Modify StringInSlice to work with all string types
> Change StringInSlice to work with any string based type

- cnf-certification-test/certification/certtool/certtool_test.go
coverage: 31.8% of statements up from 0.0%
> Add tests to certtool package

- cnf-certification-test/identifiers/identifiers.go
> Removed unused scaling test case identifier.

- cnf-certification-test/networking/netutil/netutil.go
- cnf-certification-test/networking/netutil/netutil_test.go
According to https://bugzilla.redhat.com/show_bug.cgi?id=1512550 chain counters might be non-zero even without "-c" option for iptables-save. Zeroing iptables chain counters before making comparison for whitlisting.
This is to address https://github.com/test-network-function/cnf-certification-test/issues/676
> Zeroing iptables chains counters before comparing

- cnf-certification-test/manageability/suite.go
- cnf-certification-test/tnf_config.yml
- docs/configuration.md
- pkg/autodiscover/autodiscover.go
- pkg/configuration/configuration.go
- pkg/configuration/testdata/tnf_test_config.yml
- pkg/provider/provider.go
Adding new protocol name to the map ("allowedProtocolNames").
> Make prefixes list for the port names check to be configurable

- CATALOG.md
- cmd/tnf/addclaim/addclaim_test.go
- cnf-certification-test/identifiers/identifiers.go
Thanks to @mwlinca for pointing these out.
> Fix minor typos

- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- Dockerfile
https://groups.google.com/g/golang-announce/c/L_3rmdT0BMU
> Update Go to v1.19.4

- docs/test-container.md
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.1.2
> Update version to v4.1.2

- docs/configuration.md
#635 added the feature but didn't add the documentation.  This provides a note and an example in the doc for this feature.
> Add documentation section for skipScaling config

- pkg/provider/pods.go
- pkg/provider/provider.go
Related to #672 
Check if the pods is created by Openshift's DeploymentConfig resources.
> Detect pods created by Openshift's DeploymentConfig resources

- .github/workflows/pre-main.yaml
- Makefile
#735 was the dependabot PR that updated ginkgo in the go.mod.
> Manually update Ginkgo to v2.6.0 to match go.mod

- docs/test-standalone.md
Adds a note about running all of the tests, common and extended.
> Add doc section about running all of the tests at once

- cnf-certification-test/identifiers/identifiers.go
- cnf-certification-test/identifiers/remediation.go
- cnf-certification-test/lifecycle/suite.go
Check if when kind equal to StatesfulSet, the service name is not local storage.
> PODs must NOT place persistent volumes on local storage

- CATALOG.md
All I did was `make build-catalog-md` to bring this up to speed.  Looks like I forgot to update this in #750.
> Update the CATALOG

- CATALOG.md
- cnf-certification-test/identifiers/exceptions.go
- cnf-certification-test/identifiers/identifiers.go
> Fix some typos in CATALOG

- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- Dockerfile
https://groups.google.com/g/golang-announce/c/wrmRT7JlevE
> Update Go to v1.19.5

- CATALOG.md
- cnf-certification-test/identifiers/identifiers.go
- go.mod
- go.sum
Also added missing value to storage-required-pods entry, re-generated CATALOG.md
> Added qe variable to catalog entries

- pkg/provider/containers_test.go
Related to similar changes in: #177 and #618
> Import naming convention fix

- cmd/tnf/addclaim/compareclaim.go
- cnf-certification-test/accesscontrol/pidshelper.go
- cnf-certification-test/accesscontrol/pidshelper_test.go
- cnf-certification-test/chaostesting/suite.go
- cnf-certification-test/lifecycle/podrecreation/podrecreation.go
- cnf-certification-test/lifecycle/scaling/deployment_scaling.go
- cnf-certification-test/lifecycle/scaling/statefulset_scaling.go
- cnf-certification-test/networking/services/services.go
- cnf-certification-test/platform/cnffsdiff/fsdiff.go
- cnf-certification-test/platform/isredhat/isredhat.go
- cnf-certification-test/platform/nodetainted/nodetainted.go
- cnf-certification-test/platform/suite.go
- pkg/provider/provider.go
- Fixed some typos.
- Optimized some return statements.
- Removed some english contractions similar to #264
> Some typos and optimizations

- .github/workflows/pre-main.yaml
Just some comment changes to remove the references to minikube.
> Remove references to minikube in favor of Kind

- .golangci.yml
- Makefile
- docs/test-standalone.md
- pkg/provider/provider.go
https://github.com/golangci/golangci-lint/releases/tag/v1.51.0
> Update GolangCI to v1.51.0

- pkg/provider/statefulsets_test.go
Just an additional test for `IsStatefulSetReady` func.
> Add additional StatefulSet unit tests

- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- Dockerfile
- docs/test-standalone.md
Release Notes: https://tip.golang.org/doc/go1.20
> Upgrade Go to v1.20.1

- CATALOG.md
- cnf-certification-test/identifiers/identifiers.go
- cnf-certification-test/identifiers/remediation.go
- cnf-certification-test/lifecycle/podsets/podsets.go
- cnf-certification-test/lifecycle/scaling/crd_scaling.go
- cnf-certification-test/lifecycle/scaling/scaling_helper.go
- cnf-certification-test/lifecycle/scaling/scaling_helper_test.go
- cnf-certification-test/lifecycle/suite.go
- cnf-certification-test/tnf_config.yml
- internal/clientsholder/clientsholder.go
- pkg/autodiscover/autodiscover.go
- pkg/autodiscover/autodiscover_podset.go
- pkg/autodiscover/autodiscover_scaleObject.go
- pkg/configuration/configuration.go
- pkg/provider/provider.go
- pkg/provider/scale_object.go
- pkg/provider/scale_object_test.go
crs scaling PR test case - if a crs had scaling object so that mean that we can scale it 
this PR include a regular scaling for that cr and hpa scaling
also it had a fix for a bug that we have on the hpa scaling- (checking if a specific kind had hpa by the scaleTrget)
> Crd scale - scale a crd that have a option of scaling in there role- regular scale and hpa scale

- cnf-certification-test/suite_test.go
#868 disabled it accidentally.
> Re-enable preflight suite

- go.mod
https://github.com/test-network-function/cnf-certification-test/pull/873 missed this.
> Forgot to update go.mod to 1.20

- internal/clientsholder/clientsholder.go
- pkg/autodiscover/autodiscover_pdbs_test.go
- pkg/autodiscover/autodiscover_podset_test.go
Increase coverage: 17.2% -> 26.1%
> autodiscover: add unit tests

- .github/workflows/pre-main.yaml
- Makefile
- run-cnf-suites.sh
- run-tnf-container.sh
- script/create-missing-test-files.sh
- script/create-version-files.sh
- script/get-git-latest-release.sh
- script/rhcos_versions.sh
- script/run-container.sh
See more:
https://github.com/mvdan/sh
The PR doesn't change code logic.
> Use shfmt linter

- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- Dockerfile
https://groups.google.com/g/golang-announce/c/3-TpUx48iQY
> Update Go to 1.20.2

- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
https://github.com/actions/setup-go/releases/tag/v4.0.0
> Update setup-go action to v4

- .github/actions/documentation/Dockerfile
- .github/dependabot.yml
- .github/workflows/pre-main.yaml
- Dockerfile
- Makefile
- https://github.com/hadolint/hadolint
- https://github.com/hadolint/hadolint-action
> Add Hadolint, a Dockerfile linter

- CATALOG.md
- cnf-certification-test/identifiers/identifiers.go
Fixing issue introduced in https://github.com/test-network-function/cnf-certification-test/pull/937
> Remove TestStorageRequiredPods duplicated entry

- .github/dependabot.yml
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot
> Add dependabot config for github actions

- docs/test-container.md
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.1.7
> Prepare for v4.1.7 release

- .github/workflows/pre-main.yaml
- README.md
- https://github.com/markdownlint/markdownlint
- https://github.com/nosborn/github-action-markdown-cli
- Unite all action linters.
> Add markdown linter

- script/results.html
This is to reformat the results.html file with vscode, upcoming PR modifying this file and formatted with vscode as well will show only code changes. There is no code changes in this PR.
> reformating results.html file 

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- Dockerfile
https://groups.google.com/g/golang-announce/c/Xdv6JL9ENs8
> Update Go to v1.20.3

- go.mod
- go.sum
https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.6.1
> Update preflight to v1.6.1

- docs/test-container.md
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.2.3
> Prepare for v4.2.3 release

- .github/workflows/self-hosted.yml
Related to: https://github.com/test-network-function/cnf-certification-test-partner/pull/257
> Switch to 'make bootstrap-cluster'

- cnf-certification-test/identifiers/identifiers.go
Related to [QE performance test](https://github.com/test-network-function/cnfcert-tests-verification/pull/305)
> Set flag to true for the implemented performance test

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.28.1
> Update operator-sdk to v1.28.1

- .github/workflows/tnf-image-4-0.yaml
- .github/workflows/tnf-image.yaml
- Makefile
- README.md
- docs/index.md
- docs/test-standalone.md
Just some various documentation updates.  Also I bumped the release level to 4.12 in the Makefile.
> Documentation Update

- script/results.html
- Download Results button renamed to "Download Results Feedback".
- Changed the name of the file that is created with the feedback from the partner to "results-feedback.html".
> Minor improvements for results.html

- run-cnf-suites.sh
Resolves: https://github.com/test-network-function/cnf-certification-test/issues/1069
> Add BASEDIR from suggestion

- go.mod
- go.sum
https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.6.3
> Update preflight to v1.6.3

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.3.0
> Prepare for v4.3.0 release

- CATALOG.md
- cnf-certification-test/identifiers/identifiers.go
- cnf-certification-test/lifecycle/suite.go
- cnf-certification-test/platform/hugepages/hugepages_test.go
- pkg/autodiscover/autodiscover.go
- pkg/provider/provider.go
Found some random typos that could use some correction.
> Fix some typos

- go.mod
- go.sum
https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.6.5
> Update preflight to v1.6.5

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/update-rhcos-mapping.yml
- Dockerfile
https://groups.google.com/g/golang-announce/c/q5135a9d924
> Update Go to v1.20.5

- CATALOG.md
- cnf-certification-test/identifiers/identifiers.go
- script/classification.js
- script/results-embed.html
- script/results.html
[CNFCERT-490]Auto-populate comments in HTML parser based on JSON
a download feedback button that downloading the feedback that we have now as a json file and by pressing upload feedback we can upload a json file of feedback
> add a download for feedback and upload previus feedback

- cmd/tnf/generate/qe_coverage/qe_coverage.go
> QE Coverage : Add more details in result

- cnf-certification-test/identifiers/identifiers.go
Related to issue [CNFCERT-512](https://issues.redhat.com/browse/CNFCERT-512)
> Mark manageability tests as implemented

- cmd/tnf/generate/qe_coverage/qe_coverage.go
- cmd/tnf/main.go
> Enhance tnf tool

- internal/certdb/offlinecheck/helm.go
- internal/certdb/offlinecheck/helm_test.go
using https://github.com/Masterminds/semver to perform the check
> Fix checking semver version against contraint version

- go.mod
- go.sum
build-depends: 28703
https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.6.9
> Update preflight to v1.6.9

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.30.0
> Update operator-sdk to v1.30.0

- cnf-certification-test/performance/suite.go
Adds compliant and non-compliant objects to a few tests in the `performance` test suite.
> Add performance failure reason objects

- CATALOG.md
- cmd/tnf/generate/catalog/catalog.go
- cnf-certification-test/chaostesting/suite.go
- cnf-certification-test/common/constant.go
- cnf-certification-test/identifiers/identifiers.go
- cnf-certification-test/results/html/classification.js
- cnf-certification-test/results/html/results-embed.html
- generated_policy.json
> chaos-testing: comment out the existing suite as only contains an example test case

- cnf-certification-test/identifiers/identifiers.go
QE coverage change: 79% -> 80%
> Set the QE coverage flag for the test case one-process-per-container

- go.mod
- go.sum
https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.6.10
> Update preflight to v1.6.10

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.3.1
> Prepare for v4.3.1

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/update-rhcos-mapping.yml
- Dockerfile
https://groups.google.com/g/golang-announce/c/2q13H6LEEx0
> Update Go to v1.20.6

- cnf-certification-test/identifiers/identifiers.go
QE coverage change: 80% -> 82%
> Set the undeclared-container-ports-usage test case as QE covered

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.3.2
> Prepare for v4.3.2

- .golangci.yml
- cmd/tnf/claim/add/add.go
- cnf-certification-test/accesscontrol/securitycontextcontainer/securitycontextcontainer.go
- cnf-certification-test/accesscontrol/suite.go
- cnf-certification-test/chaostesting/pod_delete/pod_delete.go
- cnf-certification-test/lifecycle/scaling/crd_scaling.go
- cnf-certification-test/lifecycle/tolerations/tolerations.go
- cnf-certification-test/platform/suite.go
- internal/certdb/offlinecheck/operator.go
- internal/clientsholder/clientsholder.go
- pkg/provider/containers.go
- pkg/provider/operators.go
> Fix error handling logic for no SSHd check

- cnf-certification-test/results/html/results-embed.html
- cnf-certification-test/results/html/results.html
https://github.com/jquery/jquery/releases/tag/3.7.0 
Related to: https://github.com/test-network-function/parser/pull/4
> Update jquery to v3.7.0

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.31.0
> Update operator-sdk to v1.31.0

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.3.3
> Prepare for v4.3.3

- go.mod
- go.sum
https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.6.11
> Update preflight to v1.6.11

- cnf-certification-test/identifiers/identifiers.go
for operator-install-source test
> updated qe coverage variable

- .github/workflows/qe.yaml
Follow up to #1255 
Depends on fixes found in: #1305
> Enable manageability QE PR tests

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/update-rhcos-mapping.yml
- Dockerfile
https://groups.google.com/g/golang-announce/c/X0b6CsSAaYI
> Update Go to v1.20.7

- .github/workflows/pre-main.yaml
Playing around with some runner cleanup actions.  This action cleans up 28 GB of space on the free tier runner!  🤯 
https://github.com/jlumbroso/free-disk-space
> Use free-disk-space action to cleanup

- .github/workflows/qe.yaml
> Enable performance QE suite

- cnf-certification-test/identifiers/identifiers.go
* operator-install-status-succeeded
* operator-install-no-privileged
QE coverage: 88%
> Set a couple of operator test cases as QE covered

- .golangci.yml
- Makefile
- cnf-certification-test/accesscontrol/rbac/automount_test.go
- cnf-certification-test/lifecycle/suite.go
- cnf-certification-test/lifecycle/volumes/volumes_test.go
- cnf-certification-test/networking/policies/policies_test.go
- cnf-certification-test/observability/pdb/pdb_test.go
- docs/test-standalone.md
- pkg/scheduling/scheduling.go
https://github.com/golangci/golangci-lint/releases/tag/v1.54.2
> Update GolangCI-lint to v1.54.2

- cnf-certification-test/accesscontrol/suite.go
- cnf-certification-test/identifiers/doclinks.go
- cnf-certification-test/identifiers/identifiers.go
- cnf-certification-test/identifiers/remediation.go
Static detection making use of the BPF capability.
> access-control: add detection of eBPF filter loading

- cnf-certification-test/observability/suite.go
Updated test case: observability-pod-disruption-budget
> Bug fix: consider the case PDB defined but no label match

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.3.5
> Prepare for v4.3.5

- .github/workflows/self-hosted.yml
Just playing around with stability of the runners.
> Prune everything in self-hosted

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/update-rhcos-mapping.yml
- Dockerfile
https://groups.google.com/g/golang-announce/c/Fm51GRLNRvM
> Update Go to v1.21.1

- .github/workflows/pre-main.yaml
- .github/workflows/qe.yaml
- .github/workflows/self-hosted.yml
Playing around with crons and github actions.
> Enable QE tests for nightly runs

- .github/workflows/pre-main.yaml
- Makefile
This allows to have dependencies between PR in the Github actions like in DCI.
> GitHub actions use Depends-On: strings in the PR description

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.4.0
> Prepare for v4.4.0

- cnf-certification-test/accesscontrol/suite.go
Similar to: https://github.com/test-network-function/cnf-certification-test/pull/1433
> Fix report objects for hostpath test

- .github/workflows/qe.yaml
Marked WIP until everything passes then I'll remove the PR checks.
> Enable more suites for QE nightly runs

- .github/workflows/pre-main.yaml
- .github/workflows/qe-hosted.yml
They merged a bunch of changes and made a release this morning.
> Free-disk-space update

- internal/certdb/onlinecheck/onlinecheck.go
Adds an additional digest check to support multi architecture images. Images that support multiple achitecture (arm64, amd64, ...) do not use image_id digest. Instead they are using the manifest_list_digest. The manifest_list_digest stays the same for the same image compiled for multiple architectures.
For offline support: https://github.com/test-network-function/oct/pull/66
> add check for "manifest_list_digest" when looking for certified containers by digest

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.32.0
> Update operator-sdk to v1.32.0

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.5.1
> Prepare for v4.5.1

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/qe-hosted.yml
- .github/workflows/update-rhcos-mapping.yml
- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/iNNxDTCjZvo
> Update Go to v1.21.3

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.5.2
> Prepare for v4.5.2

- .github/workflows/preflight.yml
Similar to: https://github.com/test-network-function/cnf-certification-test-partner/pull/368
> Add cron to run preflight against unstable image

- .github/workflows/qe-ocp-intrusive.yaml
- Adds a YAML for nightly intrusive testing.
- Adds a docker cleanup prior to running the tests.
> Add YAML for intrusive QE OCP testing

- .github/workflows/pre-main.yaml
- .golangci.yml
- Makefile
- cnf-certification-test/identifiers/identifiers.go
- cnf-certification-test/platform/cnffsdiff/fsdiff_test.go
- docs/test-standalone.md
- internal/crclient/crclient.go
- pkg/scheduling/scheduling.go
https://github.com/golangci/golangci-lint/releases/tag/v1.55.1
> Update GolangCI-lint to v1.55.1

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.5.4
> Prepare for v4.5.4

- cnf-certification-test/performance/suite.go
Fix regression from
https://github.com/test-network-function/cnf-certification-test/pull/1590
passing performance QE test:
https://github.com/test-network-function/cnf-certification-test/actions/runs/6802199359
https://github.com/test-network-function/cnf-certification-test/actions/runs/6802987960
> Fix regression in  performance-rt-apps-no-exec-probes

- version.json
> Getting bugfix for parser (still needing bootstrap for some elements)

- .github/workflows/pre-main.yaml
- pkg/configuration/configuration.go
Bonus: Added `ENABLE_DATA_COLLECTION` envconfig flag.
> Temporarily disable collector

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.5.5
> Prepare for v4.5.5

- .github/actions/setup/action.yml
- .github/workflows/qe-hosted.yml
Related to: https://github.com/actions/setup-go/issues/403
> Disable Go cache for self-hosted

- .github/workflows/qe-hosted.yml
- .github/workflows/qe-ocp-413-intrusive.yaml
- .github/workflows/qe-ocp-413.yaml
- .github/workflows/qe-ocp-414-intrusive.yaml
- .github/workflows/qe-ocp-414.yaml
- .github/workflows/qe.yaml
> QE Test: Remove keep-going flag

- cnf-certification-test/accesscontrol/suite.go
- generated_policy.json
- main.go
- pkg/testhelper/testhelper.go
Similar to: https://github.com/test-network-function/cnf-certification-test/pull/1614
> Transition accesscontrol suite to ginkgoless

- .github/workflows/pre-main.yaml
> Temp. disable collector sanity check

- cnf-certification-test/platform/suite.go
- generated_policy.json
- main.go
- pkg/certsuite/certsuite.go
- pkg/testhelper/testhelper.go
Also added all the needed skip functions to the testhelper package.
> Transition platform-alteration suite to ginkgoless.

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v4.5.7
> Prepare for v4.5.7

- pkg/checksdb/checksgroup.go
If a check returns error, due to a panic or a error returned from the checkFn(), the remaining checks should be skipped.
The previous code was setting the result of the remaining checks to "skipped" from onFailre(), but that result was overwritten later, as the check wasn't actually skipped.
> Bugfix: skip execution of remaining checks on error/panic.

- pkg/checksdb/checksdb.go
PR 1694 did not apply anything - not sure what happened
> Only capture ctrl-c while tests are running

- cmd/tnf/claim/show/csv/csv.go
- cmd/tnf/pkg/claim/claim.go
Add a new column, 'Operator Version,' to the resulted CSV table.
> Add operator versions

- run-basic-batch-operators-test.sh
build-depends: https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/91
> skip operator if claim file couldn't be parsed

- .github/workflows/qe-ocp-413-intrusive.yaml
- .github/workflows/qe-ocp-413.yaml
- .github/workflows/qe-ocp-414-intrusive.yaml
- .github/workflows/qe-ocp-414.yaml
Reverts test-network-function/cnf-certification-test#1723
This wasn't doing what I thought would happen so I'm reverting it.
> Revert "Enable QE nightlies for ginkgo_removal"

- .github/workflows/qe-hosted.yml
build-depends: https://github.com/redhatci/ansible-collection-redhatci-ocp/pull/100
Marked WIP to see if this works.
> Enable QE PR tests

- cnf-certification-test/manageability/suite.go
> manageability: review logs

- cnf-certification-test/operator/suite.go
> operator: review logs

- .github/workflows/pre-main.yaml
- .github/workflows/qe-hosted.yml
Follow up to #1774 
Removes any references to `ginkgo_removal`.
> Remove ginkgo_removal refs

- cnf-certification-test/accesscontrol/suite.go
- cnf-certification-test/lifecycle/suite.go
- cnf-certification-test/manageability/suite.go
- cnf-certification-test/networking/suite.go
> More consolidation to checksGroup.Add calls

- cnf-certification-test/certification/suite.go
> certification: review logs

- version.json
related to https://github.com/test-network-function/parser/pull/35
> bump parser version to 0.4.3

- cnf-certification-test/platform/suite.go
- pkg/provider/pods.go
> platform: review logs

- cnf-certification-test/lifecycle/ownerreference/ownerreference.go
- cnf-certification-test/lifecycle/ownerreference/ownerreference_test.go
- cnf-certification-test/lifecycle/podsets/podsets.go
- cnf-certification-test/lifecycle/scaling/crd_scaling.go
- cnf-certification-test/lifecycle/scaling/deployment_scaling.go
- cnf-certification-test/lifecycle/scaling/deployment_scaling_test.go
- cnf-certification-test/lifecycle/scaling/statefulset_scaling.go
- cnf-certification-test/lifecycle/suite.go
- pkg/provider/pods.go
> lifecycle: logs review

- cnf-certification-test/preflight/suite.go
- pkg/provider/containers.go
- pkg/provider/operators.go
> preflight: review logs

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v5.0.0
> Prepare for v5.0.0

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v5.0.1
> Prepare for v5.0.1

- internal/cli/cli.go
- main.go
- pkg/certsuite/certsuite.go
- pkg/checksdb/checksdb.go
Enable the flag `-L/--list` to list the checks.
> flags: allow filtered checks listing

- .github/workflows/qe-hosted.yml
- .github/workflows/qe-ocp-413-intrusive.yaml
- .github/workflows/qe-ocp-413.yaml
- .github/workflows/qe-ocp-414-intrusive.yaml
- .github/workflows/qe-ocp-414.yaml
Related to: https://github.com/test-network-function/cnfcert-tests-verification/pull/685
> Pass Github run ID into QE for collector

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v5.0.2
> Prepare for v5.0.2

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/preflight.yml
- .github/workflows/update-rhcos-mapping.yml
- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/Qdkw_yX60TE
> Update Go to v1.21.7

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v5.0.3
> Prepare for v5.0.3

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.34.0
> Update operator-sdk to v1.34.0

- pkg/certsuite/certsuite.go
Currently, the return code of the `cnf-certification-test` binary is an error code if there is an issue preventing a correct execution or if there are failed test cases. But having failed test cases is just an indication of a workload that does not meet some requirements, not a problem with the CNF Certification itself, so the return code should show that the execution was successful. The results of the execution should always be checked using the information provided in the CLI or in the claim or log file but not using the binary's return code.
This change modifies the return code of the `cnf-certification-test` binary to be successful even if there are some test cases that fail, leaving the error codes for actual runtime errors.
> Only return error when an actual error occurs during a CNF run

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/preflight.yml
- .github/workflows/update-rhcos-mapping.yml
- Dockerfile
- docs/test-standalone.md
- go.mod
https://tip.golang.org/doc/go1.22
> Update Go to v1.22

- version.json
related to: test-network-function/parser#38
> Bumping the parser version to v0.4.4 to fix SRI issue (javascript)

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.34.1
> Update operator-sdk to v1.34.1

- cnf-certification-test/accesscontrol/suite.go
- cnf-certification-test/networking/netcommons/netcommons.go
- cnf-certification-test/networking/netutil/netutil.go
- cnf-certification-test/networking/suite.go
The conversion `strconv.atoi` was throwing a code scanning error:
> Fix integer conversions

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v5.0.5
> Prepare for v5.0.5

- cnf-certification-test/manageability/suite.go
Adding documentation for all the functions in manageability.
> Documentation for all the functions in Manageability

- .github/workflows/pre-main.yaml
- .github/workflows/tnf-image.yaml
- Dockerfile
- Makefile
Enables multi-arch builds for our images for both arm64 and amd64.
> Enable multi-platform image builds

- CATALOG.md
- cmd/tnf/check/results/results.go
- cnf-certification-test/identifiers/doclinks.go
- cnf-certification-test/identifiers/identifiers.go
- cnf-certification-test/identifiers/remediation.go
- cnf-certification-test/operator/suite.go
- expected_results.yaml
- pkg/autodiscover/autodiscover.go
- pkg/autodiscover/autodiscover_crds.go
- pkg/autodiscover/autodiscover_crds_test.go
- pkg/provider/provider.go
- pkg/testhelper/testhelper.go
Refers [CNFCERT-899](https://issues.redhat.com/browse/CNFCERT-899)
Includes : 
* Check for OpenAPI spec
* Fix for handling larger test result file
* Refactoring of CRD retrieval code and associated new unit tests
* Sorted the expected_results entries.
> feat : Operator CRD has OpenAPI spec

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v5.0.6
> Prepare for v5.0.6

- expected_results.yaml
Move "access-control-crd-roles" from "skip" to "pass".
Depends-On: [cnf-certification-test-partner#418](https://github.com/test-network-function/cnf-certification-test-partner/pull/418)
> Update the expected results template

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/preflight.yml
- .github/workflows/update-rhcos-mapping.yml
- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/YgW0sx8mN3M
> Update Go to v1.22.2

- run-basic-batch-operators-test.sh
Added full log link on html page.
Using operator oc plugin instead of tasty
Simplify worflow to avoid unnecessary retries
Added additional failure checks that are displayed on the webpage
> Operator script: Improved log output with limited information on command line and color coding.

- .github/workflows/qe-ocp-415-intrusive.yaml
- .github/workflows/qe-ocp-415.yaml
Change the `4.13` nightly to `4.15` which involves changing some strings and changing the name of the file.
> Change 4.13 QE nightly to 4.15

- .github/workflows/update-rhcos-mapping.yml
Adds the ability to kick off the script update job with a UI button.
> Add workflow_dispatch to RHCOS job

- expected_results.yaml
Move "lifecycle-affinity-required-pods" from "skip" to "pass".
> Update expected results template

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v5.0.7
> Prepare for v5.0.7

- .github/workflows/qe-ocp-414-intrusive.yaml
- .github/workflows/qe-ocp-414.yaml
- .github/workflows/qe-ocp-415-intrusive.yaml
- .github/workflows/qe-ocp-415.yaml
Related to: https://github.com/test-network-function/cnfcert-tests-verification/pull/738
> Clean openshift-marketplace namespaces in QE

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v5.0.8
> Prepare for v5.0.8

- README.md
Properly fill repository org and name to pull test results
> Fix OSSF scorecard badge

- README.md
Adds some badges for our two nightly OCP runs.
> Add README badges for QE OCP nightlies

- .github/workflows/pre-main.yaml
- .golangci.yml
- Makefile
- cmd/tnf/check/results/results.go
- cmd/tnf/generate/qe_coverage/qe_coverage.go
- cnf-certification-test/lifecycle/scaling/crd_scaling.go
- cnf-certification-test/webserver/webserver.go
- docs/test-standalone.md
- internal/cli/cli.go
- internal/clientsholder/clientsholder.go
- internal/log/log.go
- pkg/compatibility/compatibility.go
https://github.com/golangci/golangci-lint/releases/tag/v1.58.1
> Update GolangCI-lint to v1.58.1

- go.mod
- go.sum
https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.9.4
> Update preflight to v1.9.4

- docs/runtime-env.md
- docs/test-container.md
- pkg/provider/provider.go
- pkg/provider/provider_test.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v5.1.0
> Prepare for v5.1.0

- .github/workflows/qe-hosted.yml
Right now we're seeing this get stuck for hours.
> Add 10 minute timeout for waiting for all pods to be ready

- .github/workflows/pre-main.yaml
- .github/workflows/preflight.yml
- .github/workflows/qe-hosted.yml
- .github/workflows/tnf-image.yaml
- .github/workflows/update-rhcos-mapping.yml
Related to: https://github.com/actions/runner-images/issues/9848
Checking to see what happens to our CI when ran on ubuntu-24.04.
> Update ubuntu runners to 24.04

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.34.2
> Update operator-sdk to v1.34.2

- run-basic-batch-operators-test.sh
Instead of getting as an input a catalog name, the script will get a catalog index and will create a "CatalogSource" resource based on it.  At the end of the run the "CatalogSource" will be deleted.
* In addition the "status" variable was removed - the exit code is checked after every command and an error will appear if necessary.
> Batch operators test catalog source automation

- cmd/certsuite/run/run.go
- docs/runtime-env.md
- docs/test-container.md
- pkg/configuration/configuration.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v5.1.1
> Prepare for v5.1.1

- .github/actions/install-yaml-dep/action.yml
- .github/actions/setup-partner-cluster/action.yml
- .github/workflows/pre-main.yaml
- .github/workflows/qe-hosted.yml
Moving all of these similar tasks into a shared action YAML.
> Consolidate shared tasks into composite actions

- cnf-certification-test/networking/services/services_test.go
- pkg/provider/provider_test.go
- pkg/versions/versions_test.go
Just some additional unit tests, low hanging fruit.
> Add various unit tests

- go.mod
- go.sum
https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.9.6
> Update preflight to v1.9.6

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/preflight.yml
- .github/workflows/update-rhcos-mapping.yml
- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/XbxouI9gY7k
> Update Go to v1.22.4

- .github/workflows/qe-ocp-416-intrusive.yaml
- .github/workflows/qe-ocp-416.yaml
Adds a YAML for the OCP 4.16 nightly runs.
> Add OCP 4.16 nightly YAML

- .github/workflows/qe-ocp-416-intrusive.yaml
- .github/workflows/qe-ocp-416.yaml
> Adjust 'runs-on' label

- cnf-certification-test/operator/suite.go
This PR changes the existing code that considered all operators in the cluster to only test operators which are labelled by the partner.
> fix : Limit operator test suits TC to test operators only

- pkg/testhelper/testhelper.go
This PR will fix the broken QE tests from [this PR](https://github.com/test-network-function/cnf-certification-test/pull/2145)
> Fix Skip Function for Crds

- run-basic-batch-operators-test.sh
It replaces the legacy "run-tnf-container.sh" script.
> Use the certsuite command in "run-basic-batch-operators-test.sh"

- cmd/certsuite/run/run.go
- docs/runtime-env.md
- docs/test-container.md
- pkg/configuration/configuration.go
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v5.1.2
> Prepare for v5.1.2

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.35.0
> Update operator-sdk to v1.35.0

- script/rhcos_versions.sh
Related to: #2187 
Adds 4.17 to the channels list for the RHCOS script.
> Add 4.17 to RHCOS script

- cnf-certification-test/platform/isredhat/isredhat.go
- cnf-certification-test/platform/isredhat/isredhat_test.go
Adds a logging line and a unit test case for UBI9 based images.
> Add logging; unit tests for UBI9

- cnf-certification-test/accesscontrol/suite.go
- cnf-certification-test/lifecycle/suite.go
- cnf-certification-test/networking/suite.go
- cnf-certification-test/performance/suite.go
- cnf-certification-test/platform/suite.go
- pkg/autodiscover/autodiscover.go
- pkg/checksdb/check.go
Found some typos that can be corrected.
> Adjust typos

- cmd/certsuite/run/run.go
- docs/runtime-env.md
- docs/test-run.md
- pkg/configuration/configuration.go
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v5.1.3
> Prepare for v5.1.3

- script/run-basic-batch-operators-test.sh
Fixed directory of the `certsuite` executable.
> Change batch script run suites cmd

- cmd/certsuite/run/run.go
- docs/runtime-env.md
- docs/test-run.md
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v5.2.0
> Prepare for v5.2.0

- internal/log/log.go
- pkg/checksdb/check_test.go
Includes some changes from: #2195
> Add check pkg unit tests

- .golangci.yml
- Makefile
- cmd/certsuite/run/run.go
https://github.com/golangci/golangci-lint/releases/tag/v1.59.1
> Update GolangCI-lint to v1.59.1

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/preflight.yml
- .github/workflows/update-rhcos-mapping.yml
- .github/workflows/upload-release-assets.yaml
- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/gyb7aM1C9H4
> Update Go to v1.22.5

- cmd/certsuite/run/run.go
- docs/runtime-env.md
- docs/test-run.md
- version.json
https://github.com/test-network-function/cnf-certification-test-partner/releases/tag/v5.2.1
> Prepare for v5.2.1

- script/rhcos_versions.sh
https://github.com/test-network-function/cnf-certification-test/pull/2237 broke the script.
> Fix RHCOS version script

- .github/workflows/pre-main.yaml
> Missed version update for golangci

- Dockerfile
- Makefile
Reverts test-network-function/cnf-certification-test#2263
> Revert "Remove some dependencies from the image"

- internal/datautil/data_util.go
- internal/datautil/data_util_test.go
This new package can contain functions used for comparing or transforming data structs such as maps, slices or other complex structures.
This commit adds a function "IsMapSubset()" to find if a map is the subset of another.
> internal/datautil: add new package for basic data handling

- .github/workflows/tnf-image.yaml
This variable is unused.  Removing it.
> Remove RELEASE_LEVEL

- docs/data-collection.md
- mkdocs.yml
This PR adds documentation regarding the use of the [Collector](https://github.com/test-network-function/collector)
> Add data collection doc

- .github/workflows/pre-main.yaml
- cmd/certsuite/run/run.go
- docs/runtime-env.md
- version.json
https://github.com/test-network-function/k8s-best-practices-debug/releases/tag/v0.0.3
> Update debug image to v0.0.3

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.36.0
> Update operator-sdk to v1.36.0

- pkg/claimhelper/claimhelper.go
Reverts test-network-function/cnf-certification-test#2306
> Revert "Remove unused func in claimhelper"

- .github/workflows/qe-ocp-pre-main.yaml
This is for #2303 since we are adding an OCP-only test there.
> Enable observability suite for PR OCP testing

- .github/workflows/pre-main.yaml
- cmd/certsuite/run/run.go
- docs/runtime-env.md
- version.json
https://github.com/test-network-function/k8s-best-practices-debug/releases/tag/v0.0.4
> Update debug image to v0.0.4

- .github/workflows/pre-main.yaml
- .github/workflows/tnf-image.yaml
Follow up to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/2321
> Fix unstable push; add legacy image to tnf image yaml

- .github/workflows/tnf-image.yaml
> Fix DEBUG_ variables

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.36.1
> Update operator-sdk to v1.36.1

- README.md
- docs/developers.md
- Moved linter list from the README to developers page.
- Fix linter issues
> doc : Fix on topics

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/preflight.yml
- .github/workflows/update-rhcos-mapping.yml
- .github/workflows/upload-release-assets.yaml
- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/X4q_-Wf-5g4
> Update Go to v1.22.6

- go.mod
- go.sum
Related to: https://github.com/redhat-best-practices-for-k8s/certsuite-qe/pull/881
> Update openshift libraries manually

- Makefile
https://github.com/golangci/golangci-lint/releases/tag/v1.60.3
> Update GolangCI-lint to v1.60.3

- .github/workflows/pre-main.yaml
- cmd/certsuite/run/run.go
- docs/runtime-env.md
- version.json
https://github.com/redhat-best-practices-for-k8s/certsuite-probe/releases/tag/v0.0.7
> Update probe to v0.0.7

- expected_results.yaml
- tests/operator/suite.go
build-depends: https://github.com/dci-labs/dallas-pipelines/pull/1210
> Fix OperatorAutomountTokens reversed result

- .github/workflows/pre-main.yaml
The sanity check continues to fail.  I think we might need a bigger VM to run the collector on.
> Temporarily disable collector sanity check

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/preflight.yml
- .github/workflows/update-rhcos-mapping.yml
- .github/workflows/upload-release-assets.yaml
- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/K-cEzDeCtpc
> Update Go to v1.23.1

- pkg/provider/operators.go
- pkg/provider/provider.go
Change `createOperators()` to accept `AllSubscriptions` instead of `Subscriptions` which is limited to subscriptions from the target namespace.
> Look through all subscriptions for install source

- .github/workflows/qe-ocp-414-intrusive.yaml
- .github/workflows/qe-ocp-414.yaml
- .github/workflows/qe-ocp-415-intrusive.yaml
- .github/workflows/qe-ocp-415.yaml
- .github/workflows/qe-ocp-416-intrusive.yaml
- .github/workflows/qe-ocp-416.yaml
- .github/workflows/qe-ocp-417-intrusive.yaml
- .github/workflows/qe-ocp-417.yaml
- .github/workflows/qe-ocp-arm-416.yaml
- .github/workflows/qe-ocp-pre-main.yaml
Cleanup the dangling images post-run.
> Add docker image cleanup to self-hosted YAMLs

- go.mod
- webserver/webserver.go
Checking what happens if we update the v2 go-yaml library to v3.
> Update yaml from v2 to v3

- .github/workflows/pre-main.yaml
- cmd/certsuite/run/run.go
- docs/runtime-env.md
- version.json
https://github.com/redhat-best-practices-for-k8s/certsuite-probe/releases/tag/v0.0.9
> Update probe image to v0.0.9

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.37.0
> Update operator-sdk to v1.37.0

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/preflight.yml
- .github/workflows/update-rhcos-mapping.yml
- .github/workflows/upload-release-assets.yaml
- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/NKEc8VT7Fz0
> Update Go to v1.23.2

- .github/workflows/pre-main.yaml
- cmd/certsuite/run/run.go
- docs/runtime-env.md
- version.json
https://github.com/redhat-best-practices-for-k8s/certsuite-probe/releases/tag/v0.0.10
> Update probe to v0.0.10

- CATALOG.md
The CATALOG.md wasn't generated to be up to date on `main`.
> Manually re-run CATALOG.md build

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/preflight.yml
- .github/workflows/update-rhcos-mapping.yml
- .github/workflows/upload-release-assets.yaml
- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/X5KodEJYuqI?pli=1
> Update Go to v1.23.3

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.38.0
> Update operator-sdk to v1.38.0

- pkg/testhelper/testhelper_test.go
Add some additional tests for the `testhelper` package.
> Add additional testhelper pkg unit tests

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/preflight.yml
- .github/workflows/update-rhcos-mapping.yml
- .github/workflows/upload-release-assets.yaml
- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/3DyiMkYx4Fo
> Update Go to v1.23.4

- .github/workflows/pre-main.yaml
- .golangci.yml
- Makefile
- tests/accesscontrol/suite.go
- tests/networking/suite.go
- webserver/webserver.go
https://github.com/golangci/golangci-lint/releases/tag/v1.63.3
> Update GolangCI-lint to v1.63.3

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.39.1
> Update operator-sdk to v1.39.1

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/preflight.yml
- .github/workflows/update-rhcos-mapping.yml
- .github/workflows/upload-release-assets.yaml
- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/sSaUhLA-2SI
> Update Go to v1.23.5

- Makefile
https://github.com/golangci/golangci-lint/releases/tag/v1.63.4
> Update GolangCI-lint to v1.63.4

- version.json
https://github.com/redhat-best-practices-for-k8s/parser/releases/tag/v0.5.1
https://github.com/redhat-best-practices-for-k8s/certsuite-probe/releases/tag/v0.0.12
> Update parser to v0.5.1; probe to v0.0.12

- .github/workflows/qe-ocp-414-intrusive.yaml
- .github/workflows/qe-ocp-415-intrusive.yaml
- .github/workflows/qe-ocp-416-intrusive.yaml
- .github/workflows/qe-ocp-417-intrusive.yaml
Fix these values to run the intrusive tests against the binary as part of the "intrusive" YAMLs.
> Fix intrusive QE tests that run against binary

- tests/operator/suite.go
`uniqueOnwnedCrds` --> `uniqueOwnedCrds`
> Adjust some typos

- .github/actions/setup/action.yml
- .github/workflows/codeql-analysis.yml
- .github/workflows/merge.yaml
- .github/workflows/pre-main.yaml
- .github/workflows/preflight.yml
- .github/workflows/update-rhcos-mapping.yml
- .github/workflows/upload-release-assets.yaml
- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/xU1ZCHUZw3k
> Update Go to v1.23.6

- .github/workflows/pre-main.yaml
- Makefile
https://github.com/golangci/golangci-lint/releases/tag/v1.64.3
> Update GolangCI to v1.64.3

- tests/operator/helper.go
- tests/operator/helper_test.go
> Add unit test for the operator helper

- .github/actions/setup-partner-cluster/action.yml
- .github/workflows/qe-ocp-hosted.yml
https://github.com/palmsoftware/quick-k8s/releases/tag/v0.0.21
https://github.com/palmsoftware/quick-ocp/releases/tag/v0.0.4
> Update quick-* versions

- tests/identifiers/identifiers.go
Related to https://github.com/redhat-best-practices-for-k8s/certsuite-qe/pull/1084
> Flag the test as QE test covered

- .github/dependabot.yml
> Add grouping to other dependabot categories

- CATALOG.md
- README.md
- cmd/certsuite/generate/catalog/catalog.go
- docs/configuration.md
- docs/test-spec-implementation.md
- docs/workload-developers.md
Adding bars `|` to fix the linter.
> Fix markdown

- .github/workflows/pre-main.yaml
- cmd/certsuite/run/run.go
- docs/runtime-env.md
- version.json
https://github.com/redhat-best-practices-for-k8s/certsuite-probe/releases/tag/v0.0.15
> Update -probe to v0.0.15

- .github/workflows/qe-ocp-hosted.yml
Increase the retries from 1 to 3 to help smooth out the nightlies.
> Increase CRC QE attempts

- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/4t3lzH3I0eI/m/b42ImqrBAQAJ
> Update Go to v1.24.1

- .github/workflows/qe-hosted-arm.yml
- .github/workflows/qe-hosted.yml
Remove the wait-for-pods script.
> Remove for wait-for-pods script

- tests/platform/cnffsdiff/fsdiff.go
We have seen where a container is initially `Running` during autodiscover, it might fall into a `CrashLoopBackOff` state before the test is executed.  Let's add some retries here to see if we can smooth out any potential errors.
> fsdiff: add retries around runPodmanDiff command

- script/rekick-failed-workflows.sh
There are sometimes runs that end in a timeout that can also be rekicked.
> script: Add runs that timed out

- go.mod
https://github.com/redhat-openshift-ecosystem/openshift-preflight/releases/tag/1.13.0
> Update preflight to v1.13.0

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.39.2
> Update operator-sdk to v1.39.2

- .github/workflows/pre-main.yaml
- cmd/certsuite/run/run.go
- docs/runtime-env.md
https://github.com/redhat-best-practices-for-k8s/certsuite-probe/releases/tag/v0.0.16
> Update probe image to v0.0.16

- version.json
https://github.com/redhat-best-practices-for-k8s/certsuite-probe/releases/tag/v0.0.16
> Update -probe to v0.0.16

- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/UZoIkUT367A/m/5WDxKizJAQAJ
> Update Go to v1.24.3

- Dockerfile
- go.mod
https://groups.google.com/g/golang-announce/c/ufZ8WpEsA3A/m/XDxq7uidAgAJ
> Update Go to v1.24.4

- Dockerfile
https://github.com/operator-framework/operator-sdk/releases/tag/v1.40.0
> Update operator-sdk to v1.40.0

- script/rekick-failed-workflows.sh
Follow up to #3001 
Adds the ability to rekick these jobs if failed.
> script: update rekick script with 4.18 jobs

- internal/crclient/crclient.go
Adds a retry loop around the call to exec for the `nsenter` command.  Retry 5 times with a 3 second sleep in between each attempt.
> nsenter: add retry logic

- script/rekick-failed-workflows.sh
Adjusting the rekick script to default to 24 hours back for jobs and will allow for a `-d` flag to pass a number of days back to look.
> Adjust rekick script to default to 24 hours back; add flag

- .github/workflows/qe-ocp-418-intrusive.yaml
- .github/workflows/qe-ocp-418.yaml
- .github/workflows/qe-ocp-hosted.yml
https://github.com/palmsoftware/quick-ocp/releases/tag/v0.0.16
> Update quick-ocp to v0.0.16

- .github/actions/setup-partner-cluster/action.yml
- .github/workflows/pre-main.yaml
- .github/workflows/qe-hosted-arm.yml
- .github/workflows/qe-hosted.yml
- .github/workflows/qe-ocp-414-intrusive.yaml
- .github/workflows/qe-ocp-414.yaml
- .github/workflows/qe-ocp-415-intrusive.yaml
- .github/workflows/qe-ocp-415.yaml
- .github/workflows/qe-ocp-416-intrusive.yaml
- .github/workflows/qe-ocp-416.yaml
- .github/workflows/qe-ocp-417-intrusive.yaml
- .github/workflows/qe-ocp-417.yaml
- .github/workflows/qe-ocp-418-intrusive.yaml
- .github/workflows/qe-ocp-418.yaml
- .github/workflows/qe-ocp-arm-416.yaml
- .github/workflows/qe-ocp-pre-main.yaml
Giving some extra headroom to these jobs.
> Increase retry timeouts

- .github/workflows/pre-main.yaml
- CATALOG.md
- Makefile
- cmd/certsuite/generate/catalog/catalog.go
- tests/identifiers/impact.go
Related to https://github.com/redhat-best-practices-for-k8s/certsuite/issues/3013
This PR adds an impact statement for each test. The impact statement describes the impacts and potential risks of non-compliance with best practices. 
Rendered catalog: https://github.com/redhat-best-practices-for-k8s/certsuite/blob/79f117b412655361d4590f02a03b3f2da2068df9/CATALOG.md
Assisted-by: Cursor AI Editor
> Add impact statement

- .github/workflows/qe-hosted.yml
- .github/workflows/update-dashboard.yml
- CATALOG.md
- Makefile
- README.md
- docs/developers.md
- docs/nightlies.md
- docs/nightlies/index.html
- docs/runtime-env.md
- mkdocs.yml
Creates a new dashboard for monitoring our nightlies ⭐ 
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R27-R28): Added a link to the **nightlies dashboard** for monitoring QE workflow health.
* [`docs/nightlies.md`](diffhunk://#diff-6fd28361dc89af73cd6af44120d72efcf0d5c8a7e460904f83f2867ac1c9ededR1-R35): Created a new documentation file detailing the Nightlies Dashboard, its features, monitored workflows, and access instructions.
* [`mkdocs.yml`](diffhunk://#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2R66): Updated the navigation structure to include the Nightlies Dashboard documentation.
> Create nightlies dashboard

- Dockerfile
- go.mod
> Update Go to v1.25.0

- .github/workflows/probe-update.yaml
Follow up to: https://github.com/redhat-best-practices-for-k8s/certsuite/pull/3195
> Add missing pre-main.yaml to new probe script

- script/rhcos_versions.sh
Added support for the `4.21` release channel by including it in the `CHANNELS` array.
> Add 4.21 to RHCOS script

- internal/clientsholder/command.go
Instead of an infinite context for ExecCommand, let's add a limit of 30 seconds (arguable) to make sure we don't wait forever.
> Add 30 second timeout for ExecCommandContainer
